<?php

return [
    'UAE' => [
        'continent' => 'Asia',
        'cities' => [
            'Abu Dhabi',
            'Al Ain',
            'Ajman',
            'Dubai',
            'Sharjah',
            'RAK',
            'Fujairah',
            'UAQ',
        ],
    ],
    'Bhutan' => [
        'continent' => 'Asia',
        'cities' => [
            'Punakha',
        ],
    ],
    'Jersey' => [
        'continent' => 'Europe',
        'cities' => [
            'St Saviour',
        ],
    ],
    'Nepal' => [
        'continent' => 'Asia',
        'cities' => [
            'Lumbini',
        ],
    ],
    'Guatemala' => [
        'continent' => 'Central America',
        'cities' => [
            'Pacaya Volcano',
        ],
    ],
    'Qatar' => [
        'continent' => 'Asia',
        'cities' => [
            'Al Wukair',
            'Al Khor',
            'Doha',
            'Dukhan',
            'Al Wakrah',
            'Ain Khaled',
            'Al Daayen',
            'Al Rayyan',
        ],
    ],
    'Kuwait' => [
        'continent' => 'Asia',
        'cities' => [
            'Kuwait cities',
            'Safat',
            'Hawally',
            'Hawalli',
            'Khaitan',
            'Salmiya',
            'Al Ahmadi',
            'Al Farwaniyah',
            'Jleeb Al-Shuyoukh',
            'Al Jahra',
            'Sabah Al Salem',
            'Mahboula',
            'Al-Salam',
            'Mangaf',
            'Salwa',
            'Al Asimah',
            'Muscat',
        ],
    ],
    'Austria' => [
        'continent' => 'Europe',
        'cities' => [
            'Vienna',
            'Graz',
            'Linz',
            'RemovedSalzburg',
            'Innsbruck',
            'Klagenfurt',
            'Leoben',
            'Krems an der Donau',
            'Wels',
            'Villach',
            'Dornbirn',
            'Eisenstadt',
            'Sankt Polten',
            'Wiener Neustadt',
            'Kufstein',
            'Salzburg',
            'Tyrol',
        ],
    ],
    'Belgium' => [
        'continent' => 'Europe',
        'cities' => [
            'Wezembeek-Oppem',
            'Tervuren',
            'Aalst',
            'Aarschot',
            'Andenne',
            'Antoing',
            'Antwerp',
            'Arlon',
            'Ath',
            'Bastogne',
            'Beaumont',
            'Beauraing',
            'Beringen',
            'Bilzen',
            'Binche',
            'Blankenberge',
            'Borgloon',
            'Bouillon',
            'Braine-le-Comte',
            'Bree',
            'Bruges ',
            'Brussels',
            'Charleroi',
            'Chatelet',
            'Chievres',
            'Chimay',
            'Chiny',
            'Ciney',
            'Comines-Warneton ',
            'Couvin',
            'Damme',
            'Deinze',
            'Dendermonde ',
            'Diest',
            'Diksmuide ',
            'Dilsen-Stokkem',
            'Dinant',
            'Durbuy',
            'Eeklo',
            'Enghien',
            'Eupen',
            'Fleurus',
            'Florenville',
            'Fontaine-l Eveque',
            'Fosses-la-Ville',
            'Geel',
            'Gembloux ',
            'Genappe',
            'Genk',
            'Geraardsbergen',
            'Ghent ',
            'Gistel',
            'Halen',
            'Halle ',
            'Hamont Achel',
            'Hannut ',
            'Harelbeke',
            'Hasselt',
            'Herentals',
            'Herk-de-Stad',
            'Herve',
            'Hoogstraten',
            'Houffalize',
            'Huy',
            'Izegem',
            'Jodoigne',
            'Kortrijk',
            'La Louviere',
            'La Roche-en-Ardenne',
            'Landen',
            'Le Roeulx',
            'Lessines',
            'Leuven',
            'Leuze en Hainaut',
            'Liege',
            'Lier',
            'Limbourg',
            'Lo Reninge',
            'Lokeren',
            'Lommel',
            'Maaseik',
            'Malmedy',
            'Marche en Famenne',
            'Mechelen',
            'Menen',
            'Mesen',
            'Mons',
            'Mortsel',
            'Mouscron',
            'Namur',
            'Neufchateau',
            'Nieuwpoort',
            'Ninove',
            'Nivelles',
            'Ostend',
            'Ottignies Louvain la Neuve',
            'Oudenaarde',
            'Oudenburg',
            'Peer',
            'Peruwelz',
            'Philippeville',
            'Poperinge',
            'Rochefort',
            'Roeselare',
            'Ronse',
            'Saint Ghislain',
            'Saint Hubert',
            'Scherpenheuvel Zichem',
            'Seraing',
            'Sint-Niklaas',
            'Sint-Truiden',
            'Soignies',
            'Spa',
            'St. Vith',
            'Stavelot',
            'Tervuren',
            'Thuin',
            'Tielt',
            'Tienen',
            'Tongeren',
            'Torhout',
            'Tournai ',
            'Turnhout',
            'Verviers',
            'Veurne',
            'Vilvoorde',
            'Virton',
            'Vise',
            'Walcourt',
            'Waregem',
            'Uccle',
            'Waremme',
            'Wavre',
            'Waterloo',
            'Wervik',
            'Ypres',
            'Zottegem',
            'Zoutleeuw',
            'Antwerpen',
            'Libramont',
            'London',
        ],
    ],
    'Saudi Arabia' => [
        'continent' => 'Asia',
        'cities' => [
            'Arabia Hafar Al Batin',
            'Arabia Al-Kharj',
            'Riyadh',
            'Jeddah',
            'Jouf',
            'Dhahran',
            'Makkah',
            'Najran',
            'Dammam',
            'Asir',
            'Jazan',
            'Madina',
            'Taif',
            'Qassim',
            'Hail',
            'Tabuk',
            'Al Jubail',
            'Yenbu',
            'Arar',
            'Al Majmaah',
            'Alhasa',
            'Al Khobar',
            'Jizan',
            'Medina',
            'Al Ahsa',
        ],
    ],
    'Oman' => [
        'continent' => 'Asia',
        'cities' => [
            'Muscat',
            'Sohar',
            'Salalah',
            'Seeb',
            'Ibra',
            'Ibri',
            'Nizwa',
            'Barka',
            'Sur',
            'Al Athaiba',
            'Al Muladha',
            'Al-Ghubra',
        ],
    ],
    'Bahrain' => [
        'continent' => 'Asia',
        'cities' => [
            'Tubli',
            'Zallaq',
            'Manama',
            'Riffa',
            'Isa Town',
            'Muharraq',
            'Budaiya',
            'Salmabad',
            'Al Eker',
            'Hamala',
            'Adliya',
            'Saar',
            'Zinj',
            'Barbar',
            'Sitra',
            'Hamad Town',
            'Al Markh',
            'Sanad',
            'Janabiya',
            'Awali',
            'Sanabis',
            'Diplomatic Area',
            'Seef',
            'Sakhair',
        ],
    ],
    'Egypt' => [
        'continent' => 'Asia',
        'cities' => [
            'Cairo',
            'Alexandria',
            'Assiut',
            'Banha',
            'Beni Suef',
            'Giza',
            'Mansoura',
            'Fayoum',
            'Kafr el-Sheikh',
            'Dakahlia',
            'Shibin El Kom',
            'Al Minya',
            '6th of October',
            'Sohag',
            'Qena',
            'Ismailia',
            'Gharbiya',
            'Zagazig',
            'Sadat',
            'Aswan',
            'Badr',
            'Port Fuad',
            'New Cairo cities',
            'El Sharkeya',
            'Obour',
            'Hurghada',
            'Sharm El Sheikh',
            'Sheikh Zayed cities',
            'El Shorouk',
            'New Cairo',
            'Kaliobeya',
            'Al Minufiyah',
        ],
    ],
    'Turkey' => [
        'continent' => 'Asia',
        'cities' => [
            'Golcuk',
            'Dereli',
            'Sehitkamil',
            'Serdivan',
            'Izmit',
            'Bartin',
            'Istanbul',
            'Ankara',
            'Eskisehir',
            'Izmir',
            'Kocaeli',
            'Adana',
            'Bursa',
            'Trabzon',
            'Malatya',
            'Elazig',
            'Isparta',
            'Mersin',
            'Kahramanmaras',
            'Van',
            'Denizli',
            'Nigde',
            'Sanliurfa',
            'Sakarya',
            'Konya',
            'Kayseri',
            'Canakkale',
            'Erzurum',
            'Antalya',
            'Edirne',
            'Manisa',
            'Afyon',
            'Balikesir',
            'Kirikkale',
            'Samsun',
            'Gaziantep',
            'Zonguldak',
            'Hatay',
            'Tokat',
            'Diyarbakir',
            'Aydin',
            'Bolu',
            'Mugla',
            'Kutahya',
            'Kars',
            'Erzincan',
            'Yalova',
            'Sivas',
            'Tekirdag',
            'Yozgat',
            'Aksaray',
            'Adıyaman',
            'Kyrenia',
            'Karabuk',
            'Kırklareli',
        ],
    ],
    'Lebanon' => ['continent' => 'Asia', 'cities' => [
        'Matn',
        'Beirut',
        'Tripoli',
        'Jounieh',
        'Baabda',
        'Mount Lebanon',
        'Kesserwan',
        'Aley',
        'Cornet Chahwan',
        'Ghazir',
        'Rabieh',
        'Sidon',
        'Choueifat',
        'Ajaltoun',
        'Zouk Mosbeh',
        'Nabatieh',
        'Zahle',
        'Amsheet',
        'Tyre',
        'Batroumine',
    ]],
    'Jordan' => ['continent' => 'Asia', 'cities' => [
        'Amman',
        'Irbid',
        'Zarqa',
        'Al-Karak',
        'Al-Mafraq',
        'Salt',
        "Ma'an",
        'Tafilah',
        'Jerash',
        'Ajloun',
        'Aqaba',
    ]],
    'Syria' => ['continent' => 'Asia', 'cities' => [
        'Damascus',
        'Latakia',
        'Homs',
        'Ar-Raqqah',
        'Daraa',
        'Halab',
    ]],
    'Seychelles' => ['continent' => 'Africa', 'cities' => [
        'Roche Caiman',
    ]],
    'Tunisia' => ['continent' => 'Africa', 'cities' => [
        'Gafsa',
        'Tunis',
        'Sousse',
        'Sfax',
        'Kairouan',
    ]],
    'Morocco' => ['continent' => 'Africa', 'cities' => [
        'Ifrane',
        'Rabat',
        'Agadir',
        'Tanger',
        'Casablanca',
        'Fes',
        'Marrakech',
        'Kenitra',
        'Meknes',
        'Ouarzazate',
    ]],
    'Algeria' => ['continent' => 'Africa', 'cities' => [
        'Algiers',
        'Kouba',
        'Oued Smar',
        'Dely Ibrahim',
        'Bab Ezzouar',
        'Koléa',
        'Annaba',
        'Batna',
        'Bechar',
        'Bejaia',
        'doucen',
        'Blida',
        'Constantine',
        'Djelfa',
        'Guelma',
        'Laghouat',
        'Medea',
        'Oran',
        'Ouargla',
        'Oum El Bouaghi',
        'Saida',
        'Sétif',
        'Sidi Bel Abbès',
        'Skikda',
        'Tébessa',
        'Tindouf',
    ]],
    'United Kingdom' => ['continent' => 'Europe', 'cities' => [
        'Richmond',
        'Oxford',
        'Durham',
        'Dulverton',
        'Newcastle upon Tyne',
        'Tyne and Wear',
        'Leicestershire',
        'Middlesex',
        'Buckinghamshire',
        'Accrington',
        'Cambridge',
        'Bournemouth',
        'Dorset',
        'York',
        'Birmingham',
        'Romford',
        'Hampshire',
        'Bath',
        'Bedford',
        'London',
        'Lincoln',
        'Blackburn',
        'Blackpool',
        'Poole',
        'Bolton',
        'Bradford',
        'Bridgwater',
        'Brighton',
        'Bristol',
        'Surrey',
        'Canterbury',
        'Coventry',
        'Sunderland',
        'Hartlepool',
        'Sheffield',
        'Colchester',
        'Norfolk',
        'St Austell',
        'Skipton',
        'Leicester',
        'Wath upon Dearne',
        'South Yorkshire',
        'Cornwall',
        'West Midlands',
        'Ormskirk',
        'Kent',
        'Exeter',
        'Gloucestershire',
        'Lincolnshire',
        'Shropshire',
        'Essex',
        'Hereford',
        'Manchester',
        'Hull',
        'Staffordshire',
        'West Yorkshire',
        'Cumbria',
        'Lancaster',
        'Leeds',
        'Liverpool',
        'Northampton',
        'Preston',
        'Nottingham',
        'Redditch',
        'Warwickshire',
        'West Sussex',
        'Ashington',
        'Norwich',
        'Plymouth',
        'Rotherham',
        'Taunton',
        'Paignton',
        'Waterlooville',
        'South Shields',
        'Southampton',
        'Southport',
        'Winchester',
        'St Helens',
        'Twickenham',
        'Coalville',
        'Stockport',
        'Stratford upon Avon',
        'Wiltshire',
        'Greater Manchester',
        'Middlesbrough',
        'Suffolk',
        'Peterborough',
        'Cheshire',
        'Derby',
        'Cheltenham',
        'Greenwich',
        'Hertfordshire',
        'Portsmouth',
        'Berkshire',
        'Wolverhampton',
        'Worcestershire',
        'Walsall',
        'Merseyside',
        'Chelmsford',
        'Cranfield',
        'Henley-on-Thames',
        'Beaconsfield',
        'Gloucester',
        'Bracknell',
        'Oldham',
        'Loughborough',
        'Devon',
        'East Sussex',
        'Somerset',
        'Wakefield',
        'Lancashire',
        'Bedfordshire',
        'North Yorkshire',
        'Herefordshire',
        'East Yorkshire',
        'Northamptonshire',
        'Nottinghamshire',
        'Northumberland',
        'Derbyshire',
        'Oxfordshire',
        'Birling Gap',
    ]],
    'United States' => ['continent' => 'North America', 'cities' => [
        'Arcadia',
        'Canyonville',
        'Camden',
        'Carbondale',
        'Denton',
        'Herlingen',
        'Elkhorn',
        'New York',
        'Maryland',
        'California',
        'Wisconsin',
        'Cleveland',
        'Virginia',
        'Texas',
        'Colorado',
        'Arizona',
        'Massachusetts',
        'Florida',
        'Pennsylvania',
        'Illinois',
        'South Carolina',
        'Spokane',
        'Alabama',
        'Alaska',
        'Arkansas',
        'Connecticut',
        'Delaware',
        'District of Columbia',
        'Georgia',
        'Hawaii',
        'Idaho',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'North Carolina',
        'North Dakota',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Providence',
        'Rhode Island',
        'South Dakota',
        'Tennessee',
        'Utah',
        'Vermont',
        'Washington',
        'West Virginia',
        'Wyoming',
        'Minneapolis',
        'Flint',
        'Montgomery',
        'Santa Clarita',
        'San Diego',
        'Los Angeles',
        'Pasadena',
        'Clovis',
        'Mishawaka',
        'Vincennes',
        'Annapolis',
        'Laurel',
        'Takoma Park',
        'Hancock',
        'Kansas cities',
        'Carson',
        'Springfield',
        'Newark',
        'Lincoln cities',
        'Utica',
        'Beaufort',
        'Aiken',
        'Scranton',
        'Ellendale',
        'Concord',
        'Valley cities',
        'Wilmington',
        'Lima',
        'Cincinnati',
        'Bellevue',
        'Pasco',
        'Centralia',
        'Milwaukee',
        'Watertown',
        'Glendale',
        'Weslaco',
        'Midland',
        'Tyler',
        'Dallas',
        'Lake Jackson',
        'Southlake',
        'Winston-Salem',
        'Grand Forks',
        'Guam',
        'Jamestown',
        'Albany',
        'Lansing',
        'New York cities',
        'Seattle',
        'Oakland',
        'La Canada Flintridge',
        'Boston',
        'San Jose',
        'Palo Alto',
        'Ojai',
        'Belmont',
        'Carpinteria',
        'Bloomfield Hills',
        'New Haven',
        'Chicago',
        'Fort Lauderdale',
        'Windsor',
        'Philadelphia',
        'Houston',
        'Miami',
        'San Mateo',
        'St. Louis',
        'Rye',
        'Albuquerque',
        'Plantation',
        'Redmond',
        'Lake Forest',
        'Atlanta',
        'Cambridge',
        'San Francisco',
        'Englewood',
        'San Antonio',
        'Palos Verdes Peninsula',
        'Portland',
        'Pittsburgh',
        'Santa Monica',
        'Austin',
        'Claremont',
        'Irving',
        'Hopkins',
        'Delray Beach',
        'San Rafael',
        'Saint Paul',
        'Summit',
        'Hudson',
        'Baltimore',
        'Sandy',
        'Las Vegas',
        'Honolulu',
        'Dublin',
        'Lyndhurst',
        'Troy',
        'Montezuma',
        'Coral Gables',
        'Shaker Heights',
        'Tampa',
        'Gahanna',
        'Carlsbad',
        'Durham',
        'Louisville',
        'Calabasas',
        'Alexandria cities',
        'Toledo',
        'College Park',
        'Ridgeland',
        'Boise',
        'Nashville',
        'Los Altos',
        'Irvine',
        'Monterey',
        'Winter Park',
        'Phoenix',
        'San Juan Capistrano',
        'Memphis',
        'Columbus',
        'Asheville',
        'El Segundo',
        'New Orleans',
        'Sacramento',
        'Denver',
        'Anaheim',
        'Golden Valley',
        'Mountain View',
        'Norfolk',
        'Birmingham cities',
        'State Indiana',
        'Ann Arbor',
        'Kirkland',
        'Fort Wayne',
        'Chattanooga',
        'Eden Prairie',
        'Fort Worth',
        'Hartford',
        'Fort Myers',
        'cities Indianapolis',
        'cities Charlotte',
        'Newport',
        'Lafayette',
        'St. Petersburg',
        'Santa Cruz',
        'Racine',
        'Colorado Springs',
        'Oklahoma cities',
        'Savannah',
        'Boca Raton',
        'Raleigh',
        'Baton Rouge',
        'Newton',
        'Richmond',
        'Dayton',
        'Danville',
        'Lititz',
        'Westlake Village',
        'North Miami Beach',
        'Syracuse',
        'Kingston',
        'Tacoma',
        'Stamford',
        'Bethlehem',
        'Athens',
        'Evanston',
        'Orlando',
        'Naperville',
        'Reno',
        'Greensboro',
        'Newburyport',
        'Worcester',
        'Knoxville',
        'Waco',
        'New Bedford',
        'Sedona',
        'Waltham',
        'Hagerstown',
        'Pittsfield',
        'Palm Beach Gardens',
        'Jacksonville',
        'Fairfield',
        'Bell Buckle',
        'Saint Joseph',
        'Salt Lake cities',
        'Mendota Heights',
        'Buffalo',
        'Peachtree Corners',
        'cities Naples',
        'Beverly',
        'Sunnyvale',
        'Marietta',
        'Easthampton',
        'Manchester',
        'Elgin',
        'Traverse cities',
        'Coconut Creek',
        'Huntsville',
        'Jenkintown',
        'North Ridgeville',
        'Rockville',
        'Charlottesville',
        'cities Jackson',
        'Oradell',
        'Santa Fe',
        'Mobile',
        'Tulsa',
        'Rancho Santa Margarita',
        'Madison',
        'Bellaire',
        'New London',
        'Demarest',
        'Rochester',
        'Carmel',
        'Tucson',
        'Franklin',
        'Columbia',
        'Goldsboro',
        'Greenville',
        'Little Rock',
        'Norcross',
        'Lawrence',
        'Charleston',
        'Gastonia',
        'West Palm Beach',
        'Macon',
        'Santa Rosa',
        'Sun Valley',
        'Faribault',
        'Lynchburg',
        'San Marino',
        'Bettendorf',
        'Grosse Pointe Woods',
        'Hoboken',
        'Plymouth',
        'Plano',
        'Aurora',
        'Arlington',
        'Lancaster',
        'Ukiah',
        'Palmetto',
        'chicopee',
        'Des Plaines',
        'Pontiac',
        'Medford',
        'Chester',
        'Augusta',
        'White Plains',
        'Omaha',
        'New Rochelle',
        'Paramus',
        'Eagan',
        'Wichita',
        'Garland',
        'Sammamish',
        'Sarasota',
        'Wheaton',
        'Hardeeville',
        'Meriden',
        'Bridgeport',
        'Novi',
        'Lewisville',
        'Richfield',
        'Beaver Dam',
        'North Chicago',
        'Vero Beach',
        'Beaverton',
        'Lexington',
        'Tallahassee',
        'cities Melbourne',
        'Detroit',
        'Allentown',
        'Poughkeepsie',
        'Paris',
        'St Louis Park',
        'Webster Groves',
        'Smyrna',
        'New Brunswick',
        'Joplin',
        'Barnstable',
        'Falls Church',
        'Waterbury',
        'Santa Barbara',
        'Harrisburg',
        'Encinitas',
        'Cumming',
        'La Porte cities',
        'Dothan',
        'Rockford',
        'East Providence',
        'West Chicago',
        'Spokane',
        'Sheridan',
        'Gainesville',
        'Doral',
        'Williamsburg',
        'Waukesha',
        'Akron',
        'Duluth',
        'Flowood',
        'Wheeling',
        'Covington',
        'Bloomington',
        'Jersey cities',
        'Berkeley',
        'Corpus Christi',
        'St. Augustine',
        'Dearborn',
        'Frankfort',
        'Lawrenceville',
        'Algona',
        'Northern Mariana Islands',
        'Edgerton',
        'Middletown',
        'Andover',
        'Cullman',
        'Watsonville',
        'Spangle',
        'Saint Louis',
        'Waynesboro',
        'Peru',
        'Atchison',
        'Bradenton',
        'Greenfield',
        'West St. Paul',
        'Mount Pleasant',
        'San Marcos',
        'Winona',
        'Bay St. Louis',
        'Willoughby',
        'Gentry',
        'Fergus Falls',
        'Salem',
        'Hauula',
        'Bangor',
        'Roswell',
        'Parowan',
        'Freeman',
        'Spray',
        'Delafield',
        'Scottsdale',
        'Staunton',
        'Napa',
        'Olympic Valley',
        'Lake Mary',
        'Calhoun',
        'Orchard Lake Village',
        'Marlborough',
        'Central cities',
        'Erie',
        'Miller',
        'Ladysmith',
        'Viroqua',
        'Saco',
        'Braintree',
        'Bryan',
        'Roanoke',
        'Burlington',
        'Campbell',
        'Chula Vista',
        'Vallejo',
        'San Antonio',
        'Michigan cities',
        'Martinsville',
        'Fresno',
        'Clarkston',
        'Torrance',
        'Chicago Heights',
        'West Covina',
        'Wildomar',
        'Lanett',
        'Owosso',
        'Granbury',
        'Bismarck',
        'Cottonwood',
        'Harrah',
        'Lumberton',
        'Fitchburg',
        'Owatonna',
        'Healdsburg',
        'Colfax',
        'Huntington Beach',
        'Winchester',
        'Fridley',
        'Caldwell',
        'Marion',
    ]],
    'Switzerland' => ['continent' => 'Europe', 'cities' => [
        'Valais',
        'Baar',
        'Dubendorf',
        'Zug',
        'Vevey',
        'Saas Fee',
        'Le Bouveret',
        'Neuchatel',
        'Bellinzona',
        'Zurich',
        'Lausanne',
        'Geneva',
        'Basel',
        'Bern',
        'St. Gallen',
        'Fribourg',
        'Brugg',
        'Lugano',
        'Delemont',
        'Luzern',
        'Bulle',
        'Winterthur',
        'Gland',
        'Montreux',
        'Leysin',
        'Saint-Legier-La Chiesaz',
        'La Tour-de-Peilz',
    ]],
    'Australia' => ['continent' => 'continent of Australia', 'cities' => [
        'Albury',
        'Alice Springs',
        'Bathurst',
        'Ashgrove',
        'Berrimah',
        'Canberra',
        'Brisbane',
        'Sydney',
        'Melbourne',
        'Parramatta',
        'North Parramatta',
        'Perth',
        'Adelaide',
        'Wollongong',
        'Queensland',
        'Gold Coast',
        'Wodonga',
        'Shoalhaven',
        'Kensington',
        'Wagga Wagga',
        'Burwood',
        'Coffs Harbour',
        'Macquarie Park',
        'Glen Waverley',
        'Geraldton',
        'Geelong',
        'Carlton',
        'Scoresby',
        'Hobart',
        'Cairns',
        'Mackay',
        'Port Lincoln',
        'Shepparton',
        'Mount Isa',
        'Prahran',
        'Broome',
        'Darwin',
        'Oakleigh',
        'Armidale',
        'Logan cities',
        'Hawkesbury',
        'Ultimo',
        'Newcastle',
        'Ballarat',
        'Central Coast',
        'Toowoomba',
        'Rydalmere',
        'Bunbury',
        'Surry Hills',
        'Crawley',
        'Victoria',
        'Redland cities',
        'cities of Ipswich',
        'Benalla',
        'Dianella',
        'Bairnsdale',
        'Berwick',
        'Bennett Springs',
        'Belmont North',
        'Raceview',
        'Albany',
        'Mount Helena',
        'Fletcher',
        'Blakeview',
        'Bibra Lake',
        'Goonellabah',
        'Clearview',
        'Thurgoona',
        'Brighton',
        'Menangle Park',
        'Bundaberg Central',
        'Dubbo',
        'Morphettville',
        'Canterbury',
        'Holder',
        'Harrisdale',
        'Tamworth',
        'Bickley',
        'Carmel',
        'Wangaratta',
        'Tasmania',
        'Fassifern',
        'Kemps Creek',
        'Glendalough',
        'Carindale',
        'Grafton',
        'Toormina',
        'Upper Coomera',
        'Busselton',
        'Bangholme',
        'Deniliquin',
        'Forrestfield',
        'Australia',
        'Bruce',
        'New South Wales',
        'Western Australia',
        'Northern Territory',
        'Orange',
        'Yeppoon',
        'Jimboomba',
        'Jindabyne',
        'Nathan',
        'Robina',
        'Banyo',
        'Rockhampton',
        'Bendigo',
        'Darlinghurst',
        'Launceston',
        'Whyalla',
        'Kelvin Grove',
        'South Australia',
        'Burnie',
        'Coolangatta',
        'Mawson Lakes',
        'Williamstown',
        'Mount Barker',
        'Walkerville',
        'Marrara',
        'Lakelands',
    ]],
    'Hong Kong' => ['continent' => 'Asia', 'cities' => [
        'Tsuen Wan',
        'Pokfulam',
        'Kowloon',
        'Sha Tin New Town',
        'Tuen Mun',
        'Tai po',
        'Wanchai',
        'Braemar Hill',
        'Tseung Kwan O New Town',
        'Quarry Bay',
        'Tsim Sha Tsui',
        'Aberdeen',
        'Kowloon Bay',
        'Kowloon Tong',
        'Kowloon cities',
        'cities Hong Kong',
        'Hong Kong Island',
        'Discovery Bay',
        'Lantau Island',
        'Wan Chai',
        'The Peak',
        'Causeway Bay',
        'Tin Hau',
        'Sheung Wan',
        'Yau Ma Tei',
        'Ma On Shan',
        'Happy Valley',
        'Mid Levels',
        'New Territories',
        'Yau Yat Chuen',
        'Shau Kei Wan',
        'Sha Tin',
        'Wong Chuk Hang',
        'Tseung Kwan O',
        'Kwai Chung',
        'Shatin',
        'Tsing Yi',
        'Kennedy Town',
        'Mid-Levels',
        'Sai Kung',
        'Tai Tam',
        'Stanley',
        'Clear Water Bay',
        'Yuen Long',
        'Chai Wan',
        'Fanling',
        'Central',
        'Hong Kong cities', ]],
    'Japan' => ['continent' => 'Asia', 'cities' => [
        'Tokyo',
        'Kyoto',
        'Osaka',
        'Nagoya',
        'Sendai',
        'Fukuoka',
        'Sapporo',
        'Kobe',
        'Hiroshima',
        'Chiba',
        'Yokohama',
        'Okayama',
        'Nagasaki',
        'Gifu',
        'Kanazawa',
        'Saitama',
        'Kagoshima',
        'Tsu',
        'Maebashi',
        'Tsukuba',
        'Yamaguchi',
        'Kumamoto',
        'Niigata',
        'Matsumoto',
        'Hiratsuka',
        'Katsuyama',
        'Fukushima',
        'Kyotanabe',
        'Nishinomiya',
        'Hirosaki',
        'Tamamura',
        'Matsue',
        'Nonoichi',
        'Yamagata',
        'Higashiosaka',
        'Nara',
        'Otaru',
        'Hirakata',
        'Atsugi',
        'Matsuyama',
        'Tottori',
        'Takizawa',
        'Morioka',
        'Toyoake',
        'Beppu',
        'Miyazaki',
        'Minamiuonuma',
        'Shizuoka',
        'Fukui',
        'Nisshin',
        'Togane',
        'Kochi',
        'Akita',
        'Tokushima',
        'Nomi',
        'Koshigaya',
        'Yurihonjo',
        'Sakado',
        'Saga',
        'Asahikawa',
        'Hakodate',
        'Takamatsu',
        'Toyohashi',
        'Kasugai',
        'Chita',
        'Nagakute',
        'Toyota',
        'Kitanagoya',
        'Inazawa',
        'Tokai',
        'Obu',
        'Hachinohe',
        'Kurume',
        'Munakata',
        'Dazaifu',
        'Ogaki',
        'Onomichi',
        'Fukuyama',
        'Hatsukaichi',
        'Kato',
        'Miki',
        'Kakogawa',
        'Kahoku',
        'Hakusan',
        'Miura',
        'Sagamihara',
        'Kawasaki',
        'Tamana',
        'Ise',
        'Suzuka',
        'Sasebo',
        'Isahaya',
        'Joetsu',
        'Nagaoka',
        'Kashiwazaki',
        'Shibata',
        'Soja',
        'Kurashiki',
        'Takahashi',
        'Ibaraki',
        'Neyagawa',
        'Tondabayashi',
        'Sakai',
        'Kawagoe',
        'Niiza',
        'Ageo',
        'Gyoda',
        'Utsunomiya',
        'Ohtawara',
        'Ashikaga',
        'Tama',
        'Toyama',
        'Imizu',
        'Kofu',
        'Tsuru',
        'Kashiwa',
        'Nagareyama',
        'Urayasu',
        'Matsudo',
        'Ichikawa',
        'Inzai',
        'Katsuura',
        'Echizen',
        'Aizuwakamatsu',
        'Iwaki',
        'Takasaki',
        'Muroran',
        'Obihiro',
        'Kitami',
        'Ebetsu',
        'Kitahiroshima',
        'Chitose',
        'Kushiro',
        'Tomakomai',
        'Nayoro',
        'Mito',
        'Inashiki',
        'Ryugasaki',
        'Hitachi',
        'Kanoya',
        'Satsumasendai',
        'Kami',
        'Natori',
        'Chino',
        'Shiojiri',
        'Oita',
        'Okinawa',
        'Ginowan',
        'Nago',
        'Naha',
        'Kanzaki',
        'Hikone',
        'Otsu',
        'Hamamatsu',
        'Naruto',
        'Wakayama',
        'Shimonoseki',
        'Tagawa',
        'Iwata',
        'Ichinomiya',
        'Suita',
        'Kamogawa',
        'Midori',
        'Shimotsuke',
        'Kakegawa',
        'Kanagawa',
        'Yamato',
        'Nagano',
        'Aomori',
        'Tokorozawa',
        'Mie',
        'Gunma',
        'Ishikawa',
        'Hokkaido',
        'Miyagi',
        'Aichi',
        'Hyogo',
        'Shimane',
        'Ehime',
        'Iwate',
        'Kyushu',
        'Kagawa',
        'Yamanashi',
        'Kamikawa',
        'Tochigi',
        'Shiga', ]],
    'Jamaica' => ['continent' => 'North America', 'cities' => [
        'Kingston',
        'Portmore',
        'Montego Bay',
        'Spanish Town',
        'May Pen',
        'Mandeville',
        'Old Harbour',
        'Savanna-la-Mar',
        'Ocho Rios',
        'Port Antonio',
        'Linstead',
        'Saint Anns Bay',
        'Morant Bay',
        'Hayes',
        'Above Rocks',
        'Albert Town',
        'Alexandria',
        'Alligator Pond',
        'Anchovy',
        'Annotto Bay',
        'Balaclava',
        'Bamboo',
        'Bath',
        'Bethel Town',
        'Black River',
        'Bluefields',
        'Bog Walk',
        'Brompton',
        'Browns Town',
        'Buff Bay',
        'Bull Savanna',
        'Cambridge',
        'Cascade',
        'Cave Valley',
        'Chapelton',
        'Christiana',
        'Claremont',
        'Clarks Town',
        'Coleyville',
        'Constant Spring',
        'Crofts Hill',
        'Dalvey',
        'Darliston',
        'Discovery Bay',
        'Duncans',
        'Easington',
        'Ewarton',
        'Falmouth',
        'Frankfield',
        'Frome',
        'Gayle',
        'Golden Grove',
        'Gordon Town',
        'Grange Hill',
        'Green Island',
        'Guys Hill',
        'Highgate',
        'Hope Bay',
        'Hopewell',
        'Islington',
        'Kellits',
        'Lacovia',
        'Lionel Town',
        'Little London',
        'Lluidas Vale',
        'Lucea',
        'Lucky Hill',
        'Maggotty',
        'Malvern',
        'Manchioneal',
        'Maroon Town',
        'Mavis Bank',
        'Moneague',
        'Moore Town',
        'Morant Bay',
        'Nain',
        'Negril',
        'Ocho Rios',
        'Old Harbour Bay',
        'Oracabessa',
        'Osbourne Store',
        'Petersfield',
        'Point Hill',
        'Port Maria',
        'Port Royal',
        'Porus',
        'Race Course',
        'Richmond',
        'Rio Bueno',
        'Riversdale',
        'Rocky Point',
        'Runaway Bay',
        'Sandy Bay',
        'Sanguinetti',
        'Santa Cruz',
        'Seaford Town',
        'Seaforth',
        'Siloah',
        'Southfield',
        'Spalding',
        'Stony Hill',
        'Trinity Ville',
        'Ulster Spring',
        'Wakefield',
        'White House',
        'Williamsfield',
        'Yallahs',
    ]],
    'France' => ['continent' => 'Europe', 'cities' => [
        'Aix-En-Provence',
        'Antibes',
        'Loches',
        'Cannes',
        'Luynes',
        'Paris',
        'lyon',
        'Strasbourg',
        'Grenoble',
        'Montpellier',
        'Lille',
        'Toulouse',
        'Rennes',
        'Caen',
        'Nice',
        'Ecully',
        'Saint Denis',
        'Poitiers',
        'Compiegne',
        'Gif sur Yvette',
        'Nantes',
        'Creteil',
        "Saint Martin d'Heres",
        'Nanterre',
        'Villetaneuse',
        'Dijon',
        'Angers',
        'Mont Saint Aignan',
        'Bordeaux',
        'Versailles',
        'Amiens',
        'Brest',
        'Marseille',
        'Villeurbanne',
        'Le Mans',
        'Jouy en Josas',
        'Chambery',
        'Cachan',
        'Orleans',
        'Clermont Ferrand',
        'Cergy Pontoise',
        'La Garde',
        'Perpignan',
        'Noisy le Grand',
        'Saint Etienne',
        'Nancy',
        'Arras',
        'Pessac',
        'Ajaccio',
        'Belfort',
        'La Rochelle',
        'Troyes',
        'Evry Essonne',
        'Le Havre',
        'Le Kremlin Bicetre',
        'Albi',
        'Roubaix',
        'Villejuif',
        'Beauvais',
        'Palaiseau',
        'Chasseneuil du Poitou',
        'Malakoff',
        'Sceaux',
        'Douai',
        'Champs sur Marne',
        'Montigny le Bretonneux',
        "Villeneuve d'Ascq",
        'Aubiere',
        'Ivry sur Seine',
        'Saint Ouen',
        'Saint Etienne du Rouvray',
        'Bruz',
        'Rouen',
        'Rueil Malmaison',
        'Bidart',
        'Tarbes',
        'Pau',
        'Gradignan',
        'Castanet Tolosan',
        'Limoges',
        "Saint Barthélemy d'Anjou",
        'Blois',
        'Arcueil',
        'Metz',
        'Collonges sous Saleve',
        'Nimes',
        'Reims',
        'Normandy',
        'Occitanie',
        'Brittany',
        'Nouvelle-Aquitaine',
        'Pauillac',
        'Mougins',
        'Saint-Germain-en-Laye',
        'Fuveau', ]],
    'Denmark' => ['continent' => 'Europe', 'cities' => [
        'Vejle',
        'Ikast-Brande',
        'Copenhagen',
        'Aarhus',
        'Odense',
        'Aalborg',
        'Frederiksberg',
        'Roskilde',
        'Kolding',
        'Randers',
        'Hellerup',
        'Naestved',
        'Ikast',
        'Billund',
        'Sonderborg', ]],
    'China' => ['continent' => 'Asia', 'cities' => [
        'Beijing',
        'Shanghai',
        'Hefei',
        'Nanjing',
        'Hangzhou',
        'Xian',
        'Tianjin',
        'Shandong',
        'Suzhou',
        'Kunshan',
        'Shantou',
        'Zhenjiang',
        'Zhengzhou',
        'Wuhan',
        'Guangzhou',
        'Harbin',
        'Xiamen',
        'Changchun',
        'Chengdu',
        'Lanzhou',
        'Changsha',
        'Macau',
        'Dongguan',
        'Xi An',
        'Qingdao',
        'Ningbo',
    ]],
    'Ireland' => ['continent' => 'Europe', 'cities' => [
        'Ballina',
        'Dublin',
        'Cork',
        'Galway',
        'Maynooth',
        'Limerick',
        'Shannon',
        'carlow',
        'Bishopstown',
        'Waterford',
        'Letterkenny',
        'Dundalk',
        'Sligo',
        'Athlone',
        'Tralee',
        'Killorglin',
        'Donegal',
        'Belfast',
        'Clane', ]],
    'Netherlands' => ['continent' => 'Europe', 'cities' => [
        'Amsterdam',
        'Leiden',
        'Utrecht',
        'Rotterdam',
        'Delft',
        'Maastricht',
        'Groningen',
        'Eindhoven',
        'Wageningen',
        'Enschede',
        'Tilburg',
        'Nijmegen',
        'Zwolle',
        'Deventer',
        'Breukelen',
        'Breda',
        'Leeuwarden',
        'Arnhem',
        'Hague',
        'Den Haag',
        'Dronten',
        'Hertogenbosch',
        'Gouda',
        'Voorschoten',
        'Velp',
        'Apeldoorn',
        'Vlissingen',
        'Emmen',
        'Venlo',
        'Haarlem',
        'Heerlen',
        'Ede',
        'Doetinchem',
        'The Hague', ]],
    'Sweden' => ['continent' => 'Europe', 'cities' => [
        'Upplands Vasby',
        'Uppsala',
        'Lund',
        'Stockholm',
        'Gothenburg',
        'Umeå',
        'Linkoping',
        'Malmo',
        'Trollhattan',
        'Boras',
        'jonkoping',
        'Lulea',
        'Karlskrona',
        'Gavle',
        'Vasteras',
        'Sundsvall',
        'Skovde',
        'Karlstad',
        'Vaxjo',
        'Orebro',
        'Huddinge',
        'Halmstad',
        'Falun',
        'kristianstad', ]],
    'Germany' => ['continent' => 'Europe', 'cities' => [
        'Kassel',
        'Bockenheim',
        'Hachenburg',
        'Biberach',
        'Munich',
        'Berlin',
        'Freiburg',
        'Bayreuth',
        'Marburg',
        'Aachen',
        'Baden Wurttemberg',
        'Hamburg',
        'Bonn',
        'Cologne',
        'Leipzig',
        'Munster',
        'Hannover',
        'Bremen',
        'Stuttgart',
        'Mainz',
        'Frankfurt',
        'Gottingen',
        'Dresden',
        'Karlsruhe',
        'Wurzburg',
        'Regensburg',
        'Jena',
        'Kiel',
        'Kaiserslautern',
        'Saarbrucken',
        'Bielefeld',
        'Konstanz',
        'Darmstadt',
        'Essen',
        'Dusseldorf',
        'Giessen',
        'Ulm',
        'Mannheim',
        'Trier',
        'Potsdam',
        'Halle',
        'Oldenburg',
        'Braunschweig',
        'Rostock',
        'Hagen',
        'Lubeck',
        'Siegen',
        'Augsburg',
        'Osnabruck',
        'Wuppertal',
        'Dortmund',
        'Greifswald',
        'Passau',
        'Ilmenau',
        'Clausthal Zellerfeld',
        'Bamberg',
        'Weimar',
        'Luneburg',
        'Erlangen',
        'Eichstatt',
        'Wismar',
        'Furtwangen',
        'Neubiberg',
        'Ludwigsburg',
        'Mittweida',
        'Vallendar',
        'Magdeburg',
        'Hildesheim',
        'Wiesbaden',
        'Stralsund',
        'Erfurt',
        'Merseburg',
        'Esslingen am Neckar',
        'Heilbronn',
        'Koblenz',
        'Witten',
        'Nordhausen',
        'Krefeld',
        'Aalen',
        'Cottbus',
        'Vechta',
        'Flensburg',
        'Wolfenbuttel',
        'Wedel',
        'Heidelberg',
        'Zwickau',
        'Reutlingen',
        'Schwabisch Gmund',
        'Schweinfurt',
        'Freising',
        'Bremerhaven',
        'Kleve',
        'Lemgo',
        'Fulda',
        'Nurtingen',
        'Wernigerode',
        'Emden',
        'Schmalkalden',
        'Ingolstadt',
        'Coburg',
        'Rosenheim',
        'Heide',
        'Idstein',
        'Eberswalde',
        'Offenbach',
        'Paderborn',
        'Nuremberg',
        'Zittau',
        'Kempten',
        'Bruhl',
        'Offenburg',
        'Gelsenkirchen',
        'Hamm',
        'Sankt Augustin',
        'Ludwigshafen',
        'Iserlohn',
        'Mulheim',
        'Friedrichshafen',
        'Aschaffenburg',
        'Landshut',
        'Hof',
        'Rottenburg',
        'Neuendettelsau',
        'Buxtehude',
        'Bochum',
        'Ansbach',
        'Deggendorf',
        'Ottersberg',
        'Kehl',
        'Pforzheim',
        'Schwabisch Hall',
        'Bad Honnef',
        'Neubrandenburg',
        'Elmshorn',
        'Brandenburg',
        'Neu-Ulm',
        'Trossingen',
        'Oestrich Winkel',
        'Detmold',
        'Amberg',
        'Furth',
        'Wildau',
        'Neuruppin',
        'Geisenheim',
        'Hamelin',
        'Speyer',
        'Kothen',
        'Herrenberg',
        '‎Bavaria',
        'Hesse',
        'North Rhine-Westphalia',
        'Thuringia',
        'Schleswig-Holstein',
        'Rhineland',
        'Oberursel',
        'Munchen',
        'Steinbach',
        'Friedrichsdorf',
        'Rheinberg', ]],
    'New Zealand' => ['continent' => 'Oceania continent', 'cities' => [
        'Auckland',
        'Bay of Islands',
        'Dunedin',
        'Christchurch',
        'Hamilton',
        'Palmerston North',
        'Tasman',
        'Tauranga',
        'Wanaka',
        'Wellington',
        'Whangarei',
        "Hawke's Bay",
        'Albany',
    ]],
    'Finland' => ['continent' => 'Europe', 'cities' => [
        'Helsinki',
        'Turku',
        'Espoo',
        'Kuopio',
        'Oulu',
        'Tampere',
        'Jyvaskyla',
        'Lappeenranta',
        'Rovaniemi',
        'Vaasa',
        'Seinajoki',
        'mikkeli',
        'Kokkola',
        'Hameenlinna',
        'Kajaani',
        'Vantaa',
        'Mariehamn',
        'Pori',
        'Joensuu',
        'Lahti', ]],
    'South Korea' => ['continent' => 'Asia', 'cities' => [
        'Gumi',
        'Daejeon',
        'Pohang',
        'Seoul',
        'Busan',
        'Incheon',
        'Daegu',
        'Jeonju',
        'Gwangju',
        'Chuncheon',
        'Gyeongsan',
        'Yongin',
        'Suwon',
        'Muan',
        'Sejong',
        'Jeju',
        'Cheongju',
        'Cheonan',
        'Goyang',
        'Gongju',
        'Jinju',
        'Asan',
        'Suncheon',
        'Andong',
        'Chungju',
        'Changwon',
        'Pocheon',
        'Gimhae',
        'Hwaseong',
        'Gunpo',
        'Seosan',
        'Seongnam',
        'Yangsan',
        'Jecheon',
        'Iksan',
        'Gangneung',
        'Wonju',
        'Seogwipo',
        'Sacheon',
        'Mungyeong',
        'Eumseong',
        'Ulsan',
        'Pyeongtaek',
        'Uijeongbu',
        'Sokcho',
        'Hoengseong',
        'Songdo',
        'Gunsan',
        'Geoje', ]],
    'Russia' => ['continent' => 'Europe', 'cities' => [
        'Chita',
        'Syktyvkar',
        'Moscow',
        'Saint Petersburg',
        'Novosibirsk',
        'Tomsk',
        'Kazan',
        'Krasnoyarsk',
        'Voronezh',
        'Rostov on Don',
        'Nizhny Novgorod',
        'Vladivostok',
        'Yekaterinburg',
        'Tyumen',
        'Barnaul',
        'Perm',
        'Chelyabinsk',
        'Saransk',
        'Saratov',
        'Ulyanovsk',
        'Irkutsk',
        'Samara',
        'Tambov',
        'Yaroslavl',
        'Orenburg',
        'Kaliningrad',
        'Omsk',
        'Volgograd',
        'Stavropol',
        'Krasnodar',
        'Astrakhan',
        'Murmansk',
        'Vladimir',
        'Ivanovo',
        'Blagoveshchensk',
        'Cherepovets',
        'Ulan Ude',
        'Elista',
        'Magnitogorsk',
        'Khabarovsk',
        'Surgut',
        'Kaluga',
        'Komsomolsk on Amur',
        'Ryazan',
        'Novocherkassk',
        'Yuzhno sakhalinsk',
        'Bratsk',
        'Lipetsk',
        'Michurinsk',
        'Ukhta',
        'Izhevsk',
        'Tula',
        'Nizhnevartovsk',
        'Kirov',
        'Petrozavodsk',
        'Makhachkala',
        'oryol',
        'Arkhangelsk',
        'Blagoveschensk',
        'Khanty Mansiysk',
        'Ufa',
        'Veliky novgorod',
        'Cheboksary',
        'Pyatigorsk',
        'Belgorod',
        'Maykop',
        'Yakutsk',
        'Kursk',
        'Innopolis',
        'Yoshkar Ola',
        'Sochi',
        'Shuya',
        'Penza',
        'Irkutsk Oblast', ]],
    'Tanzania' => ['continent' => 'Africa', 'cities' => [
        'Moshi urban',
    ]],
    'Taiwan' => ['continent' => 'Asia', 'cities' => [
        'Taipei',
        'Hsinchu',
        'Tainan cities',
        'Zhongli District',
        'Kaohsiung',
        'New Taipei cities',
        'Taichung',
        'Taoyuan',
        'Hualien',
        'Changhua',
        'Chiayi',
        'Douliu',
        'Nantou',
        'Keelung',
        'Yilan',
        'Yuanlin',
        'Miaoli',
        'Pingtung',
        'Taitung cities',
        'Magong',
        'Kinmen',
        'Tainan', ]],
    'Norway' => ['continent' => 'Europe', 'cities' => [
        'Asker',
        'Akershus',
        'Fredrikstad',
        'Gjovik',
        'Molde',
        'Kautokeino',
        'Notodden',
        'Oslo',
        'Bergen',
        'Trondheim',
        'Tromsø',
        'Kristiansand',
        'Halden',
        'Stavanger',
        'Longyearbyen',
        'As',
        'Volda',
        'Elverum',
        'Stjordal',
        'Steinkjer',
        'Bodo', ]],
    'Canada' => ['continent' => 'North America', 'cities' => [
        'Stephenville',
        'Port Coquitlam',
        'Richmond',
        'Airdrie',
        'Nanaimo',
        'Victoria',
        'Winnipeg',
        'Rothesay',
        'Halifax',
        'Windsor',
        'Oakville',
        'Mississauga',
        'St. Catharines',
        'Aurora',
        'Whitby',
        'Sherbrooke',
        'Stanstead',
        'Edmonton',
        'Okotoks',
        'Williams Lake',
        'Burnaby',
        'Surrey',
        'Kelowna',
        'New Westminster',
        'Charlottetown',
        'New York',
        'Montreal',
        'Ontario',
        'Alberta',
        'Nova Scotia',
        'British Columbia',
        'Ottawa',
        'Quebec',
        'Vancouver',
        'Manitoba',
        'New Brunswick',
        'Moncton',
        'cities Hamilton',
        'Toronto',
        'Saskatchewan',
        'Regina',
        "St. John's",
        'Sault Ste Marie',
        'Baltimore',
        'Buffalo',
        'cities London',
        'Hamilton',
        'Calgary',
        'Chilliwack',
        'Coquitlam',
        'Vernon',
        'Abbotsford',
        'Prince George',
        'Vaughan',
        'Craik',
        'Bedford',
        'Markham',
        'Oshawa',
        'Summerland',
        'Belleville',
        'Fort Erie',
        'Amherstburg',
        'Newmarket',
        'Richmond Hill',
        'Nepean',
        'London',
        'Kitchener',
        'Peterborough',
        'Waterloo',
        'Welland',
        'Kingston',
        'Lethbridge',
        'Guelph',
    ]],
    'South Africa' => ['continent' => 'Africa', 'cities' => [
        'Boksburg',
        'Midrand',
        'Welkom',
        'Krugersdorp',
        'Germiston',
        'Odendaalsrus',
        'Cape Town',
        'Pretoria',
        'Glenwood',
        'Auckland Park',
        'Johannesburg',
        'KwaZulu-Natal',
        'Potchefstroom',
        'Stellenbosch',
        'Grahamstown',
        'Port Elizabeth',
        'Bellville',
        'Alice',
        'Empangeni',
        'Bloemfontein',
        'Vanderbijlpark',
        'Vereeniging',
        'Durban',
        'Thohoyandou',
        '‎Gauteng',
        'Ladysmith',
        'Langebaan',
        'Eastern Cape',
        'North West',
        'Pietermaritzburg',
        'Rustenburg',
        'Northern Cape',
        'Newcastle',
        'Welkom',
    ]],
    'Spain' => ['continent' => 'Europe', 'cities' => [
        'Gibraltar',
        'Navarra',
        'San Cristobal de La Laguna',
        'Barcelona',
        'Madrid',
        'Pamplona',
        'Valencia',
        'Calvia',
        'Compostela',
        'Salamanca',
        'Granada',
        'Zaragoza',
        'Seville',
        'Murcia',
        'Alicante',
        'Ciudad Real',
        'Cordoba',
        'Getafe',
        'Las Palmas',
        'mostoles',
        'Cadiz',
        'Oviedo',
        'Huelva',
        'A Coruna',
        'Alcalá de Henares',
        'Tarragona',
        'Badajoz',
        'Palma',
        'Jaen',
        'Leon',
        'Bilbao',
        'Elche',
        'Cartagena',
        'Burgos',
        'Lleida',
        'Mondragon',
        'Moncada',
        'Vic',
        'Valladolid',
        'Segovia',
        'Santander',
        'Castellon de la Plana',
        'Sabadell',
        'Malaga',
        'Vigo',
        'Zamudio',
        'Biscay',
        'Marbella',
        'Andalusia',
        'Castile & Leon',
        'Catalonia',
        '‎Cantabria',
        'Toledo', ]],
    'The Gambia' => ['continent' => 'Africa', 'cities' => [
        'Abuko',
        'Bakau',
        'Banjul',
        'Bansang',
        'Basse Santa Su',
        'Brikama',
        'Brufut',
        'Farafenni',
        'Gimara Bakadaji',
        'Gunjur',
        'Janjanbureh (Georgetown]',
        'Jufureh',
        'Kalagi',
        'Kanilai',
        'Kerewan',
        'Kololi',
        'Kuntaur',
        'Lamin (North Bank Division]',
        'Lamin (Western Division]',
        'Mansa Konko',
        'Nema Kunku',
        'Serekunda',
        'Soma',
        'Sukuta',
        'Tanji', ]],
    'Thailand' => ['continent' => 'Asia', 'cities' => [
        'Bangkok',
        'Nakhon Pathom',
        'Chiang Mai',
        'Khon Kaen',
        'Nakhon Nayok',
        'Phra Nakhon Si Ayutthaya',
        'Phetchaburi',
        'Chiang Rai',
        'Chonburi',
        'Lampang',
        'Maha Sarakham',
        'Hat Yai',
        'Phitsanulok',
        'Ubon Ratchathani',
        'Nakhon Ratchasima',
        'Songkhla',
        'Nakhon Si Thammarat',
        'Rangsit',
        'Surat Thani',
        'Yala',
        'Nonthaburi',
        'Rayong',
        'Phuket',
        'Saraburi',
        'Nakorn Ratchasima',
        'Pathumthani',
        'Samutprakarn',
        'Udon Thani',
        'Krabi',
        'Chiangmai',
        'Phatthaya',
        'Pathum Thani', ]],
    'Italy' => ['continent' => 'Europe', 'cities' => [
        'Rome',
        'Rimini',
        'Padova',
        'Milan',
        'Florence',
        'pavia',
        'Trento',
        'Trieste',
        'Turin',
        'Siena',
        'Perugia',
        'Genoa',
        'Catania',
        'Venice',
        'Bologna',
        'Pisa',
        'Bari',
        'Salerno',
        'Udine',
        'Brescia',
        'Parma',
        'Sassari',
        'Palermo',
        'Cosenza',
        'Verona',
        'Modena',
        'Ferrara',
        'Ancona',
        'Chieti',
        'Bolzano',
        'Venezia',
        "L'Aquila",
        'Macerata',
        'Caserta',
        'Cassino',
        'Foggia',
        'Naples',
        'Varese',
        'Castellanza',
        'Reggio Calabria',
        'Teramo',
        'Catanzaro',
        'Campobasso',
        'Pollenzo',
        'Aosta',
        'Treviso',
        'Bergamo',
        'Messina',
        'Enna',
        'Brindisi',
        'Genova',
        'Mestre',
        'Vicenza',
        'Monza',
        'Como',
        'Sicily',
        'Tuscany',
        'Emilia-Romagna',
        'Sardinia', ]],
    'Malaysia' => ['continent' => 'Asia', 'cities' => [
        'Kuala Lumpur',
        'Skudai',
        'Seremban',
        'Pekan',
        'Arau',
        'Kota Kinabalu',
        'Kota Samarahan',
        'Kuala Terengganu',
        'Nilai',
        'Sintok',
        'Iskandar Puteri',
        'Shah Alam',
        'Petaling Jaya',
        'Tanjung Malim',
        'Seri Iskandar',
        'Ipoh',
        'Cyberjaya',
        'Subang Jaya',
        'Seri kembangan',
        'Parit Raja',
        'Penang',
        'Sungai Buloh',
        'Johor Bahru',
        'Malacca',
        'Alor Setar',
        'George Town',
        'Negeri Sembilan',
        'State Sabah',
        'Kuching',
        'Selangor',
        'Putrajaya',
        'Miri',
        'Sarawak',
        'Kajang',
        'State Johor',
        'Perak',
        'Johor', ]],
    'Indonesia' => ['continent' => 'Asia', 'cities' => [
        'Magelang',
        'Gresik Regency',
        'Kota Depok',
        'Yogyakarta',
        'Bandung',
        'Surabaya',
        'Malang',
        'Semarang',
        'Jakarta',
        'Lampung',
        'Denpasar',
        'Padang',
        'Surakarta',
        'Depok',
        'Purwokerto',
        'East Java',
        'Manado',
        'Salatiga',
        'Bali',
        'Gorontalo',
        'Riau',
        'Makassar',
        'Medan',
        'Kendari',
        'Bengkulu',
        'Tasikmalaya',
        'Aceh',
        'Tangerang',
        'Banten',
        'Jepara',
        'Samarinda',
        'Jambi',
        'Ambon',
        'Batam',
        'Sidoarjo',
        'Pasuruan',
        'Bogor',
        'Bekasi',
        'Sukabumi',
        'North Sumatra',
        'Pematangsiantar',
        'Palembang',
        'Mataram',
        'Pontianak',
        'Palangkaraya',
        'South Jakarta',
        'West Jakarta',
        'North Jakarta',
        'East Jakarta',
        'West Java',
        'Tembagapura', ]],
    'Greece' => ['continent' => 'Europe', 'cities' => [
        'Athens',
        'Rhodes',
        'Rethymno',
        'Thessaloniki',
        'Patras',
        'Xanthi',
        'Loannina',
        'Chania',
        'Piraeus',
        'Heraklion',
        'Mytilene',
        'Volos',
        'Kozani',
        'Larissa',
        'Serres',
        'Corfu',
        'Arta',
        'kavala',
        'Argostoli',
        'Crete',
        'Pallini',
        'Koropi',
        'Kalamata', ]],
    'Poland' => ['continent' => 'Europe', 'cities' => [
        'Krakow',
        'Warsaw',
        'Łódź',
        'poznan',
        'Torun',
        'Bydgoszcz',
        'Katowice',
        'Lodz',
        'Gliwice',
        'Gdansk',
        'Olsztyn',
        'Lublin',
        'Rzeszow',
        'Bialystok',
        'Wrocław',
        'Zielona Gora',
        'Szczecin',
        'Opole',
        'Kielce',
        'Bielsko-biala',
        'Nowy Sacz',
        'Koszalin',
        'Czestochowa',
        'Siedlce',
        'Gdynia',
        'Zamosc',
        'Lomza',
        'Chelm',
        'Pila',
        'Plock',
        'Radom',
        'Pultusk', ]],
    'Argentina' => ['continent' => 'South America', 'cities' => [
        'Cordoba',
        'Buenos Aires',
        'Pilar',
        'Mendoza',
        'Entre Rios',
        'Tandil',
        'Bahia Blanca',
        'Florencio Varela',
        'Tucuman',
        'Santiago del Estero', ]],
    'Pakistan' => ['continent' => 'Asia', 'cities' => [
        'Mansehra',
        'Islamabad',
        'Khuzdar',
        'Uthal',
        'Quetta',
        'Muzaffarabad',
        'Sudhnoti',
        'Karachi',
        'Lahore',
        'Peshawar',
        'Bahawalpur',
        'Gujrat',
        'Faisalabad',
        'Gujranwala',
        'Multan',
        'Bhimber',
        'Rawalpindi',
        'Sargodha',
        'Hyderabad cities',
        'Jamshoro',
        'Khairpur',
        'Nawabshah',
        'Sukkur',
        'Bannu',
        'Lower Dir District',
        'Dera Ismail Khan',
        'Kohat',
        'Nowshera',
        'Swabi',
        'Gilgit',
        'Swat',
        'Mardan',
        'Mirpur',
        'Poonch',
        'Kotli',
        'Bagh',
        'Turbat',
        'Zhob',
        'Upper Dir',
        'Haripur',
        'Abbottabad',
        'Karak',
        'Rahim Yar Khan',
        'Sialkot',
        'Dera Ghazi Khan',
        'Larkana',
        'Sindh', ]],
    'Wales' => ['continent' => 'Europe', 'cities' => [
        'bangor',
        'Swansea',
        'Ceredigion',
        'Cardiff',
        'Llanelli',
        'Wrexham',
        'Port Talbot',
        'Pembrokeshire',
        'Glamorgan',
        'Carmarthenshire',
        'Pontypridd',
        'Anglesey',
        'Amlwch',
        'Menai Bridge',
        'Holyhead',
        'Ebbw Vale',
        'Abertillery',
        'Tredegar',
        'Llantwit Major',
        'Crumlin',
        'Blaina',
        'Bridgend',
        'Maesteg',
        'Porthcawl',
        'Aberbargoed',
        'cities Newport',
        'Caerphilly',
        'Blackwood',
        'Bargoed',
        'Rhymney',
        'Newbridge',
        'Ystrad Mynach',
        'Risca',
        'Merthyr Tydfil',
        'Carmarthen',
        'Cardigan',
        'cities Ammanford',
        'Llandysul',
        'Burry Port',
        'Pencader',
        'Lampeter',
        'Kidwelly',
        'Cynwyl Elfed',
        'Llandeilo',
        'St Clears',
        'Pontarddulais',
        'Johnstown',
        'Laugharne',
        'Llangunnor',
        'Llanllwni',
        'Llanmiloe',
        'Neath',
        'Llanybydder',
        'Whitland',
        'Pembrey',
        'Llandovery',
        'Pendine',
        'Trimsaran',
        'Newcastle Emlyn',
        'Aberystwyth',
        'Tregaron',
        'Flintshire',
        'Aberaeron',
        'Conwy',
        'Colwyn Bay',
        'Abergele',
        'Llandudno',
        'Deganwy',
        'Haverfordwest',
        'Prestatyn',
        'Rhyl',
        'St Asaph',
        'Denbigh',
        'Ruthin',
        'Corwen',
        'Llanferres',
        'llandegla',
        'Llangollen',
        'Crickhowell',
        'Holywell',
        'Buckley',
        'Ewloe',
        'Mold',
        'Hawarden',
        'Queensferry',
        'Saltney',
        'Connahs Quay',
        'Caerwys',
        'cities Bangor',
        'Pwllheli',
        'Caernarfon',
        'Tregarth',
        'Bala',
        'Llanegryn',
        'Llanberis',
        'Dolgellau',
        'Garndolbenmaen',
        'Llanbedrog',
        'Tywyn',
        'Talysarn',
        'Bethesda',
        'Blaenau Ffestiniog',
        'Porthmadog',
        'Barmouth',
        'Harlech',
        'Botwnnog',
        'Penrhyndeudraeth',
        'Treharris',
        'Aberdare',
        'Abergavenny',
        'Brecon',
        'Caldicot',
        'Chepstow',
        'Pontypool',
        'Monmouth',
        'Llandogo',
        'Raglan',
        'Usk',
        'Denbighshire',
        'Gwynedd',
        'Monmouthshire',
        'Blaenau Gwent', ]],
    'Portugal' => ['continent' => 'Europe', 'cities' => [
        'Lisbon',
        'Coimbra',
        'Porto',
        'Braga',
        'Paco de arcos',
        'Pacos de brando',
        'Beja',
        'Senhora da Hora',
        'Estoril',
        'Tomar',
        'Barcelos',
        'Viana Do Castelo',
        'Viseu',
        'Faro',
        'Covilha',
        'Vila real',
        'Aveiro',
        'Portalegre',
        'Setubal',
        'Leiria',
        'Funchal',
        'Oliveira de Azemeis',
        'Maia',
        'Gandra',
        'Vila Nova de Gaia',
        'Almada',
        'Braganca',
        'Norte',
        'Centro', ]],
    'Peru' => ['continent' => 'South America', 'cities' => [
        'Cusco',
    ]],
    'Mexico' => ['continent' => 'North America', 'cities' => [
        'Monterrey',
        'Mexico cities',
        'Guanajuato',
        'Alvaro Obregon',
        'Leon',
        'Ecatepec',
        'Guadalajara',
        'Puebla',
        'Juárez',
        'Tijuana',
        'Zapopan',
        'Nezahualcóyotl',
        'Culiacán',
        'Chihuahua',
        'Naucalpan',
        'Mérida',
        'San Luis Potosí',
        'Aguascalientes',
        'Hermosillo',
        'Saltillo',
        'Mexicali',
        'Guadalupe',
        'Acapulco',
        'Tlalnepantla',
        'Cancún',
        'Querétaro',
        'Chimalhuacán',
        'Torreón',
        'Morelia',
        'Reynosa',
        'Tlaquepaque',
        'Tuxtla Gutiérrez',
        'Durango',
        'Toluca',
        'Ciudad López Mateos',
        'Cuautitlán Izcalli',
        'Ciudad Apodaca',
        'Matamoros',
        'San Nicolás de los Garza',
        'Veracruz',
        'Xalapa',
        'Tonalá',
        'Mazatlán',
        'Irapuato',
        'Nuevo Laredo',
        'Xico',
        'Villahermosa',
        'General Escobedo',
        'Celaya',
        'Cuernavaca',
        'Tepic',
        'Ixtapaluca',
        'Ciudad Victoria',
        'Ciudad Obregón',
        'Tampico',
        'Ciudad Nicolás Romero',
        'Ensenada',
        'Coacalco de Berriozábal',
        'Santa Catarina',
        'Uruapan',
        'Gómez Palacio',
        'Los Mochis',
        'Pachuca',
        'Oaxaca',
        'Soledad de Graciano Sánchez',
        'Tehuacán',
        'Ojo de Agua',
        'Coatzacoalcos',
        'Campeche',
        'Monclova',
        'La Paz',
        'Nogales',
        'Buenavista',
        'Puerto Vallarta',
        'Tapachula',
        'Ciudad Madero',
        'San Pablo de las Salinas',
        'Chilpancingo',
        'Poza Rica',
        'Chicoloapan de Juárez',
        'Ciudad del Carmen',
        'Chalco de Díaz Covarrubias',
        'Jiutepec',
        'Salamanca',
        'San Luis Río Colorado',
        'Cuautla',
        'Ciudad Benito Juárez',
        'Chetumal',
        'Piedras Negras',
        'Playa del Carmen',
        'Zamora',
        'Córdoba',
        'San Juan del Río',
        'Colima',
        'Ciudad Acuña',
        'Manzanillo',
        'Zacatecas',
        'Veracruz',
        'Ciudad Valles',
        'Guadalupe',
        'San Pedro Garza García',
        'Naucalpan',
        'Fresnillo',
        'Orizaba',
        'Miramar',
        'Iguala',
        'Delicias',
        'Ciudad de Villa de Álvarez',
        'Ciudad Cuauhtémoc',
        'Navojoa',
        'Guaymas',
        'Minatitlán',
        'Cuautitlán',
        'Texcoco',
        'Hidalgo del Parral',
        'Tepexpan',
        'Tulancingo',

    ]],
    'Philippines' => ['continent' => 'Asia', 'cities' => [
        'Goa',
        'Banga',
        'Murcia',
        'Virac',
        'Baliuag',
        'Daet',
        'Aborlan',
        'Boac',
        'Iba',
        'La Trinidad',
        'Bangued',
        'Paranaque',
        'San Pablo cities',
        'Isabela',
        'Cainta',
        'Manila',
        'Cagayan Valley',
        'Tuguegarao',
        'Calabarzon',
        'Batangas cities',
        'Cavite cities',
        'Lucena',
        'Dasmariñas',
        'Caraga',
        'Central Luzon',
        'Cabanatuan',
        'Malolos',
        'Meycauayan',
        'Muñoz',
        'Tarlac cities',
        'Tagbilaran',
        'Cebu',
        'Central Visayas',
        'Dumaguete',
        'Mandaue',
        'Davao',
        'Baybay',
        'Eastern Visayas',
        'Tacloban',
        'Ilocos',
        'Dagupan',
        'Vigan',
        'Cagayan de Oro',
        'Northern Mindanao',
        'Ozamiz',
        'Quezon cities',
        'Bacolod',
        'Western Visayas',
        'Iloilo cities',
        'Baguio',
        'Makati',
        'Mandaluyong',
        'Naga',
        'Zamboanga cities',
        'Caloocan',
        'General Santos',
        'Iriga',
        'Koronadal',
        'Las Piñas',
        'Legazpi',
        'Marawi',
        'Pasay',
        'Pasig',
        'Puerto Princesa',
        'San Juan',
        'Valenzuela',
        'Butuan',
        'Sorsogon cities',
        'Balanga',
        'Pampanga',
        'Catbalogan',
        'Borongan',
        'Gingoog',
        'Odiongan',
        'Taytay',
        'Roxas',
        'Guimaras',
        'Quirino',
        'Digos',
        'Kidapawan',
        'Nueva Ecija',
        'Leyte',
        'Bicol',
        'Cotabato',
        'Romblon', ]],
    'India' => ['continent' => 'Asia', 'cities' => [
        'Bidar',
        'Goa',
        'Belgaum',
        'Sonipat',
        'Ponda',
        'Samastipur',
        'Andhra Pradesh',
        'Kurnool',
        'Kakinada',
        'Assam',
        'Bangalore',
        'Bihar',
        'Madhepura',
        'Patna',
        'Chennai',
        'Gujarat',
        'Haryana',
        'Hisar',
        'Himachal Pradesh',
        'Amritsar',
        'Punjab',
        'Hyderabad',
        'Jaipur',
        'Jammu and Kashmir',
        'Jharkhand',
        'Karnataka',
        'Tumkur',
        'Kerala',
        'Lucknow',
        'Madhya Pradesh',
        'Jabalpur',
        'Rewa',
        'Maharashtra',
        'Meghalaya',
        'Mumbai',
        'Rajasthan',
        'New Delhi',
        'Orissa',
        'Rourkela',
        'Pune',
        'Patiala',
        'Rupnagar',
        'Raipur',
        'Jodhpur',
        'Ajmer',
        'Ladnun',
        'Udaipur',
        'Kanchipuram',
        'Tamil Nadu',
        'Madurai',
        'Coimbatore',
        'Kodaikanal',
        'Thanjavur',
        'Tiruchirappalli',
        'Tirunelveli',
        'Uttar Pradesh',
        'Kanpur',
        'Rampur',
        'Allahabad',
        'Bareilly',
        'Greater Noida',
        'Varanasi',
        'Uttarakhand',
        'Dehradun',
        'Haridwar',
        'Roorkee',
        'Nainital',
        'Kolkata',
        'West Bengal',
        'Howrah',
        'Bardhaman',
        'Agartala',
        'Chandigarh',
        'Bhilai',
        'Imphal',
        'Itanagar',
        'Rajnandgaon',
        'Jagdalpur',
        'Bilaspur',
        'Dimapur',
        'Faridabad',
        'Sikar',
        'Peelamedu',
        'Indore',
        'Jorhat',
        'Sivasagar',
        'Pondicherry',
        'Aizawl',
        'Churachandpur',
        'Sricities',
        'Visakhapatnam',
        'Guwahati',
        'Arunachal Pradesh',
        'Gurugram',
        'Shillong',
        'Gangtok',
        'Rohtak',
        'Srinagar',
        'Bijapur',
        'Bagalkot',
        'Kolar',
        'Hubli',
        'Shimoga',
        'Mangalore',
        'Mysore',
        'Bhopal',
        'Sehore',
        'Gwalior',
        'Satna',
        'Ujjain',
        'Sagar',
        'Shivpuri',
        'Bikaner',
        'Sardarshahar',
        'Banswara',
        'Churu',
        'Alwar',
        'Sri Ganganagar',
        'Bhilwara',
        'Sirohi',
        'Salem',
        'Anandnagar',
        'Rishikesh',
        'Darbhanga',
        'Gaya',
        'Rajgir',
        'Bihar Sharif',
        'Atal Nagar',
        'Kumhari',
        'Gandhinagar',
        'Vadodara',
        'Rajkot',
        'Surat',
        'Ahmedabad',
        'Visnagar',
        'Mehsana',
        'Shimla',
        'Ranchi',
        'Jamshedpur',
        'Thiruvananthapuram',
        'Malappuram',
        'Kottayam',
        'Parbhani',
        'Nagpur',
        'Karad',
        'Kolhapur',
        'Aurangabad',
        'Bhubaneswar',
        'Cuttack',
        'Berhampur',
        'Mohali',
        'Jalandhar',
        'Ludhiana',
        'Phagwara',
        'Hoshiarpur',
        'Bathinda',
        'Sambalpur',
        'Gorakhpur',
        'Agra',
        'Jais',
        'Mathura',
        'Ghaziabad',
        'Firozabad',
        'Saharanpur',
        'Hapur',
        'Banda',
        'Jhansi',
        'Bulandshahr',
        'Durgapur',
        'Raiganj',
        'Dhanbad',
        'Guntur',
        'cities Kochi',
        'Ahmednagar',
        'Bhimavaram',
        'Odisha',
        'Chhattisgarh',
        'Tripura',
        'Manipur',
        'Nagaland',
        'Sikkim', ]],
    'North Korea' => ['continent' => 'Asia', 'cities' => [
        'Pyongyang',
    ]],
    'Northern Ireland' => ['continent' => 'Europe', 'cities' => [
        'Ballina',
        'Belfast',
        'Dungannon',
        'Coleraine',
        'Armagh',
        'Holywood',
        'Bangor', ]],
    'Scotland' => ['continent' => 'Europe', 'cities' => [
        'Dunbar',
        'Edinburgh',
        'Glasgow',
        'Aberdeen',
        'Dundee',
        'Fife',
        'Stirling',
        'Inverness',
        'Paisley',
        'Clackmannanshire',
        'Crieff',
        'Cupar',
        'Perth',
        'Moray',
        'Perthshire',
        'Helensburgh',
        'Musselburgh',
        'St Andrews', ]],
    'Romania' => ['continent' => 'Europe', 'cities' => [
        'Cluj Napoca',
        'Lasi',
        'Bucharest',
        'Bucuresti',
        'Timisoara',
        'Craiova',
        'Bacau',
        'Targu mures',
        'Resita',
        'Pitesti',
        'Oradea',
        'Arad',
        'Targoviste',
        'Galati',
        'Brasov',
        'Suceava',
        'Constanta',
        'Sibiu', ]],
    'Belarus' => ['continent' => 'Europe', 'cities' => [
        'Minsk',
        'Vitebsk',
        'Novopolotsk',
        'Grodno',
        'Gomel',
        'Horki',
        'Mazyr',
        'Baranovichi',
        'Mogilev',
        'Pinsk',
        'Brest', ]],
    'Bosnia and Herzegovina' => ['continent' => 'Europe', 'cities' => [
        'Sarajevo',
        'Zenica',
        'Tuzla',
        'Bihac',
        'Banja Luka',
        'Mostar',
        'Travnik',
        'Slobomir',
        'Bijeljina', ]],
    'Albania' => ['continent' => 'Europe', 'cities' => [
        'Tirana',
        'Shkoder',
        'Gjirokaster',
        'Korce',
        'Vlore', ]],
    'Bulgaria' => ['continent' => 'Europe', 'cities' => [
        'Varna',
        'Sofia',
        'Blagoevgrad',
        'Ruse',
        'Svishtov',
        'Stara Zagora',
        'Plovdiv',
        'Gabrovo',
        'Shumen',
        'Tarnovo',
        'Pleven',
        'Burgas',
        'Botevgrad',
        'Velika Turnovo',
        'Pernik', ]],
    'Estonia' => ['continent' => 'Europe', 'cities' => [
        'Tartu',
        'Tallinn', ]],
    'Hungary' => ['continent' => 'Europe', 'cities' => [
        'Gyor',
        'Budapest',
        'Szeged',
        'Debrecen',
        'Pecs',
        'Veszprem',
        'Sopron',
        'Szekesfehervar',
        'Dunaujvaros',
        'Kaposvar',
        'Eger',
        'Miskolc',
        'Tatabanya',
        'Gyongyos',
        'Godollo', ]],
    'Croatia' => ['continent' => 'Europe', 'cities' => [
        'Zagreb',
        'Rijeka',
        'Split',
        'Osijek',
        'Zadar',
        'Pula',
        'Dubrovnik',
        'Koprivnica', ]],
    'Czech Republic' => ['continent' => 'Europe', 'cities' => [
        'Brno',
        'Prague',
        'Olomouc',
        'Ostrava',
        'Pilsen',
        'Opava',
        'Zlin',
        'Liberec',
        'Usti nad Labem',
        'Hradec Kralove',
        'Boleslav',
        'Znojmo',
        'Prerov',
        'Pisek',
        'Jihlava',
        'Pardubice',
        'Ceske Budejovice',
        'Havirov', ]],
    'Iceland' => ['continent' => 'Europe', 'cities' => [
        'Reykjavik',
        'Akureyri',
        'Borgarnes',
        'Sauoarkrokur', ]],
    'Macedonia' => ['continent' => 'Europe', 'cities' => [
        'Skopje',
        'Tetovo',
        'Bitola',
        'Stip',
        'ohrid',
        'Struga',
        'Gostivar',
        'Sveti Nikole', ]],
    'Latvia' => ['continent' => 'Europe', 'cities' => [
        'Riga',
        'Jelgava',
        'Valmiera',
        'Daugavpils',
        'Rezekne',
        'Liepaja',
        'Ventspils',
        'Jurmala', ]],
    'Lithuania' => ['continent' => 'Europe', 'cities' => [
        'Vilnius',
        'Alytus',
        'Kaunas',
        'Klaipeda',
        'Marijampole',
        'Siauliai',
        'Utena',
        'Panevezys', ]],
    'Malta' => ['continent' => 'Europe', 'cities' => [
        'Msida',
        'Paola',
        "St. Julian's",
        'Sliema', ]],
    'Moldova' => ['continent' => 'Europe', 'cities' => [
        'Chisinau', ]],
    'Liechtenstein' => ['continent' => 'Europe', 'cities' => [
        'Mauren',
        'Vaduz', ]],
    'Monaco' => ['continent' => 'Europe', 'cities' => [
        'Monte carlo', ]],
    'Serbia' => ['continent' => 'Europe', 'cities' => [
        'Belgrade',
        'Novi sad',
        'Nis',
        'Kragujevac',
        'Novi Pazar',
        'Sremska Kamenica', ]],
    'Slovakia' => ['continent' => 'Europe', 'cities' => [
        'Kosice',
        'Banska Bystrica',
        'Bratislava',
        'Nitra',
        'Zilina',
        'Trnava',
        'Presov',
        'Skalica',
        'Sladkovicovo',
        'Komarno',
        'Dubnica nad Vahom',
        'Ruzomberok', ]],
    'Luxembourg' => ['continent' => 'Europe', 'cities' => [
        'Esch Sur Alzette',
        'Luxembourg cities', ]],
    'Slovenia' => ['continent' => 'Europe', 'cities' => [
        'Ljubljana',
        'Maribor',
        'Koper',
        'Gorica',
        'Piran',
        'Celje',
        'Celije',
        'Nova Gorica', ]],
    'Ukraine' => ['continent' => 'Europe', 'cities' => [
        'Kiev',
        'Dnipropetrovsk',
        'Sumy',
        'Ternopil',
        'Ivano Frankivsk',
        'Odessa',
        'kharkiv',
        'Lviv',
        'Nizhyn',
        'Poltava',
        'Rivne',
        'Zaporizhia',
        'Melitopol',
        'Chernihiv',
        'Donetsk',
        'Chernivtsi',
        'Uzhhorod',
        'Mykolaiv',
        'Simferopol',
        'Lutsk',
        'Bila Tserkva',
        'Vinnitsa',
        'Zhytomyr',
        'Ostroh',
        'Vinnytsia',
        'Luhansk',
        'Kremenchuk',
        'Cherkasy',
        'Severodonetsk',
        'Mariupol',
        'Uman',
        'Hlukhiv',
        'Dubliany',
        'Lugansk',
        'Kropyvnytskyi',
        'Kryvyi Rih',
        'Dnipro',
        'Mukachevo', ]],
    'Andorra' => ['continent' => 'Europe', 'cities' => [
        'Sant Julia de Loria', ]],
    'Singapore' => ['continent' => 'Asia', 'cities' => [
        'Singapore cities',
        'Queenstown',
        'Sentosa',
        'Bishan',
        'Shaw Tower',
        'Downtown Core',
        'Robertson Key',
        'Bukit Timah',
        'Bukit Batok',
        'Jurong West',
        'Clementi',
        'Tanglin',
        'Ang Mo Kio',
        'Hougang',
        'Novena',
        'Kallang',
        'Marine Parade',
        'Tanjong Katong',
        'Pulau Ujong',
        'Tiong Bahru',
        'Bedok',
        'Yishun',
        'Sengkang',
        'Serangoon',
        'Mandai',
        'River Valley',
        'Newton',
        'Tampines',
        'Geylang',
        'Paya Lebar',
        'Punggol', ]],
    'San Marino' => ['continent' => 'Europe', 'cities' => [
        'San Marino cities', ]],
    'Vietnam' => ['continent' => 'Asia', 'cities' => [
        'Ho Chi Minh cities',
        'Hanoi',
        'Hoi An',
        'Thu Dau Mot',
        'Haiphong',
        'Vung Tau', ]],
    'Brunei' => ['continent' => 'Asia', 'cities' => [
        'Bandar Seri Begawan',
        'Seria',
        'Belait',
        'Kuala Belait',
        'Gadong',
        'Jerudong', ]],
    'England' => ['continent' => 'Europe', 'cities' => [
        'Chichester',
        'Leeds',
        'London',
        'Liverpool',
        'Birmingham',
        'Manchester',
        'Cardiff',
        'Wiltshire',
        'Farnborough',
        'Maidenhead',
        'Aylesbury',
        'Sutton Coldfield',
        'Nottingham',
        'Rutland',
        'Ely',
        'Gloucestershire',
        'York',
        'Brighton',
        'Shropshire',
        'Kent',
        'West Sussex',
        'Lancashire',
        'Surrey',
        'Worcestershire',
        'Somerset',
        'Bristol',
        'Bedfordshire',
        'Hertfordshire',
        'Buckinghamshire',
        'Loughborough',
        'Peterborough',
        'Taunton',
        'Derbyshire',
        'Suffolk',
        'East Sussex',
        'Cheshire',
        'Winchester',
        'Canterbury',
        'Berkshire',
        'County Durham',
        'Hampshire',
        'Norfolk',
        'North Yorkshire',
        'Salisbury',
        'Warwickshire',
        'Worcester',
        'Cambridge',
        'Staffordshire',
        'Oxfordshire',
        'Preston',
        'West Yorkshire',
        'Devon',
        'Northampton',
        'Dorset',
        'Essex',
        'Leicestershire',
        'Oxford',
        'Durham',
        'Leicester',
        'Cumbria',
        'Cannock',
        'Chelmsford',
        'Reading',
        'Chigwell',
        'Plymouth',
        'Lincolnshire',
        'Chester',
        'Wolverhampton',
        'Bournemouth',
        'Cornwall',
        'Bath',
        'Warminster',
        'Warwick',
        'Folkestone',
        'Portsmouth',
        'Windermere',
        'Nottinghamshire',
        'Eastbourne',
        'Hereford',
        'Cambridgeshire',
        'Merseyside',
        'Norwich',
        'Lincoln',
        'Northumberland',
        'Herefordshire',
        'Northamptonshire',
        'Ryde',
        'Sheffield',
        'Petworth',
        'Bradford',
        'Coventry',
        'Croydon',
        'Bury St Edmunds',
        'Newcastle-upon-Tyne',
        'Uxbridge',
        'Halesowen',
        'Swindon',
        'Hull',
        'Twickenham',
        'Wakefield',
        'Southampton',
        'Stevenage',
        'Harlow', ]],
    'Montenegro' => ['continent' => 'Europe', 'cities' => [
        'Tivat', ]],
    "Côte d'Ivoire" => ['continent' => 'Africa', 'cities' => [
        'Abidjan', ]],
    'Cyprus' => ['continent' => 'Europe', 'cities' => [
        'Famagusta',
        'Acheritou',
        'Güvercinlik',
        'Achna',
        'Düzce/Ahna',
        'Afania',
        'Gaziköy',
        'Agia Trias',
        'Sipahi',
        'Agios',
        'Andronios',
        'Topçuköy',
        'Agios Andronikos',
        'Yeşilköy',
        'Agios Chartion',
        'Ergenekon',
        'Agios Efstathios',
        'Zeybekköy',
        'Agios Georgios',
        'Aygün',
        'Agios Iakovo',
        'Altınova',
        'Agios Ilias',
        'Yarköy',
        'Agios Nikolaos',
        'Yamaçköy',
        'Agios Sergios',
        'Yeniboğaziçi/Yeni Boğaziçi',
        'Agios Symeon',
        'Avtepe',
        'Agios',
        'Theodoros',
        'Çayırova',
        'Akanthou',
        'Tatlısu',
        'Aloa',
        'Atlılar',
        'Ammochostos',
        'Mağusa/Gazimağusa',
        'Angastina',
        'Aslanköy',
        'Ardana',
        'Ardahan',
        'Arnadi',
        'Kuzucuk',
        'Artemi',
        'Arıdamı',
        'Assia',
        'Paşaköy',
        'Avgolida',
        'Kurtuluş',
        'Bogazi',
        'Boğaz',
        'Davlos',
        'Kaplıca',
        'Egkomi',
        'Tuzla',
        'Eptakomi',
        'Yedikonuk',
        'Flamoudi',
        'Mersinlik',
        'Gaidouras',
        'Korkuteli',
        'Galatia',
        'Mehmetçik',
        'Galinoporni',
        'Kaleburnu',
        'Gastria',
        'Kelecik',
        'Genagra',
        'Nergizli',
        'Gerani',
        'Turnalar',
        'Gialousa',
        'Yenierenköy/Yeni Erenköy',
        'Goufes',
        'Çamlıca',
        'Gypsou',
        'Akova',
        'Kalopsida',
        'Çayönü',
        'Kiados',
        'Serdarlı',
        'Kilanemos',
        'Esenköy',
        'Knodara',
        'Gönendere',
        'Koma tou Gialou',
        'Kumyalı',
        'Komi Kepir',
        'Büyükkonuk',
        'Kontea',
        'Türkmenköy',
        'Kornokipos',
        'Görneç',
        'Korovia',
        'Kuruova',
        'Kouklia',
        'Köprülü',
        'Kridia',
        'Kilitkaya',
        'Lapathos',
        'Sınırüstü',
        'Lefkoniko',
        'Geçitkale',
        'Leonarisso',
        'Ziyamet',
        'Limnia',
        'Mormenekşe',
        'Livadia',
        'Sazlıköy',
        'Lysi',
        'Akdoğan',
        'Lythragkomi',
        'Boltaşlı',
        'Makrasyka',
        'İncirli',
        'Mandres',
        'Ağıllar',
        'Maratha',
        'Muratağa',
        'Marathovounos',
        'Ulukışla',
        'Melanarka',
        'Adaçay',
        'Melounta',
        'Mallıdağ',
        'Millia',
        'Yıldırım',
        'Monagra',
        'Boğaztepe',
        'Mousoulita',
        'Kurudere',
        'Neta',
        'Taşlıca',
        'Ovgoros',
        'Ergazi',
        'Patriki',
        'Tuzluca',
        'Pergamos',
        'Beyarmudu',
        'Peristerona',
        'Alaniçi',
        'Perivolia tou Trikomou',
        'Bahçeler/Bahçalar',
        'Platani',
        'Çınarlı',
        'Platanissos',
        'Balalan',
        'Prastio',
        'Dörtyol',
        'Psyllatos',
        'Sütlüce',
        'Pyrga',
        'Pirhan',
        'Rizokarpaso',
        'Dipkarpaz',
        'Santalaris',
        'Sandallar/Şehitler',
        'Sinta',
        'İnönü/Sinde',
        'Spathariko',
        'Ötüken',
        'Strongylos',
        'Turunçlu',
        'Stylli',
        'Mutluyaka',
        'Tavros',
        'Pamuklu',
        'Trikomo',
        'İskele',
        'Trypimeni',
        'Tirmen',
        'Vasili',
        'Gelincik',
        'Vatili',
        'Vadili',
        'Vathylakas',
        'Derince',
        'Vitsada',
        'Pınarlı',
        'Vokolida',
        'Bafra',
        'Kyrenia',
        'Agia Irini',
        'Akdeniz',
        'Agios Amvrosios',
        'Esentepe',
        'Agios Epiktitos',
        'Çatalköy',
        'Agios Ermolaos',
        'Şirinevler',
        'Agios Georgios',
        'Karaoğlanoğlu',
        'Agirta',
        'Ağırdağ',
        'Agridaki',
        'Alemdağ',
        'Asomatos',
        'Özhan',
        'Belapais',
        'Beylerbeyi/Belabayıs',
        'Charchia',
        'Karaağaç',
        'Diorios',
        'Tepebaşı',
        'Elia',
        'Yeşiltepe',
        'Fota',
        'Dağyolu',
        'Ftericha',
        'Ilgaz',
        'Kalogrea',
        'Bahçeli',
        'Kampyli',
        'Hisarköy',
        'Karakoumi',
        'Karakum',
        'Karmi',
        'Karaman',
        'Karpasia',
        'Karpaşa/Kırpaşa/Karpaz',
        'Kato Dikomo',
        'Aşağıdikmen/Aşağı',
        'Dikmen',
        'Kazafani',
        'Ozanköy/Kazafana',
        'Kepini',
        'Arapköy',
        'Kyrenia',
        'Girne',
        'Komurcu',
        'Kömürcü',
        'Kontemenos',
        'Kılıçaslan',
        'Kormakitis',
        'Koruçam/Kormacit',
        'Koutoventis',
        'Güngör',
        'Krini',
        'Pınarbaşı',
        'Lapithos',
        'Lapta',
        'Larnakas',
        'Kozan',
        'Livera',
        'Sadrazamköy',
        'Motides',
        'Alsancak',
        'Myrtou',
        'Çamlıbel',
        'Oga',
        'Kayalar',
        'Paleosofos',
        'Malatya',
        'Panagra',
        'Geçitköy',
        'Pano Dikomo',
        'Yukarıdikmen/Yukarı Dikmen',
        'Pentadaktylos',
        'Beşparmaklar/Beşparmak Dağları',
        'Pileri',
        'Göçeri',
        'Sikhari',
        'Aşağıtaşkent/Aşağı Taşkent',
        'Sysklipos',
        'Akçiçek',
        'Templos',
        'Zeytinlik',
        'Thermia',
        'Doğanköy',
        'Trapeza',
        'Beşparmak',
        'Trimithi',
        'Edremit',
        'Vasilia',
        'Karşıyaka',
        'Vouno',
        'Yukarıtaşkent/Yukarı Taşkent',
        'Larnaca',
        'Limassol',
        'Mandria',
        'Sotira',
        'Nicosia',
        'Agia',
        'Dilekkaya',
        'Agia Marina',
        'Gürpınar',
        'Agios Vasillios',
        'Türkeli',
        'Ammadies',
        'Süleymaniye',
        'Ampelikou',
        'Bağlıköy',
        'Angolemi',
        'Taşpınar',
        'Argaki',
        'Akçay',
        'Avlona',
        'Gayretköy',
        'Beykoy',
        'Beyköy',
        'Elia',
        'Doğancı',
        'Epichio',
        'Cihangir',
        'Exo Metochi',
        'Düzova',
        'Fyllia',
        'Serhatköy',
        'Galini',
        'Ömerli',
        'Gerolakkos',
        'Alayköy',
        'Kalo Chorio',
        'Çamlıköy',
        'Kalo Chorio (Kapouti]',
        'Kalkanlı',
        'Kalyvakia',
        'Kalavaç',
        'Kanli',
        'Kanlıköy',
        'Kato Kopia',
        'Zümrütköy',
        'Kato Zodia',
        'Aşağıbostancı/Aşağı Bostancı',
        'Kazivera',
        'Gaziveran',
        'Kioneli',
        'Gönyeli',
        'Kokkina',
        'Erenköy',
        'Kourou Monastiri',
        'Kuru Manastır/Çukurova',
        'Kyra',
        'Mevlevi',
        'Kythrea',
        'Değirmenlik',
        'Lefka',
        'Lefke',
        'Louroukina',
        'Akıncılar/Lurucina',
        'Loutros',
        'Bademliköy',
        'Limnitis',
        'Yeşilırmak',
        'Mandres',
        'Hamitköy',
        'Masari',
        'Şahinler',
        'Mia Milia',
        'Haspolat',
        'Mora',
        'Meriç',
        'Morfou',
        'Güzelyurt/Omorfo',
        'Neo Chorio',
        'Minareliköy',
        'Nikitas',
        'Güneşköy',
        'Ortakoy',
        'Ortaköy',
        'Palekythro',
        'Balıkesir',
        'Pano Zodia',
        'Yukarıbostancı/Yukarı Bostancı',
        'Pentagia',
        'Yeşilyurt',
        'Peristeronari',
        'Cengizköy',
        'Petra',
        'Taşköy',
        'Petra tou Digeni',
        'Yeniceköy',
        'Potamos tou',
        'Kampou',
        'Yedidalga',
        'Prastio',
        'Aydınköy',
        'Pyrogi',
        'Gaziler',
        'Skylloura',
        'Yılmazköy',
        'Syrianochori',
        'Yayla',
        'Trachoni',
        'Demirhan',
        'Tymvou',
        'Kırklar',
        'Tymvou Airport',
        'Ercan Havaalani',
        'Voni',
        'Gökhan',
        'Xeros',
        'Gemikonağı',
        'Xerovounos',
        'Yukarıyeşilırmak',
        'Paphos',
        'Mandria', ]],
];
