<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class IndustriesTableSeeder extends Seeder
{
    private $insert;

    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now()->format('Y-m-d H:i:s');

        \DB::table('industries')->delete();

        $this->insert = \DB::table('industries')->insert([
            0 => [
                    'id' => 1,
                    'parent_id' => 0,
                    'name' => 'Agriculture, Fishing & Forestry',
                    'color' => '#1b9bd7',
                    'icon' => 'fal fa-money-bill',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            1 => [
                    'id' => 2,
                    'parent_id' => 0,
                    'name' => 'Construction & Renovation',
                    'color' => '#46cd93',
                    'icon' => 'fal fa-shopping-cart',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            2 => [
                    'id' => 3,
                    'parent_id' => 0,
                    'name' => 'Accounting & Finance',
                    'color' => '#fdba45',
                    'icon' => 'fal fa-box-full',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            3 => [
                    'id' => 4,
                    'parent_id' => 0,
                    'name' => 'Health & Medical',
                    'color' => '#0f1f3e',
                    'icon' => 'far fa-farm',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            4 => [
                    'id' => 5,
                    'parent_id' => 0,
                    'name' => 'Transportation',
                    'color' => '#4bbbce',
                    'icon' => 'fal fa-utensils-alt',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            5 => [
                    'id' => 6,
                    'parent_id' => 0,
                    'name' => 'Communications & Electronics',
                    'color' => '#e66793',
                    'icon' => 'fad fa-taco',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            6 => [
                    'id' => 7,
                    'parent_id' => 0,
                    'name' => 'Home & Garden',
                    'color' => '#1b9bd7',
                    'icon' => 'far fa-building',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            7 => [
                    'id' => 8,
                    'parent_id' => 0,
                    'name' => 'Apparel & Accessories',
                    'color' => '#46cd93',
                    'icon' => 'fal fa-candy-corn',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            8 => [
                    'id' => 9,
                    'parent_id' => 0,
                    'name' => 'Sports & Recreation',
                    'color' => '#fdba45',
                    'icon' => 'far fa-tennis-ball',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            9 => [
                    'id' => 10,
                    'parent_id' => 0,
                    'name' => 'Food & Beverages',
                    'color' => '#0f1f3e',
                    'icon' => 'fas fa-cloud-meatball',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            10 => [
                    'id' => 11,
                    'parent_id' => 0,
                    'name' => 'Education',
                    'color' => '#4bbbce',
                    'icon' => 'fad fa-school',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            11 => [
                    'id' => 12,
                    'parent_id' => 0,
                    'name' => 'Entertainment & Media',
                    'color' => '#e66793',
                    'icon' => 'fas fa-photo-video',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            12 => [
                    'id' => 13,
                    'parent_id' => 0,
                    'name' => 'Industrial Supplies & Services',
                    'color' => '#1b9bd7',
                    'icon' => 'fas fa-industry',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            13 => [
                    'id' => 14,
                    'parent_id' => 0,
                    'name' => 'Personal Care',
                    'color' => '#46cd93',
                    'icon' => 'far fa-user-secret',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            14 => [
                    'id' => 15,
                    'parent_id' => 0,
                    'name' => 'Real-Estate & Insurance',
                    'color' => '#fdba45',
                    'icon' => 'fal fa-hospitals',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            15 => [
                    'id' => 16,
                    'parent_id' => 0,
                    'name' => 'Retail & Shopping',
                    'color' => '#1bd74cbd',
                    'icon' => 'far fa-store',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            16 => [
                    'id' => 17,
                    'parent_id' => 0,
                    'name' => 'Automotive',
                    'color' => '#0f1f3e',
                    'icon' => 'fas fa-tachometer-fast',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            17 => [
                    'id' => 18,
                    'parent_id' => 0,
                    'name' => 'Travel & Lodging',
                    'color' => '#4bbbce',
                    'icon' => 'fad fa-transporter-2',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            18 => [
                    'id' => 19,
                    'parent_id' => 0,
                    'name' => 'Family & Community',
                    'color' => '#e66793',
                    'icon' => 'fad fa-house',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            19 => [
                    'id' => 20,
                    'parent_id' => 1,
                    'name' => 'Farming equipment & services',
                    'color' => '#1b9bd7',
                    'icon' => 'fal fa-money-bill',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            20 => [
                    'id' => 21,
                    'parent_id' => 1,
                    'name' => 'Soil',
                    'color' => '#28a745',
                    'icon' => 'fal fa-shopping-cart',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            21 => [
                    'id' => 22,
                    'parent_id' => 1,
                    'name' => 'General supplies & services',
                    'color' => '#4bbbce',
                    'icon' => 'fal fa-box-full',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            22 => [
                    'id' => 23,
                    'parent_id' => 1,
                    'name' => 'Horses',
                    'color' => '#343a40',
                    'icon' => 'fab fa-sticker-mule',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            23 => [
                    'id' => 24,
                    'parent_id' => 1,
                    'name' => 'Vegetables & Fruits',
                    'color' => '#46cd93',
                    'icon' => 'fas fa-badge-check',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            24 => [
                    'id' => 25,
                    'parent_id' => 1,
                    'name' => 'Sugar Cane & Sugar Beets',
                    'color' => '#0f1f3e',
                    'icon' => 'fal fa-candy-corn',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            25 => [
                    'id' => 26,
                    'parent_id' => 1,
                    'name' => 'Dairy',
                    'color' => '#1b9bd7',
                    'icon' => 'fas fa-book',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            26 => [
                    'id' => 27,
                    'parent_id' => 1,
                    'name' => 'Poultry & Eggs',
                    'color' => '#28a745',
                    'icon' => 'fal fa-turkey',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            27 => [
                    'id' => 28,
                    'parent_id' => 1,
                    'name' => 'Forestry & Forest',
                    'color' => '#fdba45',
                    'icon' => 'fal fa-utensils-alt',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            28 => [
                    'id' => 29,
                    'parent_id' => 1,
                    'name' => 'Livestock',
                    'color' => '#343a40',
                    'icon' => 'fal fa-money-bill',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            29 => [
                    'id' => 30,
                    'parent_id' => 1,
                    'name' => 'Food Processing',
                    'color' => '#46cd93',
                    'icon' => 'far fa-stocking',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            30 => [
                    'id' => 31,
                    'parent_id' => 1,
                    'name' => 'Tobacco',
                    'color' => '#fdba45',
                    'icon' => 'fad fa-taco',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            31 => [
                    'id' => 32,
                    'parent_id' => 1,
                    'name' => 'Farm Bureaus',
                    'color' => '#46cd93',
                    'icon' => 'far fa-farm',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            32 => [
                    'id' => 33,
                    'parent_id' => 2,
                    'name' => 'Building Materials & Equipment',
                    'color' => '#495057',
                    'icon' => 'far fa-building',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            33 => [
                    'id' => 34,
                    'parent_id' => 2,
                    'name' => 'Floors, Ceilings & Roofs',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            34 => [
                    'id' => 35,
                    'parent_id' => 2,
                    'name' => 'Plumbing & Piping',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            35 => [
                    'id' => 36,
                    'parent_id' => 2,
                    'name' => 'Contractor Equipment & Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            36 => [
                    'id' => 37,
                    'parent_id' => 2,
                    'name' => 'Architectural Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            37 => [
                    'id' => 38,
                    'parent_id' => 2,
                    'name' => 'Home Builders',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            38 => [
                    'id' => 39,
                    'parent_id' => 2,
                    'name' => 'General Contractors',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            39 => [
                    'id' => 40,
                    'parent_id' => 2,
                    'name' => 'Hardware - Supplies & Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            40 => [
                    'id' => 41,
                    'parent_id' => 3,
                    'name' => 'Accounting Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            41 => [
                    'id' => 42,
                    'parent_id' => 3,
                    'name' => 'Loans & Credit Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            42 => [
                    'id' => 43,
                    'parent_id' => 3,
                    'name' => 'Taxes',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            43 => [
                    'id' => 44,
                    'parent_id' => 3,
                    'name' => 'Banks & Financial Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            44 => [
                    'id' => 45,
                    'parent_id' => 3,
                    'name' => 'Retirement & Financial Planning',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            45 => [
                    'id' => 46,
                    'parent_id' => 3,
                    'name' => 'Legal',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            46 => [
                    'id' => 47,
                    'parent_id' => 3,
                    'name' => 'Commercial Banks',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            47 => [
                    'id' => 48,
                    'parent_id' => 3,
                    'name' => 'Credit Unions',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            48 => [
                    'id' => 49,
                    'parent_id' => 3,
                    'name' => 'Securities & Investment',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            49 => [
                    'id' => 50,
                    'parent_id' => 3,
                    'name' => 'Insurance',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            50 => [
                    'id' => 51,
                    'parent_id' => 3,
                    'name' => 'Misc Finance',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            51 => [
                    'id' => 52,
                    'parent_id' => 4,
                    'name' => 'Dental Care',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            52 => [
                    'id' => 53,
                    'parent_id' => 4,
                    'name' => 'Medical Products & Equipment',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            53 => [
                    'id' => 54,
                    'parent_id' => 4,
                    'name' => 'Hearing Care',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            54 => [
                    'id' => 55,
                    'parent_id' => 4,
                    'name' => 'Eye Care & Eyewear',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            55 => [
                    'id' => 56,
                    'parent_id' => 4,
                    'name' => 'Fitness & Weight Loss',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            56 => [
                    'id' => 57,
                    'parent_id' => 4,
                    'name' => 'Hospitals & Clinics',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            57 => [
                    'id' => 58,
                    'parent_id' => 4,
                    'name' => 'Health Practitioners & Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            58 => [
                    'id' => 59,
                    'parent_id' => 4,
                    'name' => 'Doctors',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            59 => [
                    'id' => 60,
                    'parent_id' => 4,
                    'name' => 'Pharmaceuticals / Health Products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            60 => [
                    'id' => 61,
                    'parent_id' => 4,
                    'name' => 'Nutritional & Dietary Supplements',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            61 => [
                    'id' => 62,
                    'parent_id' => 4,
                    'name' => 'Pharmacies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            62 => [
                    'id' => 63,
                    'parent_id' => 4,
                    'name' => 'Health Care',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            63 => [
                    'id' => 64,
                    'parent_id' => 4,
                    'name' => 'Oral Care',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            64 => [
                    'id' => 65,
                    'parent_id' => 4,
                    'name' => 'Beauty & Personal Care',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            65 => [
                    'id' => 66,
                    'parent_id' => 4,
                    'name' => 'Sexual Wellness',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            66 => [
                    'id' => 67,
                    'parent_id' => 4,
                    'name' => 'Sports Nutrition',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            67 => [
                    'id' => 68,
                    'parent_id' => 5,
                    'name' => 'Boats & marine',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            68 => [
                    'id' => 69,
                    'parent_id' => 5,
                    'name' => 'Trucking & freight',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            69 => [
                    'id' => 70,
                    'parent_id' => 5,
                    'name' => 'Special transportations services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            70 => [
                    'id' => 71,
                    'parent_id' => 5,
                    'name' => 'Air Transport',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            71 => [
                    'id' => 72,
                    'parent_id' => 5,
                    'name' => 'Automotive',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            72 => [
                    'id' => 73,
                    'parent_id' => 5,
                    'name' => 'Car Dealers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            73 => [
                    'id' => 74,
                    'parent_id' => 5,
                    'name' => 'Auto Manufacturers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            74 => [
                    'id' => 75,
                    'parent_id' => 5,
                    'name' => 'Sea Transport',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            75 => [
                    'id' => 76,
                    'parent_id' => 5,
                    'name' => 'Bike Dealers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            76 => [
                    'id' => 77,
                    'parent_id' => 6,
                    'name' => 'Communications Services & Equipment',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            77 => [
                    'id' => 78,
                    'parent_id' => 6,
                    'name' => 'Electronics - Services & Equipment',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            78 => [
                    'id' => 79,
                    'parent_id' => 6,
                    'name' => 'Computer Equipment',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            79 => [
                    'id' => 80,
                    'parent_id' => 6,
                    'name' => 'Computer Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            80 => [
                    'id' => 81,
                    'parent_id' => 6,
                    'name' => 'Internet',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            81 => [
                    'id' => 82,
                    'parent_id' => 6,
                    'name' => 'Printing & Publishing',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            82 => [
                    'id' => 83,
                    'parent_id' => 6,
                    'name' => 'TV / Movies / Music',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            83 => [
                    'id' => 84,
                    'parent_id' => 6,
                    'name' => 'Books, Magazines & Newspapers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            84 => [
                    'id' => 85,
                    'parent_id' => 6,
                    'name' => 'Cable & Satellite TV Production & Distribution',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            85 => [
                    'id' => 86,
                    'parent_id' => 6,
                    'name' => 'Telecom Services & Equipment',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            86 => [
                    'id' => 87,
                    'parent_id' => 6,
                    'name' => 'Mobile Phones',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            87 => [
                    'id' => 88,
                    'parent_id' => 6,
                    'name' => 'Accessories',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            88 => [
                    'id' => 89,
                    'parent_id' => 7,
                    'name' => 'Appliances',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            89 => [
                    'id' => 90,
                    'parent_id' => 7,
                    'name' => 'Furniture',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            90 => [
                    'id' => 91,
                    'parent_id' => 7,
                    'name' => 'Heating',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            91 => [
                    'id' => 92,
                    'parent_id' => 7,
                    'name' => 'Outdoor Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            92 => [
                    'id' => 93,
                    'parent_id' => 7,
                    'name' => 'Cooling & Ventilating',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            93 => [
                    'id' => 94,
                    'parent_id' => 7,
                    'name' => 'Garden & Lawn',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            94 => [
                    'id' => 95,
                    'parent_id' => 7,
                    'name' => 'Moving & Storage',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            95 => [
                    'id' => 96,
                    'parent_id' => 7,
                    'name' => 'Windows',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            96 => [
                    'id' => 97,
                    'parent_id' => 7,
                    'name' => 'Kitchen,Dining & Bar',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            97 => [
                    'id' => 98,
                    'parent_id' => 7,
                    'name' => 'Home Decor',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            98 => [
                    'id' => 99,
                    'parent_id' => 7,
                    'name' => 'Home Textile',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            99 => [
                    'id' => 100,
                    'parent_id' => 7,
                    'name' => 'Arts,Crafts & Sewing',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            100 => [
                    'id' => 101,
                    'parent_id' => 7,
                    'name' => 'Festive & Party Supplies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            101 => [
                    'id' => 102,
                    'parent_id' => 7,
                    'name' => 'Home Storage & Organization',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            102 => [
                    'id' => 103,
                    'parent_id' => 7,
                    'name' => 'Bathroom Products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            103 => [
                    'id' => 104,
                    'parent_id' => 7,
                    'name' => 'Household Cleaning',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            104 => [
                    'id' => 105,
                    'parent_id' => 7,
                    'name' => 'Pet Products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            105 => [
                    'id' => 106,
                    'parent_id' => 7,
                    'name' => 'Household Merchandises',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            106 => [
                    'id' => 107,
                    'parent_id' => 8,
                    'name' => 'Alterations & Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            107 => [
                    'id' => 108,
                    'parent_id' => 8,
                    'name' => 'Clothing Stores',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            108 => [
                    'id' => 109,
                    'parent_id' => 8,
                    'name' => 'Footwear',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            109 => [
                    'id' => 110,
                    'parent_id' => 8,
                    'name' => 'Jewellery',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            110 => [
                    'id' => 111,
                    'parent_id' => 8,
                    'name' => 'Watches',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            111 => [
                    'id' => 112,
                    'parent_id' => 8,
                    'name' => 'Hand Bags',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            112 => [
                    'id' => 113,
                    'parent_id' => 8,
                    'name' => 'Women\'s Fashion',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            113 => [
                    'id' => 114,
                    'parent_id' => 8,
                    'name' => 'Men\'s Fashion',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            114 => [
                    'id' => 115,
                    'parent_id' => 8,
                    'name' => 'Girls\' Fashion',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            115 => [
                    'id' => 116,
                    'parent_id' => 8,
                    'name' => 'Boys\' Fashion',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            116 => [
                    'id' => 117,
                    'parent_id' => 8,
                    'name' => 'Uniforms',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            117 => [
                    'id' => 118,
                    'parent_id' => 8,
                    'name' => 'Costumes & Accessories',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            118 => [
                    'id' => 119,
                    'parent_id' => 8,
                    'name' => 'Undergarments',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            119 => [
                    'id' => 120,
                    'parent_id' => 8,
                    'name' => 'Sleepwears',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            120 => [
                    'id' => 121,
                    'parent_id' => 8,
                    'name' => 'Luggage & Bags',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            121 => [
                    'id' => 122,
                    'parent_id' => 9,
                    'name' => 'Associations & Clubs',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            122 => [
                    'id' => 123,
                    'parent_id' => 9,
                    'name' => 'Boats & Watersports',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            123 => [
                    'id' => 124,
                    'parent_id' => 9,
                    'name' => 'Golf',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            124 => [
                    'id' => 125,
                    'parent_id' => 9,
                    'name' => 'Individual Sports',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            125 => [
                    'id' => 126,
                    'parent_id' => 9,
                    'name' => 'Bicycles',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            126 => [
                    'id' => 127,
                    'parent_id' => 9,
                    'name' => 'Camping',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            127 => [
                    'id' => 128,
                    'parent_id' => 9,
                    'name' => 'Parks & Recreation Centres',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            128 => [
                    'id' => 129,
                    'parent_id' => 9,
                    'name' => 'Sporting Goods',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            129 => [
                    'id' => 130,
                    'parent_id' => 9,
                    'name' => 'Sneakers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            130 => [
                    'id' => 131,
                    'parent_id' => 9,
                    'name' => 'Fishing',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            131 => [
                    'id' => 132,
                    'parent_id' => 9,
                    'name' => 'Swimming',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            132 => [
                    'id' => 133,
                    'parent_id' => 9,
                    'name' => 'Musical Instruments',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            133 => [
                    'id' => 134,
                    'parent_id' => 9,
                    'name' => 'Hunting',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            134 => [
                    'id' => 135,
                    'parent_id' => 9,
                    'name' => 'Fitness & Body Building',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            135 => [
                    'id' => 136,
                    'parent_id' => 9,
                    'name' => 'Water Sports',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            136 => [
                    'id' => 137,
                    'parent_id' => 9,
                    'name' => 'Team Sports',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            137 => [
                    'id' => 138,
                    'parent_id' => 9,
                    'name' => 'Racquet Sports',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            138 => [
                    'id' => 139,
                    'parent_id' => 9,
                    'name' => 'Running',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            139 => [
                    'id' => 140,
                    'parent_id' => 9,
                    'name' => 'Shooting',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            140 => [
                    'id' => 141,
                    'parent_id' => 9,
                    'name' => 'Skiing & Snowboarding',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            141 => [
                    'id' => 142,
                    'parent_id' => 9,
                    'name' => 'Sports Accessories',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            142 => [
                    'id' => 143,
                    'parent_id' => 9,
                    'name' => 'Roller Skates, Skateboards & Scooters',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            143 => [
                    'id' => 144,
                    'parent_id' => 9,
                    'name' => 'Horse Racing',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            144 => [
                    'id' => 145,
                    'parent_id' => 9,
                    'name' => 'Bowling',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            145 => [
                    'id' => 146,
                    'parent_id' => 9,
                    'name' => 'Other Sports & Entertainment',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            146 => [
                    'id' => 147,
                    'parent_id' => 9,
                    'name' => 'Sports Bags',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            147 => [
                    'id' => 148,
                    'parent_id' => 10,
                    'name' => 'Desserts & Bakery',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            148 => [
                    'id' => 149,
                    'parent_id' => 10,
                    'name' => 'Restaurants & Hotels',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            149 => [
                    'id' => 150,
                    'parent_id' => 10,
                    'name' => 'Food Services & Supplies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            150 => [
                    'id' => 151,
                    'parent_id' => 10,
                    'name' => 'Food Products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            151 => [
                    'id' => 152,
                    'parent_id' => 10,
                    'name' => 'Food Stores',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            152 => [
                    'id' => 153,
                    'parent_id' => 10,
                    'name' => 'Meat & Fish',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            153 => [
                    'id' => 154,
                    'parent_id' => 10,
                    'name' => 'Dairy Products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            154 => [
                    'id' => 155,
                    'parent_id' => 10,
                    'name' => 'Frozen products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            155 => [
                    'id' => 156,
                    'parent_id' => 10,
                    'name' => 'Bars',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            156 => [
                    'id' => 157,
                    'parent_id' => 10,
                    'name' => 'Cafes',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            157 => [
                    'id' => 158,
                    'parent_id' => 11,
                    'name' => 'Universities',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            158 => [
                    'id' => 159,
                    'parent_id' => 11,
                    'name' => 'School & Educational Supplies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            159 => [
                    'id' => 160,
                    'parent_id' => 11,
                    'name' => 'Stationary',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            160 => [
                    'id' => 161,
                    'parent_id' => 11,
                    'name' => 'Art Supplies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            161 => [
                    'id' => 162,
                    'parent_id' => 11,
                    'name' => 'Books, Magazines & Newspapers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            162 => [
                    'id' => 163,
                    'parent_id' => 12,
                    'name' => 'Music',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            163 => [
                    'id' => 164,
                    'parent_id' => 12,
                    'name' => 'Night Life',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            164 => [
                    'id' => 165,
                    'parent_id' => 12,
                    'name' => 'Games, Hobbies & Parties',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            165 => [
                    'id' => 166,
                    'parent_id' => 12,
                    'name' => 'Video, Movies & Television',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            166 => [
                    'id' => 167,
                    'parent_id' => 13,
                    'name' => 'Food & Beverages',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            167 => [
                    'id' => 168,
                    'parent_id' => 13,
                    'name' => 'Minerals',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            168 => [
                    'id' => 169,
                    'parent_id' => 13,
                    'name' => 'Laboratories',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            169 => [
                    'id' => 170,
                    'parent_id' => 13,
                    'name' => 'Metals, metals working & metals products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            170 => [
                    'id' => 171,
                    'parent_id' => 13,
                    'name' => 'Oil, coal, fuels & natural gases',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            171 => [
                    'id' => 172,
                    'parent_id' => 14,
                    'name' => 'Barbers, Beauty Salons & Spas',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            172 => [
                    'id' => 173,
                    'parent_id' => 14,
                    'name' => 'Skin & scalp services & products',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            173 => [
                    'id' => 174,
                    'parent_id' => 15,
                    'name' => 'Building Management',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            174 => [
                    'id' => 175,
                    'parent_id' => 15,
                    'name' => 'Insurance',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            175 => [
                    'id' => 176,
                    'parent_id' => 15,
                    'name' => 'Real Estate',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            176 => [
                    'id' => 177,
                    'parent_id' => 16,
                    'name' => 'Convenience Stores',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            177 => [
                    'id' => 178,
                    'parent_id' => 16,
                    'name' => 'Grocery Stores',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            178 => [
                    'id' => 179,
                    'parent_id' => 16,
                    'name' => 'Specialty retailers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            179 => [
                    'id' => 180,
                    'parent_id' => 16,
                    'name' => 'Home furnishing retailers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            180 => [
                    'id' => 181,
                    'parent_id' => 16,
                    'name' => 'Department Stores',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            181 => [
                    'id' => 182,
                    'parent_id' => 16,
                    'name' => 'Super Markets and Hyper Markets',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            182 => [
                    'id' => 183,
                    'parent_id' => 16,
                    'name' => 'Multichannel Stores',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            183 => [
                    'id' => 184,
                    'parent_id' => 16,
                    'name' => 'Apparel & Accessories',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            184 => [
                    'id' => 185,
                    'parent_id' => 16,
                    'name' => 'Gifts & Novelty',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            185 => [
                    'id' => 186,
                    'parent_id' => 16,
                    'name' => 'Stores - General',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            186 => [
                    'id' => 187,
                    'parent_id' => 16,
                    'name' => 'Books',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            187 => [
                    'id' => 188,
                    'parent_id' => 16,
                    'name' => 'Florists',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            188 => [
                    'id' => 189,
                    'parent_id' => 16,
                    'name' => 'Toys & Games',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            189 => [
                    'id' => 190,
                    'parent_id' => 16,
                    'name' => 'Party Supplies & Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            190 => [
                    'id' => 191,
                    'parent_id' => 16,
                    'name' => 'Discount, Used & Rental Goods',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            191 => [
                    'id' => 192,
                    'parent_id' => 17,
                    'name' => 'New & Used Dealers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            192 => [
                    'id' => 193,
                    'parent_id' => 17,
                    'name' => 'Repairs - Mechanical',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            193 => [
                    'id' => 194,
                    'parent_id' => 17,
                    'name' => 'Parts & Supplies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            194 => [
                    'id' => 195,
                    'parent_id' => 18,
                    'name' => 'Shipping, Packaging & Postal Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            195 => [
                    'id' => 196,
                    'parent_id' => 18,
                    'name' => 'Lodging',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            196 => [
                    'id' => 197,
                    'parent_id' => 18,
                    'name' => 'Transport',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            197 => [
                    'id' => 198,
                    'parent_id' => 19,
                    'name' => 'Travel Agencies, Clubs & Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            198 => [
                    'id' => 199,
                    'parent_id' => 19,
                    'name' => 'Children & Child Care',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            199 => [
                    'id' => 200,
                    'parent_id' => 19,
                    'name' => 'Pet Supplies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            200 => [
                    'id' => 201,
                    'parent_id' => 19,
                    'name' => 'Pet Services',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            201 => [
                    'id' => 202,
                    'parent_id' => 19,
                    'name' => 'Community Services & Organizations',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            202 => [
                    'id' => 203,
                    'parent_id' => 4,
                    'name' => 'Insurances',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            203 => [
                    'id' => 204,
                    'parent_id' => 11,
                    'name' => 'Online Universities',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            204 => [
                    'id' => 205,
                    'parent_id' => 11,
                    'name' => 'Schools',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            205 => [
                    'id' => 206,
                    'parent_id' => 11,
                    'name' => 'Nurseries',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            206 => [
                    'id' => 207,
                    'parent_id' => 11,
                    'name' => 'Training Centers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            207 => [
                    'id' => 208,
                    'parent_id' => 11,
                    'name' => 'Language Institutes',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            208 => [
                    'id' => 209,
                    'parent_id' => 11,
                    'name' => 'After School Activities',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            209 => [
                    'id' => 210,
                    'parent_id' => 11,
                    'name' => 'Recruitment Agencies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            210 => [
                    'id' => 211,
                    'parent_id' => 11,
                    'name' => 'Music & Performing Arts',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            211 => [
                    'id' => 212,
                    'parent_id' => 11,
                    'name' => 'Sports & Fitness Clubs',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            212 => [
                    'id' => 213,
                    'parent_id' => 11,
                    'name' => 'Abroad Study',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            213 => [
                    'id' => 214,
                    'parent_id' => 11,
                    'name' => 'Government Agencies',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            214 => [
                    'id' => 215,
                    'parent_id' => 11,
                    'name' => 'Art Galleries',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            215 => [
                    'id' => 216,
                    'parent_id' => 11,
                    'name' => 'Education Suppliers',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
            216 => [
                    'id' => 217,
                    'parent_id' => 11,
                    'name' => 'Special Needs',
                    'color' => '',
                    'icon' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'deleted_at' => null,
                ],
        ]);
        $this->insert;
    }
}
