<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class CurrencyListTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run(): void
    {
        DB::table('currency_list')->delete();

        DB::table('currency_list')->insert([
            0 => [
                'id' => 1,
                'country' => 'Albania',
                'currency_list' => 'Leke',
                'code' => 'ALL',
                'symbol' => 'Lek',
            ],
            1 => [
                'id' => 2,
                'country' => 'America',
                'currency_list' => 'Dollars',
                'code' => 'USD',
                'symbol' => '$',
            ],
            2 => [
                'id' => 3,
                'country' => 'Afghanistan',
                'currency_list' => 'Afghanis',
                'code' => 'AFN',
                'symbol' => '?',
            ],
            3 => [
                'id' => 4,
                'country' => 'Argentina',
                'currency_list' => 'Pesos',
                'code' => 'ARS',
                'symbol' => '$',
            ],
            4 => [
                'id' => 5,
                'country' => 'Aruba',
                'currency_list' => 'Guilders',
                'code' => 'AWG',
                'symbol' => 'ƒ',
            ],
            5 => [
                'id' => 6,
                'country' => 'Australia',
                'currency_list' => 'Dollars',
                'code' => 'AUD',
                'symbol' => '$',
            ],
            6 => [
                'id' => 7,
                'country' => 'Azerbaijan',
                'currency_list' => 'New Manats',
                'code' => 'AZN',
                'symbol' => '???',
            ],
            7 => [
                'id' => 8,
                'country' => 'Bahamas',
                'currency_list' => 'Dollars',
                'code' => 'BSD',
                'symbol' => '$',
            ],
            8 => [
                'id' => 9,
                'country' => 'Barbados',
                'currency_list' => 'Dollars',
                'code' => 'BBD',
                'symbol' => '$',
            ],
            9 => [
                'id' => 10,
                'country' => 'Belarus',
                'currency_list' => 'Rubles',
                'code' => 'BYR',
                'symbol' => 'p.',
            ],
            10 => [
                'id' => 11,
                'country' => 'Belgium',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            11 => [
                'id' => 12,
                'country' => 'Beliz',
                'currency_list' => 'Dollars',
                'code' => 'BZD',
                'symbol' => 'BZ$',
            ],
            12 => [
                'id' => 13,
                'country' => 'Bermuda',
                'currency_list' => 'Dollars',
                'code' => 'BMD',
                'symbol' => '$',
            ],
            13 => [
                'id' => 14,
                'country' => 'Bolivia',
                'currency_list' => 'Bolivianos',
                'code' => 'BOB',
                'symbol' => '$b',
            ],
            14 => [
                'id' => 15,
                'country' => 'Bosnia and Herzegovina',
                'currency_list' => 'Convertible Marka',
                'code' => 'BAM',
                'symbol' => 'KM',
            ],
            15 => [
                'id' => 16,
                'country' => 'Botswana',
                'currency_list' => 'Pula',
                'code' => 'BWP',
                'symbol' => 'P',
            ],
            16 => [
                'id' => 17,
                'country' => 'Bulgaria',
                'currency_list' => 'Leva',
                'code' => 'BGN',
                'symbol' => '??',
            ],
            17 => [
                'id' => 18,
                'country' => 'Brazil',
                'currency_list' => 'Reais',
                'code' => 'BRL',
                'symbol' => 'R$',
            ],
            18 => [
                'id' => 19,
                'country' => 'Britain (United Kingdom)',
                'currency_list' => 'Pounds',
                'code' => 'GBP',
                'symbol' => '£',
            ],
            19 => [
                'id' => 20,
                'country' => 'Brunei Darussalam',
                'currency_list' => 'Dollars',
                'code' => 'BND',
                'symbol' => '$',
            ],
            20 => [
                'id' => 21,
                'country' => 'Cambodia',
                'currency_list' => 'Riels',
                'code' => 'KHR',
                'symbol' => '?',
            ],
            21 => [
                'id' => 22,
                'country' => 'Canada',
                'currency_list' => 'Dollars',
                'code' => 'CAD',
                'symbol' => '$',
            ],
            22 => [
                'id' => 23,
                'country' => 'Cayman Islands',
                'currency_list' => 'Dollars',
                'code' => 'KYD',
                'symbol' => '$',
            ],
            23 => [
                'id' => 24,
                'country' => 'Chile',
                'currency_list' => 'Pesos',
                'code' => 'CLP',
                'symbol' => '$',
            ],
            24 => [
                'id' => 25,
                'country' => 'China',
                'currency_list' => 'Yuan Renminbi',
                'code' => 'CNY',
                'symbol' => '¥',
            ],
            25 => [
                'id' => 26,
                'country' => 'Colombia',
                'currency_list' => 'Pesos',
                'code' => 'COP',
                'symbol' => '$',
            ],
            26 => [
                'id' => 27,
                'country' => 'Costa Rica',
                'currency_list' => 'Colón',
                'code' => 'CRC',
                'symbol' => '?',
            ],
            27 => [
                'id' => 28,
                'country' => 'Croatia',
                'currency_list' => 'Kuna',
                'code' => 'HRK',
                'symbol' => 'kn',
            ],
            28 => [
                'id' => 29,
                'country' => 'Cuba',
                'currency_list' => 'Pesos',
                'code' => 'CUP',
                'symbol' => '?',
            ],
            29 => [
                'id' => 30,
                'country' => 'Cyprus',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            30 => [
                'id' => 31,
                'country' => 'Czech Republic',
                'currency_list' => 'Koruny',
                'code' => 'CZK',
                'symbol' => 'K?',
            ],
            31 => [
                'id' => 32,
                'country' => 'Denmark',
                'currency_list' => 'Kroner',
                'code' => 'DKK',
                'symbol' => 'kr',
            ],
            32 => [
                'id' => 33,
                'country' => 'Dominican Republic',
                'currency_list' => 'Pesos',
                'code' => 'DOP ',
                'symbol' => 'RD$',
            ],
            33 => [
                'id' => 34,
                'country' => 'East Caribbean',
                'currency_list' => 'Dollars',
                'code' => 'XCD',
                'symbol' => '$',
            ],
            34 => [
                'id' => 35,
                'country' => 'Egypt',
                'currency_list' => 'Pounds',
                'code' => 'EGP',
                'symbol' => '£',
            ],
            35 => [
                'id' => 36,
                'country' => 'El Salvador',
                'currency_list' => 'Colones',
                'code' => 'SVC',
                'symbol' => '$',
            ],
            36 => [
                'id' => 37,
                'country' => 'England (United Kingdom)',
                'currency_list' => 'Pounds',
                'code' => 'GBP',
                'symbol' => '£',
            ],
            37 => [
                'id' => 38,
                'country' => 'Euro',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            38 => [
                'id' => 39,
                'country' => 'Falkland Islands',
                'currency_list' => 'Pounds',
                'code' => 'FKP',
                'symbol' => '£',
            ],
            39 => [
                'id' => 40,
                'country' => 'Fiji',
                'currency_list' => 'Dollars',
                'code' => 'FJD',
                'symbol' => '$',
            ],
            40 => [
                'id' => 41,
                'country' => 'France',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            41 => [
                'id' => 42,
                'country' => 'Ghana',
                'currency_list' => 'Cedis',
                'code' => 'GHC',
                'symbol' => '¢',
            ],
            42 => [
                'id' => 43,
                'country' => 'Gibraltar',
                'currency_list' => 'Pounds',
                'code' => 'GIP',
                'symbol' => '£',
            ],
            43 => [
                'id' => 44,
                'country' => 'Greece',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            44 => [
                'id' => 45,
                'country' => 'Guatemala',
                'currency_list' => 'Quetzales',
                'code' => 'GTQ',
                'symbol' => 'Q',
            ],
            45 => [
                'id' => 46,
                'country' => 'Guernsey',
                'currency_list' => 'Pounds',
                'code' => 'GGP',
                'symbol' => '£',
            ],
            46 => [
                'id' => 47,
                'country' => 'Guyana',
                'currency_list' => 'Dollars',
                'code' => 'GYD',
                'symbol' => '$',
            ],
            47 => [
                'id' => 48,
                'country' => 'Holland (Netherlands)',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            48 => [
                'id' => 49,
                'country' => 'Honduras',
                'currency_list' => 'Lempiras',
                'code' => 'HNL',
                'symbol' => 'L',
            ],
            49 => [
                'id' => 50,
                'country' => 'Hong Kong',
                'currency_list' => 'Dollars',
                'code' => 'HKD',
                'symbol' => '$',
            ],
            50 => [
                'id' => 51,
                'country' => 'Hungary',
                'currency_list' => 'Forint',
                'code' => 'HUF',
                'symbol' => 'Ft',
            ],
            51 => [
                'id' => 52,
                'country' => 'Iceland',
                'currency_list' => 'Kronur',
                'code' => 'ISK',
                'symbol' => 'kr',
            ],
            52 => [
                'id' => 53,
                'country' => 'India',
                'currency_list' => 'Rupees',
                'code' => 'INR',
                'symbol' => 'Rp',
            ],
            53 => [
                'id' => 54,
                'country' => 'Indonesia',
                'currency_list' => 'Rupiahs',
                'code' => 'IDR',
                'symbol' => 'Rp',
            ],
            54 => [
                'id' => 55,
                'country' => 'Iran',
                'currency_list' => 'Rials',
                'code' => 'IRR',
                'symbol' => '?',
            ],
            55 => [
                'id' => 56,
                'country' => 'Ireland',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            56 => [
                'id' => 57,
                'country' => 'Isle of Man',
                'currency_list' => 'Pounds',
                'code' => 'IMP',
                'symbol' => '£',
            ],
            57 => [
                'id' => 58,
                'country' => 'Israel',
                'currency_list' => 'New Shekels',
                'code' => 'ILS',
                'symbol' => '?',
            ],
            58 => [
                'id' => 59,
                'country' => 'Italy',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            59 => [
                'id' => 60,
                'country' => 'Jamaica',
                'currency_list' => 'Dollars',
                'code' => 'JMD',
                'symbol' => 'J$',
            ],
            60 => [
                'id' => 61,
                'country' => 'Japan',
                'currency_list' => 'Yen',
                'code' => 'JPY',
                'symbol' => '¥',
            ],
            61 => [
                'id' => 62,
                'country' => 'Jersey',
                'currency_list' => 'Pounds',
                'code' => 'JEP',
                'symbol' => '£',
            ],
            62 => [
                'id' => 63,
                'country' => 'Kazakhstan',
                'currency_list' => 'Tenge',
                'code' => 'KZT',
                'symbol' => '??',
            ],
            63 => [
                'id' => 64,
                'country' => 'Korea (North)',
                'currency_list' => 'Won',
                'code' => 'KPW',
                'symbol' => '?',
            ],
            64 => [
                'id' => 65,
                'country' => 'Korea (South)',
                'currency_list' => 'Won',
                'code' => 'KRW',
                'symbol' => '?',
            ],
            65 => [
                'id' => 66,
                'country' => 'Kyrgyzstan',
                'currency_list' => 'Soms',
                'code' => 'KGS',
                'symbol' => '??',
            ],
            66 => [
                'id' => 67,
                'country' => 'Laos',
                'currency_list' => 'Kips',
                'code' => 'LAK',
                'symbol' => '?',
            ],
            67 => [
                'id' => 68,
                'country' => 'Latvia',
                'currency_list' => 'Lati',
                'code' => 'LVL',
                'symbol' => 'Ls',
            ],
            68 => [
                'id' => 69,
                'country' => 'Lebanon',
                'currency_list' => 'Pounds',
                'code' => 'LBP',
                'symbol' => '£',
            ],
            69 => [
                'id' => 70,
                'country' => 'Liberia',
                'currency_list' => 'Dollars',
                'code' => 'LRD',
                'symbol' => '$',
            ],
            70 => [
                'id' => 71,
                'country' => 'Liechtenstein',
                'currency_list' => 'Switzerland Francs',
                'code' => 'CHF',
                'symbol' => 'CHF',
            ],
            71 => [
                'id' => 72,
                'country' => 'Lithuania',
                'currency_list' => 'Litai',
                'code' => 'LTL',
                'symbol' => 'Lt',
            ],
            72 => [
                'id' => 73,
                'country' => 'Luxembourg',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            73 => [
                'id' => 74,
                'country' => 'Macedonia',
                'currency_list' => 'Denars',
                'code' => 'MKD',
                'symbol' => '???',
            ],
            74 => [
                'id' => 75,
                'country' => 'Malaysia',
                'currency_list' => 'Ringgits',
                'code' => 'MYR',
                'symbol' => 'RM',
            ],
            75 => [
                'id' => 76,
                'country' => 'Malta',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            76 => [
                'id' => 77,
                'country' => 'Mauritius',
                'currency_list' => 'Rupees',
                'code' => 'MUR',
                'symbol' => '?',
            ],
            77 => [
                'id' => 78,
                'country' => 'Mexico',
                'currency_list' => 'Pesos',
                'code' => 'MXN',
                'symbol' => '$',
            ],
            78 => [
                'id' => 79,
                'country' => 'Mongolia',
                'currency_list' => 'Tugriks',
                'code' => 'MNT',
                'symbol' => '?',
            ],
            79 => [
                'id' => 80,
                'country' => 'Mozambique',
                'currency_list' => 'Meticais',
                'code' => 'MZN',
                'symbol' => 'MT',
            ],
            80 => [
                'id' => 81,
                'country' => 'Namibia',
                'currency_list' => 'Dollars',
                'code' => 'NAD',
                'symbol' => '$',
            ],
            81 => [
                'id' => 82,
                'country' => 'Nepal',
                'currency_list' => 'Rupees',
                'code' => 'NPR',
                'symbol' => '?',
            ],
            82 => [
                'id' => 83,
                'country' => 'Netherlands Antilles',
                'currency_list' => 'Guilders',
                'code' => 'ANG',
                'symbol' => 'ƒ',
            ],
            83 => [
                'id' => 84,
                'country' => 'Netherlands',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            84 => [
                'id' => 85,
                'country' => 'New Zealand',
                'currency_list' => 'Dollars',
                'code' => 'NZD',
                'symbol' => '$',
            ],
            85 => [
                'id' => 86,
                'country' => 'Nicaragua',
                'currency_list' => 'Cordobas',
                'code' => 'NIO',
                'symbol' => 'C$',
            ],
            86 => [
                'id' => 87,
                'country' => 'Nigeria',
                'currency_list' => 'Nairas',
                'code' => 'NGN',
                'symbol' => '?',
            ],
            87 => [
                'id' => 88,
                'country' => 'North Korea',
                'currency_list' => 'Won',
                'code' => 'KPW',
                'symbol' => '?',
            ],
            88 => [
                'id' => 89,
                'country' => 'Norway',
                'currency_list' => 'Krone',
                'code' => 'NOK',
                'symbol' => 'kr',
            ],
            89 => [
                'id' => 90,
                'country' => 'Oman',
                'currency_list' => 'Rials',
                'code' => 'OMR',
                'symbol' => '?',
            ],
            90 => [
                'id' => 91,
                'country' => 'Pakistan',
                'currency_list' => 'Rupees',
                'code' => 'PKR',
                'symbol' => '?',
            ],
            91 => [
                'id' => 92,
                'country' => 'Panama',
                'currency_list' => 'Balboa',
                'code' => 'PAB',
                'symbol' => 'B/.',
            ],
            92 => [
                'id' => 93,
                'country' => 'Paraguay',
                'currency_list' => 'Guarani',
                'code' => 'PYG',
                'symbol' => 'Gs',
            ],
            93 => [
                'id' => 94,
                'country' => 'Peru',
                'currency_list' => 'Nuevos Soles',
                'code' => 'PEN',
                'symbol' => 'S/.',
            ],
            94 => [
                'id' => 95,
                'country' => 'Philippines',
                'currency_list' => 'Pesos',
                'code' => 'PHP',
                'symbol' => 'Php',
            ],
            95 => [
                'id' => 96,
                'country' => 'Poland',
                'currency_list' => 'Zlotych',
                'code' => 'PLN',
                'symbol' => 'z?',
            ],
            96 => [
                'id' => 97,
                'country' => 'Qatar',
                'currency_list' => 'Rials',
                'code' => 'QAR',
                'symbol' => '?',
            ],
            97 => [
                'id' => 98,
                'country' => 'Romania',
                'currency_list' => 'New Lei',
                'code' => 'RON',
                'symbol' => 'lei',
            ],
            98 => [
                'id' => 99,
                'country' => 'Russia',
                'currency_list' => 'Rubles',
                'code' => 'RUB',
                'symbol' => '???',
            ],
            99 => [
                'id' => 100,
                'country' => 'Saint Helena',
                'currency_list' => 'Pounds',
                'code' => 'SHP',
                'symbol' => '£',
            ],
            100 => [
                'id' => 101,
                'country' => 'Saudi Arabia',
                'currency_list' => 'Riyals',
                'code' => 'SAR',
                'symbol' => '?',
            ],
            101 => [
                'id' => 102,
                'country' => 'Serbia',
                'currency_list' => 'Dinars',
                'code' => 'RSD',
                'symbol' => '???.',
            ],
            102 => [
                'id' => 103,
                'country' => 'Seychelles',
                'currency_list' => 'Rupees',
                'code' => 'SCR',
                'symbol' => '?',
            ],
            103 => [
                'id' => 104,
                'country' => 'Singapore',
                'currency_list' => 'Dollars',
                'code' => 'SGD',
                'symbol' => '$',
            ],
            104 => [
                'id' => 105,
                'country' => 'Slovenia',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            105 => [
                'id' => 106,
                'country' => 'Solomon Islands',
                'currency_list' => 'Dollars',
                'code' => 'SBD',
                'symbol' => '$',
            ],
            106 => [
                'id' => 107,
                'country' => 'Somalia',
                'currency_list' => 'Shillings',
                'code' => 'SOS',
                'symbol' => 'S',
            ],
            107 => [
                'id' => 108,
                'country' => 'South Africa',
                'currency_list' => 'Rand',
                'code' => 'ZAR',
                'symbol' => 'R',
            ],
            108 => [
                'id' => 109,
                'country' => 'South Korea',
                'currency_list' => 'Won',
                'code' => 'KRW',
                'symbol' => '?',
            ],
            109 => [
                'id' => 110,
                'country' => 'Spain',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            110 => [
                'id' => 111,
                'country' => 'Sri Lanka',
                'currency_list' => 'Rupees',
                'code' => 'LKR',
                'symbol' => '?',
            ],
            111 => [
                'id' => 112,
                'country' => 'Sweden',
                'currency_list' => 'Kronor',
                'code' => 'SEK',
                'symbol' => 'kr',
            ],
            112 => [
                'id' => 113,
                'country' => 'Switzerland',
                'currency_list' => 'Francs',
                'code' => 'CHF',
                'symbol' => 'CHF',
            ],
            113 => [
                'id' => 114,
                'country' => 'Suriname',
                'currency_list' => 'Dollars',
                'code' => 'SRD',
                'symbol' => '$',
            ],
            114 => [
                'id' => 115,
                'country' => 'Syria',
                'currency_list' => 'Pounds',
                'code' => 'SYP',
                'symbol' => '£',
            ],
            115 => [
                'id' => 116,
                'country' => 'Taiwan',
                'currency_list' => 'New Dollars',
                'code' => 'TWD',
                'symbol' => 'NT$',
            ],
            116 => [
                'id' => 117,
                'country' => 'Thailand',
                'currency_list' => 'Baht',
                'code' => 'THB',
                'symbol' => '?',
            ],
            117 => [
                'id' => 118,
                'country' => 'Trinidad and Tobago',
                'currency_list' => 'Dollars',
                'code' => 'TTD',
                'symbol' => 'TT$',
            ],
            118 => [
                'id' => 119,
                'country' => 'Turkey',
                'currency_list' => 'Lira',
                'code' => 'TRY',
                'symbol' => 'TL',
            ],
            119 => [
                'id' => 120,
                'country' => 'Turkey',
                'currency_list' => 'Liras',
                'code' => 'TRL',
                'symbol' => '£',
            ],
            120 => [
                'id' => 121,
                'country' => 'Tuvalu',
                'currency_list' => 'Dollars',
                'code' => 'TVD',
                'symbol' => '$',
            ],
            121 => [
                'id' => 122,
                'country' => 'Ukraine',
                'currency_list' => 'Hryvnia',
                'code' => 'UAH',
                'symbol' => '?',
            ],
            122 => [
                'id' => 123,
                'country' => 'United Kingdom',
                'currency_list' => 'Pounds',
                'code' => 'GBP',
                'symbol' => '£',
            ],
            123 => [
                'id' => 124,
                'country' => 'United States of America',
                'currency_list' => 'Dollars',
                'code' => 'USD',
                'symbol' => '$',
            ],
            124 => [
                'id' => 125,
                'country' => 'Uruguay',
                'currency_list' => 'Pesos',
                'code' => 'UYU',
                'symbol' => '$U',
            ],
            125 => [
                'id' => 126,
                'country' => 'Uzbekistan',
                'currency_list' => 'Sums',
                'code' => 'UZS',
                'symbol' => '??',
            ],
            126 => [
                'id' => 127,
                'country' => 'Vatican City',
                'currency_list' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
            ],
            127 => [
                'id' => 128,
                'country' => 'Venezuela',
                'currency_list' => 'Bolivares Fuertes',
                'code' => 'VEF',
                'symbol' => 'Bs',
            ],
            128 => [
                'id' => 129,
                'country' => 'Vietnam',
                'currency_list' => 'Dong',
                'code' => 'VND',
                'symbol' => '?',
            ],
            129 => [
                'id' => 130,
                'country' => 'Yemen',
                'currency_list' => 'Rials',
                'code' => 'YER',
                'symbol' => '?',
            ],
            130 => [
                'id' => 131,
                'country' => 'Zimbabwe',
                'currency_list' => 'Zimbabwe Dollars',
                'code' => 'ZWD',
                'symbol' => 'Z$',
            ],
        ]);
    }
}
