<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class InvoiceDownloadsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run(): void
    {
        DB::table('invoice_downloads')->delete();

        DB::table('invoice_downloads')->insert([
            0 => [
                'id' => 1,
                'inv_no' => '101',
                'order_id' => '1',
                'qty' => 1,
                'variant_id' => 1,
                'vender_id' => 1,
                'price' => 171.43,
                'discount' => 0.0,
                'tax_amount' => '8.57',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'canceled',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:05:03',
                'updated_at' => '2020-11-24 15:58:15',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'inv_no' => '101',
                'order_id' => '1',
                'qty' => 1,
                'variant_id' => 2,
                'vender_id' => 1,
                'price' => 410.0,
                'discount' => 0.0,
                'tax_amount' => null,
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'shipped',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:05:03',
                'updated_at' => '2020-11-24 15:58:48',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'inv_no' => '102',
                'order_id' => '2',
                'qty' => 1,
                'variant_id' => 2,
                'vender_id' => 1,
                'price' => 379.63,
                'discount' => 0.0,
                'tax_amount' => '30.37',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'shipped',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:23:08',
                'updated_at' => '2020-11-24 15:25:41',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'inv_no' => '102',
                'order_id' => '2',
                'qty' => 1,
                'variant_id' => 4,
                'vender_id' => 1,
                'price' => 711.86,
                'discount' => 0.0,
                'tax_amount' => '128.14',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'shipped',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:23:08',
                'updated_at' => '2020-11-24 15:25:40',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'inv_no' => '102',
                'order_id' => '2',
                'qty' => 1,
                'variant_id' => 1,
                'vender_id' => 1,
                'price' => 171.43,
                'discount' => 0.0,
                'tax_amount' => '8.57',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'delivered',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:23:08',
                'updated_at' => '2020-11-24 15:25:43',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'inv_no' => '103',
                'order_id' => '3',
                'qty' => 1,
                'variant_id' => 2,
                'vender_id' => 1,
                'price' => 379.63,
                'discount' => 0.0,
                'tax_amount' => '30.37',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'processed',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:23:52',
                'updated_at' => '2020-11-24 15:25:26',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            6 => [
                'id' => 7,
                'inv_no' => '103',
                'order_id' => '3',
                'qty' => 1,
                'variant_id' => 4,
                'vender_id' => 1,
                'price' => 711.86,
                'discount' => 0.0,
                'tax_amount' => '128.14',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'shipped',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:23:52',
                'updated_at' => '2020-11-24 15:25:28',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            7 => [
                'id' => 8,
                'inv_no' => '103',
                'order_id' => '3',
                'qty' => 1,
                'variant_id' => 1,
                'vender_id' => 1,
                'price' => 171.43,
                'discount' => 0.0,
                'tax_amount' => '8.57',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'pending',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:23:52',
                'updated_at' => '2020-11-24 15:23:52',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            8 => [
                'id' => 9,
                'inv_no' => '104',
                'order_id' => '4',
                'qty' => 1,
                'variant_id' => 2,
                'vender_id' => 1,
                'price' => 379.63,
                'discount' => 0.0,
                'tax_amount' => '30.37',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'delivered',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:24:15',
                'updated_at' => '2020-11-24 15:25:15',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            9 => [
                'id' => 10,
                'inv_no' => '104',
                'order_id' => '4',
                'qty' => 1,
                'variant_id' => 4,
                'vender_id' => 1,
                'price' => 711.86,
                'discount' => 0.0,
                'tax_amount' => '128.14',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'processed',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:24:15',
                'updated_at' => '2020-11-24 15:25:03',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
            10 => [
                'id' => 11,
                'inv_no' => '104',
                'order_id' => '4',
                'qty' => 1,
                'variant_id' => 1,
                'vender_id' => 1,
                'price' => 171.43,
                'discount' => 0.0,
                'tax_amount' => '8.57',
                'shipping' => '0',
                'handlingcharge' => 0.0,
                'status' => 'shipped',
                'local_pick' => null,
                'loc_deliv_date' => null,
                'created_at' => '2020-11-24 15:24:15',
                'updated_at' => '2020-11-24 15:25:05',
                'paid_to_seller' => 'YES',
                'igst' => 8.57,
                'sgst' => null,
                'cgst' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
