<?php

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run(): void
    {

        //\DB::table('courses')->delete();

        \DB::table('courses')->insert([
            0 => [
                'id' => 1,
                'title' => 'Business Management 1',
                'code' => 'BGEC100',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => 'Core',
            ],
            1 => [
                'id' => 2,
                'title' => 'Business Law',
                'code' => 'BGEC101',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => 'Elective',
            ],
            2 => [
                'id' => 3,
                'title' => 'Intro to Computer Skills',
                'code' => 'BGEC102',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            3 => [
                'id' => 4,
                'title' => 'Business Statisties',
                'code' => 'BGEC103',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            4 => [
                'id' => 5,
                'title' => 'Communication Skills',
                'code' => 'BGEC104',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            5 => [
                'id' => 6,
                'title' => 'Business Management 11',
                'code' => 'BGEC105',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            6 => [
                'id' => 7,
                'title' => 'Business Communication 1',
                'code' => 'BGEC106',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            7 => [
                'id' => 8,
                'title' => 'Intro to Organisation Behaviour',
                'code' => 'BGEC107',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            8 => [
                'id' => 9,
                'title' => 'Elements of Economics',
                'code' => 'BGEC108',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            9 => [
                'id' => 10,
                'title' => 'Principles of Marketing',
                'code' => 'BGEC109',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            10 => [
                'id' => 11,
                'title' => 'Business Communication  11',
                'code' => 'BGEC110',
                'credithours' => '3',
                'level' => 'Level 100',
                'program' => 'Degree',
                'type' => null,
            ],
            11 => [
                'id' => 12,
                'title' => 'Business Policy and Strategy 1',
                'code' => 'BCPC200',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => 'Core',
            ],
            12 => [
                'id' => 13,
                'title' => 'Business Finance',
                'code' => 'BCPC201',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => 'Core',
            ],
            13 => [
                'id' => 14,
                'title' => 'Entrepreneurship',
                'code' => 'BCPC202',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => 'Elective',
            ],
            14 => [
                'id' => 15,
                'title' => 'Economy of Ghana',
                'code' => 'BCPC203',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => null,
            ],
            15 => [
                'id' => 16,
                'title' => 'Company Law',
                'code' => 'BCPC204',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => null,
            ],
            16 => [
                'id' => 17,
                'title' => 'Business Policy and Strategy 11',
                'code' => 'BCPC205',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => null,
            ],
            17 => [
                'id' => 18,
                'title' => 'Marketing Planning',
                'code' => 'BCPC206',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => null,
            ],
            18 => [
                'id' => 19,
                'title' => 'Sales Management',
                'code' => 'BCPC207',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => null,
            ],
            19 => [
                'id' => 20,
                'title' => 'Marketing Research',
                'code' => 'BCPC208',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => null,
            ],
            20 => [
                'id' => 21,
                'title' => 'Human Resource Management',
                'code' => 'BCPC209',
                'credithours' => '3',
                'level' => 'Level 200',
                'program' => 'Degree',
                'type' => null,
            ],
            21 => [
                'id' => 22,
                'title' => 'Research Methods',
                'code' => 'BACT300',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => 'Core',
            ],
            22 => [
                'id' => 23,
                'title' => 'Enterpreneurship Development',
                'code' => 'BACT301',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => 'Elective',
            ],
            23 => [
                'id' => 24,
                'title' => 'Cost Accounting',
                'code' => 'BACT302',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => null,
            ],
            24 => [
                'id' => 25,
                'title' => 'Financial Reporting 1',
                'code' => 'BACT303',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => null,
            ],
            25 => [
                'id' => 26,
                'title' => 'Financial Reporting 2',
                'code' => 'BACT304',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => null,
            ],
            26 => [
                'id' => 27,
                'title' => 'Company and Partnership Law',
                'code' => 'BACT305',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => null,
            ],
            27 => [
                'id' => 28,
                'title' => 'Management Accounting',
                'code' => 'BACT306',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => null,
            ],
            28 => [
                'id' => 29,
                'title' => 'Taxation',
                'code' => 'BACT307',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => null,
            ],
            29 => [
                'id' => 30,
                'title' => 'Audit & Internal Review',
                'code' => 'BACT308',
                'credithours' => '3',
                'level' => 'Level 300',
                'program' => 'Degree',
                'type' => null,
            ],
            30 => [
                'id' => 31,
                'title' => 'Business Policy and Strategy',
                'code' => 'BBBA400',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => 'Core',
            ],
            31 => [
                'id' => 32,
                'title' => 'Coroperate Reporting 1',
                'code' => 'BBBA401',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => 'Elective',
            ],
            32 => [
                'id' => 33,
                'title' => 'Taxation & Fiscal Policy',
                'code' => 'BBBA402',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            33 => [
                'id' => 34,
                'title' => 'Project Work',
                'code' => 'BBBA403',
                'credithours' => '6',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            34 => [
                'id' => 35,
                'title' => 'Internship',
                'code' => 'BBBA404',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            35 => [
                'id' => 36,
                'title' => 'Information Management',
                'code' => 'BBBA405',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            36 => [
                'id' => 37,
                'title' => 'Software Quality Management',
                'code' => 'BBBA406',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            37 => [
                'id' => 38,
                'title' => 'Electronic Business',
                'code' => 'BBBA407',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            38 => [
                'id' => 39,
                'title' => 'Mobile Web Development',
                'code' => 'BBBA408',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            39 => [
                'id' => 40,
                'title' => 'computer & Network Security',
                'code' => 'BBBA409',
                'credithours' => '3',
                'level' => 'Level 400',
                'program' => 'Degree',
                'type' => null,
            ],
            40 => [
                'id' => 41,
                'title' => 'Business Management Diploma',
                'code' => 'PDBA111',
                'credithours' => '2',
                'level' => 'Level 100',
                'program' => 'Diploma',
                'type' => null,
            ],
        ]);
    }
}
