<?php

use Illuminate\Database\Seeder;

class MenupermissionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run(): void
    {

       // \DB::table('menupermissions')->delete();

        \DB::table('menupermissions')->insert([
            0 => [
                'id' => 6,
                'sub_menu_id' => '2',
                'menu_id' => '1',
                'permission_id' => '6',
            ],
            1 => [
                'id' => 7,
                'sub_menu_id' => '2',
                'menu_id' => '1',
                'permission_id' => '7',
            ],
            2 => [
                'id' => 8,
                'sub_menu_id' => '2',
                'menu_id' => '1',
                'permission_id' => '8',
            ],
            3 => [
                'id' => 9,
                'sub_menu_id' => '2',
                'menu_id' => '1',
                'permission_id' => '9',
            ],
            4 => [
                'id' => 10,
                'sub_menu_id' => '2',
                'menu_id' => '1',
                'permission_id' => '10',
            ],
            5 => [
                'id' => 11,
                'sub_menu_id' => '3',
                'menu_id' => '2',
                'permission_id' => '11',
            ],
            6 => [
                'id' => 12,
                'sub_menu_id' => '3',
                'menu_id' => '2',
                'permission_id' => '12',
            ],
            7 => [
                'id' => 13,
                'sub_menu_id' => '3',
                'menu_id' => '2',
                'permission_id' => '13',
            ],
            8 => [
                'id' => 14,
                'sub_menu_id' => '3',
                'menu_id' => '2',
                'permission_id' => '14',
            ],
            9 => [
                'id' => 15,
                'sub_menu_id' => '4',
                'menu_id' => '3',
                'permission_id' => '15',
            ],
            10 => [
                'id' => 16,
                'sub_menu_id' => '4',
                'menu_id' => '3',
                'permission_id' => '16',
            ],
            11 => [
                'id' => 17,
                'sub_menu_id' => '4',
                'menu_id' => '3',
                'permission_id' => '17',
            ],
            12 => [
                'id' => 18,
                'sub_menu_id' => '4',
                'menu_id' => '3',
                'permission_id' => '18',
            ],
            13 => [
                'id' => 19,
                'sub_menu_id' => '5',
                'menu_id' => '4',
                'permission_id' => '19',
            ],
            14 => [
                'id' => 20,
                'sub_menu_id' => '5',
                'menu_id' => '4',
                'permission_id' => '20',
            ],
            15 => [
                'id' => 21,
                'sub_menu_id' => '5',
                'menu_id' => '4',
                'permission_id' => '21',
            ],
            16 => [
                'id' => 22,
                'sub_menu_id' => '5',
                'menu_id' => '4',
                'permission_id' => '22',
            ],
            17 => [
                'id' => 23,
                'sub_menu_id' => '6',
                'menu_id' => '5',
                'permission_id' => '23',
            ],
            18 => [
                'id' => 24,
                'sub_menu_id' => '6',
                'menu_id' => '5',
                'permission_id' => '24',
            ],
            19 => [
                'id' => 25,
                'sub_menu_id' => '6',
                'menu_id' => '5',
                'permission_id' => '25',
            ],
            20 => [
                'id' => 26,
                'sub_menu_id' => '6',
                'menu_id' => '5',
                'permission_id' => '26',
            ],
            21 => [
                'id' => 27,
                'sub_menu_id' => '7',
                'menu_id' => '1',
                'permission_id' => '27',
            ],
            22 => [
                'id' => 28,
                'sub_menu_id' => '7',
                'menu_id' => '1',
                'permission_id' => '28',
            ],
            23 => [
                'id' => 29,
                'sub_menu_id' => '7',
                'menu_id' => '1',
                'permission_id' => '29',
            ],
            24 => [
                'id' => 30,
                'sub_menu_id' => '7',
                'menu_id' => '1',
                'permission_id' => '30',
            ],
            25 => [
                'id' => 31,
                'sub_menu_id' => '7',
                'menu_id' => '1',
                'permission_id' => '31',
            ],
            26 => [
                'id' => 32,
                'sub_menu_id' => '8',
                'menu_id' => '1',
                'permission_id' => '32',
            ],
            27 => [
                'id' => 33,
                'sub_menu_id' => '8',
                'menu_id' => '1',
                'permission_id' => '33',
            ],
            28 => [
                'id' => 34,
                'sub_menu_id' => '8',
                'menu_id' => '1',
                'permission_id' => '34',
            ],
            29 => [
                'id' => 35,
                'sub_menu_id' => '8',
                'menu_id' => '1',
                'permission_id' => '35',
            ],
            30 => [
                'id' => 36,
                'sub_menu_id' => '8',
                'menu_id' => '1',
                'permission_id' => '36',
            ],
            31 => [
                'id' => 37,
                'sub_menu_id' => '9',
                'menu_id' => '2',
                'permission_id' => '37',
            ],
            32 => [
                'id' => 38,
                'sub_menu_id' => '9',
                'menu_id' => '2',
                'permission_id' => '38',
            ],
            33 => [
                'id' => 39,
                'sub_menu_id' => '9',
                'menu_id' => '2',
                'permission_id' => '39',
            ],
            34 => [
                'id' => 40,
                'sub_menu_id' => '9',
                'menu_id' => '2',
                'permission_id' => '40',
            ],
            35 => [
                'id' => 41,
                'sub_menu_id' => '10',
                'menu_id' => '5',
                'permission_id' => '41',
            ],
            36 => [
                'id' => 42,
                'sub_menu_id' => '10',
                'menu_id' => '5',
                'permission_id' => '42',
            ],
            37 => [
                'id' => 43,
                'sub_menu_id' => '10',
                'menu_id' => '5',
                'permission_id' => '43',
            ],
            38 => [
                'id' => 44,
                'sub_menu_id' => '10',
                'menu_id' => '5',
                'permission_id' => '44',
            ],
            39 => [
                'id' => 45,
                'sub_menu_id' => '10',
                'menu_id' => '5',
                'permission_id' => '45',
            ],
            40 => [
                'id' => 46,
                'sub_menu_id' => '11',
                'menu_id' => '5',
                'permission_id' => '46',
            ],
            41 => [
                'id' => 47,
                'sub_menu_id' => '11',
                'menu_id' => '5',
                'permission_id' => '47',
            ],
            42 => [
                'id' => 48,
                'sub_menu_id' => '11',
                'menu_id' => '5',
                'permission_id' => '48',
            ],
            43 => [
                'id' => 49,
                'sub_menu_id' => '11',
                'menu_id' => '5',
                'permission_id' => '49',
            ],
            44 => [
                'id' => 50,
                'sub_menu_id' => '12',
                'menu_id' => '5',
                'permission_id' => '50',
            ],
            45 => [
                'id' => 51,
                'sub_menu_id' => '12',
                'menu_id' => '5',
                'permission_id' => '51',
            ],
            46 => [
                'id' => 52,
                'sub_menu_id' => '12',
                'menu_id' => '5',
                'permission_id' => '52',
            ],
            47 => [
                'id' => 53,
                'sub_menu_id' => '12',
                'menu_id' => '5',
                'permission_id' => '53',
            ],
            48 => [
                'id' => 54,
                'sub_menu_id' => '13',
                'menu_id' => '5',
                'permission_id' => '54',
            ],
            49 => [
                'id' => 55,
                'sub_menu_id' => '13',
                'menu_id' => '5',
                'permission_id' => '55',
            ],
            50 => [
                'id' => 56,
                'sub_menu_id' => '13',
                'menu_id' => '5',
                'permission_id' => '56',
            ],
            51 => [
                'id' => 57,
                'sub_menu_id' => '13',
                'menu_id' => '5',
                'permission_id' => '57',
            ],
            52 => [
                'id' => 65,
                'sub_menu_id' => '20',
                'menu_id' => '6',
                'permission_id' => '65',
            ],
            53 => [
                'id' => 66,
                'sub_menu_id' => '20',
                'menu_id' => '6',
                'permission_id' => '66',
            ],
            54 => [
                'id' => 67,
                'sub_menu_id' => '20',
                'menu_id' => '6',
                'permission_id' => '67',
            ],
            55 => [
                'id' => 68,
                'sub_menu_id' => '20',
                'menu_id' => '6',
                'permission_id' => '68',
            ],
            56 => [
                'id' => 69,
                'sub_menu_id' => '20',
                'menu_id' => '6',
                'permission_id' => '69',
            ],
            57 => [
                'id' => 70,
                'sub_menu_id' => '21',
                'menu_id' => '6',
                'permission_id' => '70',
            ],
            58 => [
                'id' => 71,
                'sub_menu_id' => '21',
                'menu_id' => '6',
                'permission_id' => '71',
            ],
            59 => [
                'id' => 72,
                'sub_menu_id' => '21',
                'menu_id' => '6',
                'permission_id' => '72',
            ],
            60 => [
                'id' => 73,
                'sub_menu_id' => '21',
                'menu_id' => '6',
                'permission_id' => '73',
            ],
            61 => [
                'id' => 74,
                'sub_menu_id' => '22',
                'menu_id' => '10',
                'permission_id' => '74',
            ],
            62 => [
                'id' => 75,
                'sub_menu_id' => '22',
                'menu_id' => '10',
                'permission_id' => '75',
            ],
            63 => [
                'id' => 76,
                'sub_menu_id' => '22',
                'menu_id' => '10',
                'permission_id' => '76',
            ],
            64 => [
                'id' => 77,
                'sub_menu_id' => '22',
                'menu_id' => '10',
                'permission_id' => '77',
            ],
            65 => [
                'id' => 78,
                'sub_menu_id' => '22',
                'menu_id' => '10',
                'permission_id' => '78',
            ],
            66 => [
                'id' => 79,
                'sub_menu_id' => '23',
                'menu_id' => '10',
                'permission_id' => '79',
            ],
            67 => [
                'id' => 80,
                'sub_menu_id' => '23',
                'menu_id' => '10',
                'permission_id' => '80',
            ],
            68 => [
                'id' => 81,
                'sub_menu_id' => '23',
                'menu_id' => '10',
                'permission_id' => '81',
            ],
            69 => [
                'id' => 82,
                'sub_menu_id' => '23',
                'menu_id' => '10',
                'permission_id' => '82',
            ],
            70 => [
                'id' => 83,
                'sub_menu_id' => '24',
                'menu_id' => '10',
                'permission_id' => '83',
            ],
            71 => [
                'id' => 84,
                'sub_menu_id' => '24',
                'menu_id' => '10',
                'permission_id' => '84',
            ],
            72 => [
                'id' => 85,
                'sub_menu_id' => '24',
                'menu_id' => '10',
                'permission_id' => '85',
            ],
            73 => [
                'id' => 86,
                'sub_menu_id' => '24',
                'menu_id' => '10',
                'permission_id' => '86',
            ],
            74 => [
                'id' => 87,
                'sub_menu_id' => '25',
                'menu_id' => '10',
                'permission_id' => '87',
            ],
            75 => [
                'id' => 88,
                'sub_menu_id' => '25',
                'menu_id' => '10',
                'permission_id' => '88',
            ],
            76 => [
                'id' => 89,
                'sub_menu_id' => '25',
                'menu_id' => '10',
                'permission_id' => '89',
            ],
            77 => [
                'id' => 90,
                'sub_menu_id' => '25',
                'menu_id' => '10',
                'permission_id' => '90',
            ],
            78 => [
                'id' => 91,
                'sub_menu_id' => '26',
                'menu_id' => '10',
                'permission_id' => '91',
            ],
            79 => [
                'id' => 92,
                'sub_menu_id' => '26',
                'menu_id' => '10',
                'permission_id' => '92',
            ],
            80 => [
                'id' => 93,
                'sub_menu_id' => '26',
                'menu_id' => '10',
                'permission_id' => '93',
            ],
            81 => [
                'id' => 94,
                'sub_menu_id' => '26',
                'menu_id' => '10',
                'permission_id' => '94',
            ],
            82 => [
                'id' => 95,
                'sub_menu_id' => '27',
                'menu_id' => '10',
                'permission_id' => '95',
            ],
            83 => [
                'id' => 96,
                'sub_menu_id' => '27',
                'menu_id' => '10',
                'permission_id' => '96',
            ],
            84 => [
                'id' => 97,
                'sub_menu_id' => '27',
                'menu_id' => '10',
                'permission_id' => '97',
            ],
            85 => [
                'id' => 98,
                'sub_menu_id' => '27',
                'menu_id' => '10',
                'permission_id' => '98',
            ],
            86 => [
                'id' => 99,
                'sub_menu_id' => '28',
                'menu_id' => '10',
                'permission_id' => '99',
            ],
            87 => [
                'id' => 100,
                'sub_menu_id' => '28',
                'menu_id' => '10',
                'permission_id' => '100',
            ],
            88 => [
                'id' => 101,
                'sub_menu_id' => '28',
                'menu_id' => '10',
                'permission_id' => '101',
            ],
            89 => [
                'id' => 102,
                'sub_menu_id' => '28',
                'menu_id' => '10',
                'permission_id' => '102',
            ],
            90 => [
                'id' => 103,
                'sub_menu_id' => '29',
                'menu_id' => '11',
                'permission_id' => '103',
            ],
            91 => [
                'id' => 104,
                'sub_menu_id' => '29',
                'menu_id' => '11',
                'permission_id' => '104',
            ],
            92 => [
                'id' => 105,
                'sub_menu_id' => '29',
                'menu_id' => '11',
                'permission_id' => '105',
            ],
            93 => [
                'id' => 106,
                'sub_menu_id' => '29',
                'menu_id' => '11',
                'permission_id' => '106',
            ],
            94 => [
                'id' => 107,
                'sub_menu_id' => '29',
                'menu_id' => '11',
                'permission_id' => '107',
            ],
            95 => [
                'id' => 108,
                'sub_menu_id' => '30',
                'menu_id' => '11',
                'permission_id' => '108',
            ],
            96 => [
                'id' => 109,
                'sub_menu_id' => '30',
                'menu_id' => '11',
                'permission_id' => '109',
            ],
            97 => [
                'id' => 110,
                'sub_menu_id' => '30',
                'menu_id' => '11',
                'permission_id' => '110',
            ],
            98 => [
                'id' => 111,
                'sub_menu_id' => '30',
                'menu_id' => '11',
                'permission_id' => '111',
            ],
            99 => [
                'id' => 112,
                'sub_menu_id' => '32',
                'menu_id' => '11',
                'permission_id' => '112',
            ],
            100 => [
                'id' => 113,
                'sub_menu_id' => '32',
                'menu_id' => '11',
                'permission_id' => '113',
            ],
            101 => [
                'id' => 114,
                'sub_menu_id' => '32',
                'menu_id' => '11',
                'permission_id' => '114',
            ],
            102 => [
                'id' => 115,
                'sub_menu_id' => '32',
                'menu_id' => '11',
                'permission_id' => '115',
            ],
            103 => [
                'id' => 116,
                'sub_menu_id' => '33',
                'menu_id' => '11',
                'permission_id' => '116',
            ],
            104 => [
                'id' => 117,
                'sub_menu_id' => '33',
                'menu_id' => '11',
                'permission_id' => '117',
            ],
            105 => [
                'id' => 118,
                'sub_menu_id' => '33',
                'menu_id' => '11',
                'permission_id' => '118',
            ],
            106 => [
                'id' => 119,
                'sub_menu_id' => '33',
                'menu_id' => '11',
                'permission_id' => '119',
            ],
            107 => [
                'id' => 120,
                'sub_menu_id' => '34',
                'menu_id' => '7',
                'permission_id' => '120',
            ],
            108 => [
                'id' => 121,
                'sub_menu_id' => '34',
                'menu_id' => '7',
                'permission_id' => '121',
            ],
            109 => [
                'id' => 122,
                'sub_menu_id' => '34',
                'menu_id' => '7',
                'permission_id' => '122',
            ],
            110 => [
                'id' => 123,
                'sub_menu_id' => '34',
                'menu_id' => '7',
                'permission_id' => '123',
            ],
            111 => [
                'id' => 124,
                'sub_menu_id' => '35',
                'menu_id' => '8',
                'permission_id' => '124',
            ],
            112 => [
                'id' => 125,
                'sub_menu_id' => '35',
                'menu_id' => '8',
                'permission_id' => '125',
            ],
            113 => [
                'id' => 126,
                'sub_menu_id' => '35',
                'menu_id' => '8',
                'permission_id' => '126',
            ],
            114 => [
                'id' => 127,
                'sub_menu_id' => '35',
                'menu_id' => '8',
                'permission_id' => '127',
            ],
            115 => [
                'id' => 128,
                'sub_menu_id' => '36',
                'menu_id' => '9',
                'permission_id' => '128',
            ],
            116 => [
                'id' => 129,
                'sub_menu_id' => '36',
                'menu_id' => '9',
                'permission_id' => '129',
            ],
            117 => [
                'id' => 130,
                'sub_menu_id' => '36',
                'menu_id' => '9',
                'permission_id' => '130',
            ],
            118 => [
                'id' => 131,
                'sub_menu_id' => '36',
                'menu_id' => '9',
                'permission_id' => '131',
            ],
            119 => [
                'id' => 132,
                'sub_menu_id' => '37',
                'menu_id' => '37',
                'permission_id' => '132',
            ],
            120 => [
                'id' => 133,
                'sub_menu_id' => '37',
                'menu_id' => '37',
                'permission_id' => '133',
            ],
            121 => [
                'id' => 134,
                'sub_menu_id' => '37',
                'menu_id' => '37',
                'permission_id' => '134',
            ],
            122 => [
                'id' => 135,
                'sub_menu_id' => '37',
                'menu_id' => '37',
                'permission_id' => '135',
            ],
            123 => [
                'id' => 136,
                'sub_menu_id' => '37',
                'menu_id' => '37',
                'permission_id' => '136',
            ],
            124 => [
                'id' => 137,
                'sub_menu_id' => '38',
                'menu_id' => '37',
                'permission_id' => '137',
            ],
            125 => [
                'id' => 138,
                'sub_menu_id' => '38',
                'menu_id' => '37',
                'permission_id' => '138',
            ],
            126 => [
                'id' => 139,
                'sub_menu_id' => '38',
                'menu_id' => '37',
                'permission_id' => '139',
            ],
            127 => [
                'id' => 140,
                'sub_menu_id' => '38',
                'menu_id' => '37',
                'permission_id' => '140',
            ],
            128 => [
                'id' => 141,
                'sub_menu_id' => '39',
                'menu_id' => '37',
                'permission_id' => '141',
            ],
            129 => [
                'id' => 142,
                'sub_menu_id' => '39',
                'menu_id' => '37',
                'permission_id' => '142',
            ],
            130 => [
                'id' => 143,
                'sub_menu_id' => '39',
                'menu_id' => '37',
                'permission_id' => '143',
            ],
            131 => [
                'id' => 144,
                'sub_menu_id' => '39',
                'menu_id' => '37',
                'permission_id' => '144',
            ],
            132 => [
                'id' => 145,
                'sub_menu_id' => '40',
                'menu_id' => '37',
                'permission_id' => '145',
            ],
            133 => [
                'id' => 146,
                'sub_menu_id' => '40',
                'menu_id' => '37',
                'permission_id' => '146',
            ],
            134 => [
                'id' => 147,
                'sub_menu_id' => '40',
                'menu_id' => '37',
                'permission_id' => '147',
            ],
            135 => [
                'id' => 148,
                'sub_menu_id' => '40',
                'menu_id' => '37',
                'permission_id' => '148',
            ],
            136 => [
                'id' => 149,
                'sub_menu_id' => '41',
                'menu_id' => '37',
                'permission_id' => '149',
            ],
            137 => [
                'id' => 150,
                'sub_menu_id' => '41',
                'menu_id' => '37',
                'permission_id' => '150',
            ],
            138 => [
                'id' => 151,
                'sub_menu_id' => '41',
                'menu_id' => '37',
                'permission_id' => '151',
            ],
            139 => [
                'id' => 152,
                'sub_menu_id' => '41',
                'menu_id' => '37',
                'permission_id' => '152',
            ],
            140 => [
                'id' => 153,
                'sub_menu_id' => '42',
                'menu_id' => '37',
                'permission_id' => '153',
            ],
            141 => [
                'id' => 154,
                'sub_menu_id' => '42',
                'menu_id' => '37',
                'permission_id' => '154',
            ],
            142 => [
                'id' => 155,
                'sub_menu_id' => '42',
                'menu_id' => '37',
                'permission_id' => '155',
            ],
            143 => [
                'id' => 156,
                'sub_menu_id' => '42',
                'menu_id' => '37',
                'permission_id' => '156',
            ],
            144 => [
                'id' => 157,
                'sub_menu_id' => '43',
                'menu_id' => '37',
                'permission_id' => '157',
            ],
            145 => [
                'id' => 158,
                'sub_menu_id' => '43',
                'menu_id' => '37',
                'permission_id' => '158',
            ],
            146 => [
                'id' => 159,
                'sub_menu_id' => '43',
                'menu_id' => '37',
                'permission_id' => '159',
            ],
            147 => [
                'id' => 160,
                'sub_menu_id' => '43',
                'menu_id' => '37',
                'permission_id' => '160',
            ],
            148 => [
                'id' => 161,
                'sub_menu_id' => '44',
                'menu_id' => '38',
                'permission_id' => '161',
            ],
            149 => [
                'id' => 162,
                'sub_menu_id' => '44',
                'menu_id' => '38',
                'permission_id' => '162',
            ],
            150 => [
                'id' => 163,
                'sub_menu_id' => '44',
                'menu_id' => '38',
                'permission_id' => '163',
            ],
            151 => [
                'id' => 164,
                'sub_menu_id' => '44',
                'menu_id' => '38',
                'permission_id' => '164',
            ],
            152 => [
                'id' => 165,
                'sub_menu_id' => '44',
                'menu_id' => '38',
                'permission_id' => '165',
            ],
            153 => [
                'id' => 166,
                'sub_menu_id' => '45',
                'menu_id' => '38',
                'permission_id' => '166',
            ],
            154 => [
                'id' => 167,
                'sub_menu_id' => '45',
                'menu_id' => '38',
                'permission_id' => '167',
            ],
            155 => [
                'id' => 168,
                'sub_menu_id' => '45',
                'menu_id' => '38',
                'permission_id' => '168',
            ],
            156 => [
                'id' => 169,
                'sub_menu_id' => '45',
                'menu_id' => '38',
                'permission_id' => '169',
            ],
            157 => [
                'id' => 170,
                'sub_menu_id' => '46',
                'menu_id' => '38',
                'permission_id' => '170',
            ],
            158 => [
                'id' => 171,
                'sub_menu_id' => '46',
                'menu_id' => '38',
                'permission_id' => '171',
            ],
            159 => [
                'id' => 172,
                'sub_menu_id' => '46',
                'menu_id' => '38',
                'permission_id' => '172',
            ],
            160 => [
                'id' => 173,
                'sub_menu_id' => '46',
                'menu_id' => '38',
                'permission_id' => '173',
            ],
            161 => [
                'id' => 174,
                'sub_menu_id' => '47',
                'menu_id' => '38',
                'permission_id' => '174',
            ],
            162 => [
                'id' => 175,
                'sub_menu_id' => '47',
                'menu_id' => '38',
                'permission_id' => '175',
            ],
            163 => [
                'id' => 176,
                'sub_menu_id' => '47',
                'menu_id' => '38',
                'permission_id' => '176',
            ],
            164 => [
                'id' => 177,
                'sub_menu_id' => '47',
                'menu_id' => '38',
                'permission_id' => '177',
            ],
            165 => [
                'id' => 178,
                'sub_menu_id' => '49',
                'menu_id' => '38',
                'permission_id' => '178',
            ],
            166 => [
                'id' => 179,
                'sub_menu_id' => '49',
                'menu_id' => '38',
                'permission_id' => '179',
            ],
            167 => [
                'id' => 180,
                'sub_menu_id' => '49',
                'menu_id' => '38',
                'permission_id' => '180',
            ],
            168 => [
                'id' => 181,
                'sub_menu_id' => '49',
                'menu_id' => '38',
                'permission_id' => '181',
            ],
            169 => [
                'id' => 182,
                'sub_menu_id' => '50',
                'menu_id' => '38',
                'permission_id' => '182',
            ],
            170 => [
                'id' => 183,
                'sub_menu_id' => '50',
                'menu_id' => '38',
                'permission_id' => '183',
            ],
            171 => [
                'id' => 184,
                'sub_menu_id' => '50',
                'menu_id' => '38',
                'permission_id' => '184',
            ],
            172 => [
                'id' => 185,
                'sub_menu_id' => '50',
                'menu_id' => '38',
                'permission_id' => '185',
            ],
            173 => [
                'id' => 186,
                'sub_menu_id' => '51',
                'menu_id' => '38',
                'permission_id' => '186',
            ],
            174 => [
                'id' => 187,
                'sub_menu_id' => '51',
                'menu_id' => '38',
                'permission_id' => '187',
            ],
            175 => [
                'id' => 188,
                'sub_menu_id' => '51',
                'menu_id' => '38',
                'permission_id' => '188',
            ],
            176 => [
                'id' => 189,
                'sub_menu_id' => '51',
                'menu_id' => '38',
                'permission_id' => '189',
            ],
            177 => [
                'id' => 190,
                'sub_menu_id' => '52',
                'menu_id' => '28',
                'permission_id' => '190',
            ],
            178 => [
                'id' => 191,
                'sub_menu_id' => '52',
                'menu_id' => '28',
                'permission_id' => '191',
            ],
            179 => [
                'id' => 192,
                'sub_menu_id' => '52',
                'menu_id' => '28',
                'permission_id' => '192',
            ],
            180 => [
                'id' => 193,
                'sub_menu_id' => '52',
                'menu_id' => '28',
                'permission_id' => '193',
            ],
            181 => [
                'id' => 194,
                'sub_menu_id' => '53',
                'menu_id' => '29',
                'permission_id' => '194',
            ],
            182 => [
                'id' => 195,
                'sub_menu_id' => '53',
                'menu_id' => '29',
                'permission_id' => '195',
            ],
            183 => [
                'id' => 196,
                'sub_menu_id' => '53',
                'menu_id' => '29',
                'permission_id' => '196',
            ],
            184 => [
                'id' => 197,
                'sub_menu_id' => '53',
                'menu_id' => '29',
                'permission_id' => '197',
            ],
            185 => [
                'id' => 198,
                'sub_menu_id' => '54',
                'menu_id' => '30',
                'permission_id' => '198',
            ],
            186 => [
                'id' => 199,
                'sub_menu_id' => '54',
                'menu_id' => '30',
                'permission_id' => '199',
            ],
            187 => [
                'id' => 200,
                'sub_menu_id' => '54',
                'menu_id' => '30',
                'permission_id' => '200',
            ],
            188 => [
                'id' => 201,
                'sub_menu_id' => '54',
                'menu_id' => '30',
                'permission_id' => '201',
            ],
            189 => [
                'id' => 202,
                'sub_menu_id' => '55',
                'menu_id' => '31',
                'permission_id' => '202',
            ],
            190 => [
                'id' => 203,
                'sub_menu_id' => '55',
                'menu_id' => '31',
                'permission_id' => '203',
            ],
            191 => [
                'id' => 204,
                'sub_menu_id' => '55',
                'menu_id' => '31',
                'permission_id' => '204',
            ],
            192 => [
                'id' => 205,
                'sub_menu_id' => '55',
                'menu_id' => '31',
                'permission_id' => '205',
            ],
            193 => [
                'id' => 206,
                'sub_menu_id' => '56',
                'menu_id' => '32',
                'permission_id' => '206',
            ],
            194 => [
                'id' => 207,
                'sub_menu_id' => '56',
                'menu_id' => '32',
                'permission_id' => '207',
            ],
            195 => [
                'id' => 208,
                'sub_menu_id' => '56',
                'menu_id' => '32',
                'permission_id' => '208',
            ],
            196 => [
                'id' => 209,
                'sub_menu_id' => '56',
                'menu_id' => '32',
                'permission_id' => '209',
            ],
            197 => [
                'id' => 210,
                'sub_menu_id' => '56',
                'menu_id' => '32',
                'permission_id' => '210',
            ],
            198 => [
                'id' => 211,
                'sub_menu_id' => '57',
                'menu_id' => '32',
                'permission_id' => '211',
            ],
            199 => [
                'id' => 212,
                'sub_menu_id' => '57',
                'menu_id' => '32',
                'permission_id' => '212',
            ],
            200 => [
                'id' => 213,
                'sub_menu_id' => '57',
                'menu_id' => '32',
                'permission_id' => '213',
            ],
            201 => [
                'id' => 214,
                'sub_menu_id' => '57',
                'menu_id' => '32',
                'permission_id' => '214',
            ],
            202 => [
                'id' => 215,
                'sub_menu_id' => '58',
                'menu_id' => '33',
                'permission_id' => '215',
            ],
            203 => [
                'id' => 216,
                'sub_menu_id' => '58',
                'menu_id' => '33',
                'permission_id' => '216',
            ],
            204 => [
                'id' => 217,
                'sub_menu_id' => '58',
                'menu_id' => '33',
                'permission_id' => '217',
            ],
            205 => [
                'id' => 218,
                'sub_menu_id' => '58',
                'menu_id' => '33',
                'permission_id' => '218',
            ],
            206 => [
                'id' => 219,
                'sub_menu_id' => '58',
                'menu_id' => '33',
                'permission_id' => '219',
            ],
            207 => [
                'id' => 220,
                'sub_menu_id' => '59',
                'menu_id' => '33',
                'permission_id' => '220',
            ],
            208 => [
                'id' => 221,
                'sub_menu_id' => '59',
                'menu_id' => '33',
                'permission_id' => '221',
            ],
            209 => [
                'id' => 222,
                'sub_menu_id' => '59',
                'menu_id' => '33',
                'permission_id' => '222',
            ],
            210 => [
                'id' => 223,
                'sub_menu_id' => '59',
                'menu_id' => '33',
                'permission_id' => '223',
            ],
            211 => [
                'id' => 224,
                'sub_menu_id' => '60',
                'menu_id' => '33',
                'permission_id' => '224',
            ],
            212 => [
                'id' => 225,
                'sub_menu_id' => '60',
                'menu_id' => '33',
                'permission_id' => '225',
            ],
            213 => [
                'id' => 226,
                'sub_menu_id' => '60',
                'menu_id' => '33',
                'permission_id' => '226',
            ],
            214 => [
                'id' => 227,
                'sub_menu_id' => '60',
                'menu_id' => '33',
                'permission_id' => '227',
            ],
            215 => [
                'id' => 228,
                'sub_menu_id' => '61',
                'menu_id' => '34',
                'permission_id' => '228',
            ],
            216 => [
                'id' => 229,
                'sub_menu_id' => '61',
                'menu_id' => '34',
                'permission_id' => '229',
            ],
            217 => [
                'id' => 230,
                'sub_menu_id' => '61',
                'menu_id' => '34',
                'permission_id' => '230',
            ],
            218 => [
                'id' => 231,
                'sub_menu_id' => '61',
                'menu_id' => '34',
                'permission_id' => '231',
            ],
            219 => [
                'id' => 232,
                'sub_menu_id' => '61',
                'menu_id' => '34',
                'permission_id' => '232',
            ],
            220 => [
                'id' => 233,
                'sub_menu_id' => '62',
                'menu_id' => '34',
                'permission_id' => '233',
            ],
            221 => [
                'id' => 234,
                'sub_menu_id' => '62',
                'menu_id' => '34',
                'permission_id' => '234',
            ],
            222 => [
                'id' => 235,
                'sub_menu_id' => '62',
                'menu_id' => '34',
                'permission_id' => '235',
            ],
            223 => [
                'id' => 236,
                'sub_menu_id' => '62',
                'menu_id' => '34',
                'permission_id' => '236',
            ],
            224 => [
                'id' => 237,
                'sub_menu_id' => '63',
                'menu_id' => '34',
                'permission_id' => '237',
            ],
            225 => [
                'id' => 238,
                'sub_menu_id' => '63',
                'menu_id' => '34',
                'permission_id' => '238',
            ],
            226 => [
                'id' => 239,
                'sub_menu_id' => '63',
                'menu_id' => '34',
                'permission_id' => '239',
            ],
            227 => [
                'id' => 240,
                'sub_menu_id' => '63',
                'menu_id' => '34',
                'permission_id' => '240',
            ],
            228 => [
                'id' => 241,
                'sub_menu_id' => '64',
                'menu_id' => '34',
                'permission_id' => '241',
            ],
            229 => [
                'id' => 242,
                'sub_menu_id' => '64',
                'menu_id' => '34',
                'permission_id' => '242',
            ],
            230 => [
                'id' => 243,
                'sub_menu_id' => '64',
                'menu_id' => '34',
                'permission_id' => '243',
            ],
            231 => [
                'id' => 244,
                'sub_menu_id' => '64',
                'menu_id' => '34',
                'permission_id' => '244',
            ],
            232 => [
                'id' => 245,
                'sub_menu_id' => '65',
                'menu_id' => '34',
                'permission_id' => '245',
            ],
            233 => [
                'id' => 246,
                'sub_menu_id' => '65',
                'menu_id' => '34',
                'permission_id' => '246',
            ],
            234 => [
                'id' => 247,
                'sub_menu_id' => '65',
                'menu_id' => '34',
                'permission_id' => '247',
            ],
            235 => [
                'id' => 248,
                'sub_menu_id' => '65',
                'menu_id' => '34',
                'permission_id' => '248',
            ],
            236 => [
                'id' => 249,
                'sub_menu_id' => '68',
                'menu_id' => '39',
                'permission_id' => '249',
            ],
            237 => [
                'id' => 250,
                'sub_menu_id' => '70',
                'menu_id' => '36',
                'permission_id' => '250',
            ],
            238 => [
                'id' => 251,
                'sub_menu_id' => '70',
                'menu_id' => '36',
                'permission_id' => '251',
            ],
            239 => [
                'id' => 252,
                'sub_menu_id' => '70',
                'menu_id' => '36',
                'permission_id' => '252',
            ],
            240 => [
                'id' => 253,
                'sub_menu_id' => '70',
                'menu_id' => '36',
                'permission_id' => '253',
            ],
            241 => [
                'id' => 254,
                'sub_menu_id' => '70',
                'menu_id' => '36',
                'permission_id' => '254',
            ],
            242 => [
                'id' => 255,
                'sub_menu_id' => '71',
                'menu_id' => '36',
                'permission_id' => '255',
            ],
            243 => [
                'id' => 256,
                'sub_menu_id' => '71',
                'menu_id' => '36',
                'permission_id' => '256',
            ],
            244 => [
                'id' => 257,
                'sub_menu_id' => '71',
                'menu_id' => '36',
                'permission_id' => '257',
            ],
            245 => [
                'id' => 258,
                'sub_menu_id' => '71',
                'menu_id' => '36',
                'permission_id' => '258',
            ],
            246 => [
                'id' => 259,
                'sub_menu_id' => '72',
                'menu_id' => '35',
                'permission_id' => '259',
            ],
            247 => [
                'id' => 260,
                'sub_menu_id' => '72',
                'menu_id' => '35',
                'permission_id' => '260',
            ],
            248 => [
                'id' => 261,
                'sub_menu_id' => '72',
                'menu_id' => '35',
                'permission_id' => '261',
            ],
            249 => [
                'id' => 262,
                'sub_menu_id' => '72',
                'menu_id' => '35',
                'permission_id' => '262',
            ],
            250 => [
                'id' => 263,
                'sub_menu_id' => '72',
                'menu_id' => '35',
                'permission_id' => '263',
            ],
            251 => [
                'id' => 264,
                'sub_menu_id' => '73',
                'menu_id' => '35',
                'permission_id' => '264',
            ],
            252 => [
                'id' => 265,
                'sub_menu_id' => '73',
                'menu_id' => '35',
                'permission_id' => '265',
            ],
            253 => [
                'id' => 266,
                'sub_menu_id' => '73',
                'menu_id' => '35',
                'permission_id' => '266',
            ],
            254 => [
                'id' => 267,
                'sub_menu_id' => '73',
                'menu_id' => '35',
                'permission_id' => '267',
            ],
            255 => [
                'id' => 268,
                'sub_menu_id' => '74',
                'menu_id' => '41',
                'permission_id' => '268',
            ],
            256 => [
                'id' => 269,
                'sub_menu_id' => '74',
                'menu_id' => '41',
                'permission_id' => '269',
            ],
            257 => [
                'id' => 270,
                'sub_menu_id' => '74',
                'menu_id' => '41',
                'permission_id' => '270',
            ],
            258 => [
                'id' => 271,
                'sub_menu_id' => '74',
                'menu_id' => '41',
                'permission_id' => '271',
            ],
            259 => [
                'id' => 272,
                'sub_menu_id' => '74',
                'menu_id' => '41',
                'permission_id' => '272',
            ],
            260 => [
                'id' => 273,
                'sub_menu_id' => '75',
                'menu_id' => '41',
                'permission_id' => '273',
            ],
            261 => [
                'id' => 274,
                'sub_menu_id' => '75',
                'menu_id' => '41',
                'permission_id' => '274',
            ],
            262 => [
                'id' => 275,
                'sub_menu_id' => '75',
                'menu_id' => '41',
                'permission_id' => '275',
            ],
            263 => [
                'id' => 276,
                'sub_menu_id' => '75',
                'menu_id' => '41',
                'permission_id' => '276',
            ],
            264 => [
                'id' => 281,
                'sub_menu_id' => '81',
                'menu_id' => '18',
                'permission_id' => '281',
            ],
            265 => [
                'id' => 282,
                'sub_menu_id' => '81',
                'menu_id' => '18',
                'permission_id' => '282',
            ],
            266 => [
                'id' => 283,
                'sub_menu_id' => '81',
                'menu_id' => '18',
                'permission_id' => '283',
            ],
            267 => [
                'id' => 284,
                'sub_menu_id' => '81',
                'menu_id' => '18',
                'permission_id' => '284',
            ],
            268 => [
                'id' => 285,
                'sub_menu_id' => '82',
                'menu_id' => '19',
                'permission_id' => '285',
            ],
            269 => [
                'id' => 286,
                'sub_menu_id' => '82',
                'menu_id' => '19',
                'permission_id' => '286',
            ],
            270 => [
                'id' => 287,
                'sub_menu_id' => '82',
                'menu_id' => '19',
                'permission_id' => '287',
            ],
            271 => [
                'id' => 288,
                'sub_menu_id' => '82',
                'menu_id' => '19',
                'permission_id' => '288',
            ],
            272 => [
                'id' => 289,
                'sub_menu_id' => '82',
                'menu_id' => '19',
                'permission_id' => '289',
            ],
            273 => [
                'id' => 290,
                'sub_menu_id' => '83',
                'menu_id' => '19',
                'permission_id' => '290',
            ],
            274 => [
                'id' => 291,
                'sub_menu_id' => '83',
                'menu_id' => '19',
                'permission_id' => '291',
            ],
            275 => [
                'id' => 292,
                'sub_menu_id' => '83',
                'menu_id' => '19',
                'permission_id' => '292',
            ],
            276 => [
                'id' => 293,
                'sub_menu_id' => '83',
                'menu_id' => '19',
                'permission_id' => '293',
            ],
            277 => [
                'id' => 294,
                'sub_menu_id' => '84',
                'menu_id' => '20',
                'permission_id' => '294',
            ],
            278 => [
                'id' => 295,
                'sub_menu_id' => '84',
                'menu_id' => '20',
                'permission_id' => '295',
            ],
            279 => [
                'id' => 296,
                'sub_menu_id' => '84',
                'menu_id' => '20',
                'permission_id' => '296',
            ],
            280 => [
                'id' => 297,
                'sub_menu_id' => '84',
                'menu_id' => '20',
                'permission_id' => '297',
            ],
            281 => [
                'id' => 298,
                'sub_menu_id' => '84',
                'menu_id' => '20',
                'permission_id' => '298',
            ],
            282 => [
                'id' => 299,
                'sub_menu_id' => '85',
                'menu_id' => '20',
                'permission_id' => '299',
            ],
            283 => [
                'id' => 300,
                'sub_menu_id' => '85',
                'menu_id' => '20',
                'permission_id' => '300',
            ],
            284 => [
                'id' => 301,
                'sub_menu_id' => '85',
                'menu_id' => '20',
                'permission_id' => '301',
            ],
            285 => [
                'id' => 302,
                'sub_menu_id' => '85',
                'menu_id' => '20',
                'permission_id' => '302',
            ],
            286 => [
                'id' => 303,
                'sub_menu_id' => '86',
                'menu_id' => '21',
                'permission_id' => '303',
            ],
            287 => [
                'id' => 304,
                'sub_menu_id' => '86',
                'menu_id' => '21',
                'permission_id' => '304',
            ],
            288 => [
                'id' => 305,
                'sub_menu_id' => '86',
                'menu_id' => '21',
                'permission_id' => '305',
            ],
            289 => [
                'id' => 306,
                'sub_menu_id' => '86',
                'menu_id' => '21',
                'permission_id' => '306',
            ],
            290 => [
                'id' => 307,
                'sub_menu_id' => '86',
                'menu_id' => '21',
                'permission_id' => '307',
            ],
            291 => [
                'id' => 308,
                'sub_menu_id' => '87',
                'menu_id' => '21',
                'permission_id' => '308',
            ],
            292 => [
                'id' => 309,
                'sub_menu_id' => '87',
                'menu_id' => '21',
                'permission_id' => '309',
            ],
            293 => [
                'id' => 310,
                'sub_menu_id' => '87',
                'menu_id' => '21',
                'permission_id' => '310',
            ],
            294 => [
                'id' => 311,
                'sub_menu_id' => '87',
                'menu_id' => '21',
                'permission_id' => '311',
            ],
            295 => [
                'id' => 312,
                'sub_menu_id' => '88',
                'menu_id' => '21',
                'permission_id' => '312',
            ],
            296 => [
                'id' => 313,
                'sub_menu_id' => '88',
                'menu_id' => '21',
                'permission_id' => '313',
            ],
            297 => [
                'id' => 314,
                'sub_menu_id' => '88',
                'menu_id' => '21',
                'permission_id' => '314',
            ],
            298 => [
                'id' => 315,
                'sub_menu_id' => '88',
                'menu_id' => '21',
                'permission_id' => '315',
            ],
            299 => [
                'id' => 316,
                'sub_menu_id' => '89',
                'menu_id' => '13',
                'permission_id' => '316',
            ],
            300 => [
                'id' => 317,
                'sub_menu_id' => '89',
                'menu_id' => '13',
                'permission_id' => '317',
            ],
            301 => [
                'id' => 318,
                'sub_menu_id' => '89',
                'menu_id' => '13',
                'permission_id' => '318',
            ],
            302 => [
                'id' => 319,
                'sub_menu_id' => '89',
                'menu_id' => '13',
                'permission_id' => '319',
            ],
            303 => [
                'id' => 320,
                'sub_menu_id' => '89',
                'menu_id' => '13',
                'permission_id' => '320',
            ],
            304 => [
                'id' => 321,
                'sub_menu_id' => '90',
                'menu_id' => '14',
                'permission_id' => '321',
            ],
            305 => [
                'id' => 322,
                'sub_menu_id' => '90',
                'menu_id' => '14',
                'permission_id' => '322',
            ],
            306 => [
                'id' => 323,
                'sub_menu_id' => '90',
                'menu_id' => '14',
                'permission_id' => '323',
            ],
            307 => [
                'id' => 324,
                'sub_menu_id' => '90',
                'menu_id' => '14',
                'permission_id' => '324',
            ],
            308 => [
                'id' => 325,
                'sub_menu_id' => '91',
                'menu_id' => '15',
                'permission_id' => '325',
            ],
            309 => [
                'id' => 326,
                'sub_menu_id' => '91',
                'menu_id' => '15',
                'permission_id' => '326',
            ],
            310 => [
                'id' => 327,
                'sub_menu_id' => '91',
                'menu_id' => '15',
                'permission_id' => '327',
            ],
            311 => [
                'id' => 328,
                'sub_menu_id' => '91',
                'menu_id' => '15',
                'permission_id' => '328',
            ],
            312 => [
                'id' => 329,
                'sub_menu_id' => '92',
                'menu_id' => '16',
                'permission_id' => '329',
            ],
            313 => [
                'id' => 330,
                'sub_menu_id' => '92',
                'menu_id' => '16',
                'permission_id' => '330',
            ],
            314 => [
                'id' => 331,
                'sub_menu_id' => '92',
                'menu_id' => '16',
                'permission_id' => '331',
            ],
            315 => [
                'id' => 332,
                'sub_menu_id' => '92',
                'menu_id' => '16',
                'permission_id' => '332',
            ],
            316 => [
                'id' => 333,
                'sub_menu_id' => '93',
                'menu_id' => '17',
                'permission_id' => '333',
            ],
            317 => [
                'id' => 334,
                'sub_menu_id' => '93',
                'menu_id' => '17',
                'permission_id' => '334',
            ],
            318 => [
                'id' => 335,
                'sub_menu_id' => '93',
                'menu_id' => '17',
                'permission_id' => '335',
            ],
            319 => [
                'id' => 336,
                'sub_menu_id' => '93',
                'menu_id' => '17',
                'permission_id' => '336',
            ],
            320 => [
                'id' => 337,
                'sub_menu_id' => '93',
                'menu_id' => '17',
                'permission_id' => '337',
            ],
            321 => [
                'id' => 338,
                'sub_menu_id' => '94',
                'menu_id' => '22',
                'permission_id' => '338',
            ],
            322 => [
                'id' => 339,
                'sub_menu_id' => '94',
                'menu_id' => '22',
                'permission_id' => '339',
            ],
            323 => [
                'id' => 340,
                'sub_menu_id' => '94',
                'menu_id' => '22',
                'permission_id' => '340',
            ],
            324 => [
                'id' => 341,
                'sub_menu_id' => '94',
                'menu_id' => '22',
                'permission_id' => '341',
            ],
            325 => [
                'id' => 342,
                'sub_menu_id' => '95',
                'menu_id' => '23',
                'permission_id' => '342',
            ],
            326 => [
                'id' => 343,
                'sub_menu_id' => '95',
                'menu_id' => '23',
                'permission_id' => '343',
            ],
            327 => [
                'id' => 344,
                'sub_menu_id' => '95',
                'menu_id' => '23',
                'permission_id' => '344',
            ],
            328 => [
                'id' => 345,
                'sub_menu_id' => '95',
                'menu_id' => '23',
                'permission_id' => '345',
            ],
            329 => [
                'id' => 346,
                'sub_menu_id' => '96',
                'menu_id' => '24',
                'permission_id' => '346',
            ],
            330 => [
                'id' => 347,
                'sub_menu_id' => '96',
                'menu_id' => '24',
                'permission_id' => '347',
            ],
            331 => [
                'id' => 348,
                'sub_menu_id' => '96',
                'menu_id' => '24',
                'permission_id' => '348',
            ],
            332 => [
                'id' => 349,
                'sub_menu_id' => '96',
                'menu_id' => '24',
                'permission_id' => '349',
            ],
            333 => [
                'id' => 350,
                'sub_menu_id' => '96',
                'menu_id' => '24',
                'permission_id' => '350',
            ],
            334 => [
                'id' => 351,
                'sub_menu_id' => '97',
                'menu_id' => '24',
                'permission_id' => '351',
            ],
            335 => [
                'id' => 352,
                'sub_menu_id' => '97',
                'menu_id' => '24',
                'permission_id' => '352',
            ],
            336 => [
                'id' => 353,
                'sub_menu_id' => '97',
                'menu_id' => '24',
                'permission_id' => '353',
            ],
            337 => [
                'id' => 354,
                'sub_menu_id' => '97',
                'menu_id' => '24',
                'permission_id' => '354',
            ],
            338 => [
                'id' => 355,
                'sub_menu_id' => '98',
                'menu_id' => '24',
                'permission_id' => '355',
            ],
            339 => [
                'id' => 356,
                'sub_menu_id' => '98',
                'menu_id' => '24',
                'permission_id' => '356',
            ],
            340 => [
                'id' => 357,
                'sub_menu_id' => '98',
                'menu_id' => '24',
                'permission_id' => '357',
            ],
            341 => [
                'id' => 358,
                'sub_menu_id' => '98',
                'menu_id' => '24',
                'permission_id' => '358',
            ],
            342 => [
                'id' => 359,
                'sub_menu_id' => '99',
                'menu_id' => '24',
                'permission_id' => '359',
            ],
            343 => [
                'id' => 360,
                'sub_menu_id' => '99',
                'menu_id' => '24',
                'permission_id' => '360',
            ],
            344 => [
                'id' => 361,
                'sub_menu_id' => '99',
                'menu_id' => '24',
                'permission_id' => '361',
            ],
            345 => [
                'id' => 362,
                'sub_menu_id' => '99',
                'menu_id' => '24',
                'permission_id' => '362',
            ],
            346 => [
                'id' => 363,
                'sub_menu_id' => '100',
                'menu_id' => '24',
                'permission_id' => '363',
            ],
            347 => [
                'id' => 364,
                'sub_menu_id' => '100',
                'menu_id' => '24',
                'permission_id' => '364',
            ],
            348 => [
                'id' => 365,
                'sub_menu_id' => '100',
                'menu_id' => '24',
                'permission_id' => '365',
            ],
            349 => [
                'id' => 366,
                'sub_menu_id' => '100',
                'menu_id' => '24',
                'permission_id' => '366',
            ],
            350 => [
                'id' => 367,
                'sub_menu_id' => '101',
                'menu_id' => '24',
                'permission_id' => '367',
            ],
            351 => [
                'id' => 368,
                'sub_menu_id' => '101',
                'menu_id' => '24',
                'permission_id' => '368',
            ],
            352 => [
                'id' => 369,
                'sub_menu_id' => '101',
                'menu_id' => '24',
                'permission_id' => '369',
            ],
            353 => [
                'id' => 370,
                'sub_menu_id' => '101',
                'menu_id' => '24',
                'permission_id' => '370',
            ],
            354 => [
                'id' => 371,
                'sub_menu_id' => '102',
                'menu_id' => '25',
                'permission_id' => '371',
            ],
            355 => [
                'id' => 372,
                'sub_menu_id' => '102',
                'menu_id' => '25',
                'permission_id' => '372',
            ],
            356 => [
                'id' => 373,
                'sub_menu_id' => '102',
                'menu_id' => '25',
                'permission_id' => '373',
            ],
            357 => [
                'id' => 374,
                'sub_menu_id' => '102',
                'menu_id' => '25',
                'permission_id' => '374',
            ],
            358 => [
                'id' => 375,
                'sub_menu_id' => '102',
                'menu_id' => '25',
                'permission_id' => '375',
            ],
            359 => [
                'id' => 376,
                'sub_menu_id' => '103',
                'menu_id' => '26',
                'permission_id' => '376',
            ],
            360 => [
                'id' => 377,
                'sub_menu_id' => '103',
                'menu_id' => '26',
                'permission_id' => '377',
            ],
            361 => [
                'id' => 378,
                'sub_menu_id' => '103',
                'menu_id' => '26',
                'permission_id' => '378',
            ],
            362 => [
                'id' => 379,
                'sub_menu_id' => '103',
                'menu_id' => '26',
                'permission_id' => '379',
            ],
            363 => [
                'id' => 380,
                'sub_menu_id' => '103',
                'menu_id' => '26',
                'permission_id' => '380',
            ],
            364 => [
                'id' => 381,
                'sub_menu_id' => '104',
                'menu_id' => '27',
                'permission_id' => '381',
            ],
            365 => [
                'id' => 382,
                'sub_menu_id' => '104',
                'menu_id' => '27',
                'permission_id' => '382',
            ],
            366 => [
                'id' => 383,
                'sub_menu_id' => '104',
                'menu_id' => '27',
                'permission_id' => '383',
            ],
            367 => [
                'id' => 384,
                'sub_menu_id' => '104',
                'menu_id' => '27',
                'permission_id' => '384',
            ],
            368 => [
                'id' => 385,
                'sub_menu_id' => '104',
                'menu_id' => '27',
                'permission_id' => '385',
            ],
        ]);
    }
}
