<?php

use Illuminate\Database\Seeder;

class ProgrammecoursesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run(): void
    {

        //\DB::table('programmecourses')->delete();

        \DB::table('programmecourses')->insert([
            0 => [
                'id' => 1,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Management 1',
                'coursecode' => 'BGEC100',
                'credithours' => '3',
            ],
            1 => [
                'id' => 2,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Law ',
                'coursecode' => 'BGEC101',
                'credithours' => '3',
            ],
            2 => [
                'id' => 3,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Intro to Computer Skills',
                'coursecode' => 'BGEC102',
                'credithours' => '3',
            ],
            3 => [
                'id' => 4,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Statisties',
                'coursecode' => 'BGEC103',
                'credithours' => '3',
            ],
            4 => [
                'id' => 5,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Communication Skills',
                'coursecode' => 'BGEC104',
                'credithours' => '3',
            ],
            5 => [
                'id' => 9,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Principles of Marketing',
                'coursecode' => 'BGEC109',
                'credithours' => '3',
            ],
            6 => [
                'id' => 10,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Communication  11',
                'coursecode' => 'BGEC110',
                'credithours' => '3',
            ],
            7 => [
                'id' => 11,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Communication 1',
                'coursecode' => 'BGEC106',
                'credithours' => '3',
            ],
            8 => [
                'id' => 12,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Intro to Organisation Behaviour',
                'coursecode' => 'BGEC107',
                'credithours' => '3',
            ],
            9 => [
                'id' => 13,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Elements of Economics',
                'coursecode' => 'BGEC108',
                'credithours' => '3',
            ],
            10 => [
                'id' => 16,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Policy and Strategy 11',
                'coursecode' => 'BCPC205',
                'credithours' => '3',
            ],
            11 => [
                'id' => 17,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Marketing Planning',
                'coursecode' => 'BCPC206',
                'credithours' => '3',
            ],
            12 => [
                'id' => 18,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Sales Management',
                'coursecode' => 'BCPC207',
                'credithours' => '3',
            ],
            13 => [
                'id' => 19,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Marketing Research',
                'coursecode' => 'BCPC208',
                'credithours' => '3',
            ],
            14 => [
                'id' => 20,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Human Resource Management',
                'coursecode' => 'BCPC209',
                'credithours' => '3',
            ],
            15 => [
                'id' => 21,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Policy and Strategy 1',
                'coursecode' => 'BCPC200',
                'credithours' => '3',
            ],
            16 => [
                'id' => 22,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Finance',
                'coursecode' => 'BCPC201',
                'credithours' => '3',
            ],
            17 => [
                'id' => 23,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Entrepreneurship',
                'coursecode' => 'BCPC202',
                'credithours' => '3',
            ],
            18 => [
                'id' => 24,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Economy of Ghana',
                'coursecode' => 'BCPC203',
                'credithours' => '3',
            ],
            19 => [
                'id' => 25,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Company Law',
                'coursecode' => 'BCPC204',
                'credithours' => '3',
            ],
            20 => [
                'id' => 26,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Company and Partnership Law',
                'coursecode' => 'BACT305',
                'credithours' => '3',
            ],
            21 => [
                'id' => 27,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Management Accounting',
                'coursecode' => 'BACT306',
                'credithours' => '3',
            ],
            22 => [
                'id' => 28,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Taxation',
                'coursecode' => 'BACT307',
                'credithours' => '3',
            ],
            23 => [
                'id' => 29,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Audit & Internal Review',
                'coursecode' => 'BACT308',
                'credithours' => '3',
            ],
            24 => [
                'id' => 30,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Research Methods',
                'coursecode' => 'BACT300',
                'credithours' => '3',
            ],
            25 => [
                'id' => 31,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Enterpreneurship Development',
                'coursecode' => 'BACT301',
                'credithours' => '3',
            ],
            26 => [
                'id' => 32,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Cost Accounting',
                'coursecode' => 'BACT302',
                'credithours' => '3',
            ],
            27 => [
                'id' => 33,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Financial Reporting 1',
                'coursecode' => 'BACT303',
                'credithours' => '3',
            ],
            28 => [
                'id' => 34,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Financial Reporting 2',
                'coursecode' => 'BACT304',
                'credithours' => '3',
            ],
            29 => [
                'id' => 35,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Business Policy and Strategy ',
                'coursecode' => 'BBBA400',
                'credithours' => '3',
            ],
            30 => [
                'id' => 36,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Coroperate Reporting 1',
                'coursecode' => 'BBBA401',
                'credithours' => '3',
            ],
            31 => [
                'id' => 37,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Taxation & Fiscal Policy',
                'coursecode' => 'BBBA402',
                'credithours' => '3',
            ],
            32 => [
                'id' => 38,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Project Work',
                'coursecode' => 'BBBA403',
                'credithours' => '6',
            ],
            33 => [
                'id' => 39,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Internship',
                'coursecode' => 'BBBA404',
                'credithours' => '3',
            ],
            34 => [
                'id' => 40,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Information Management',
                'coursecode' => 'BBBA405',
                'credithours' => '3',
            ],
            35 => [
                'id' => 41,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Software Quality Management',
                'coursecode' => 'BBBA406',
                'credithours' => '3',
            ],
            36 => [
                'id' => 42,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Electronic Business',
                'coursecode' => 'BBBA407',
                'credithours' => '3',
            ],
            37 => [
                'id' => 43,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Mobile Web Development',
                'coursecode' => 'BBBA408',
                'credithours' => '3',
            ],
            38 => [
                'id' => 44,
                'programme' => 'Bachelor of Science  in Information Technology Management',
                'progcode' => 'BITM',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'computer & Network Security',
                'coursecode' => 'BBBA409',
                'credithours' => '3',
            ],
            39 => [
                'id' => 45,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Management 1',
                'coursecode' => 'BGEC100',
                'credithours' => '3',
            ],
            40 => [
                'id' => 46,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Law ',
                'coursecode' => 'BGEC101',
                'credithours' => '3',
            ],
            41 => [
                'id' => 47,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Intro to Computer Skills',
                'coursecode' => 'BGEC102',
                'credithours' => '3',
            ],
            42 => [
                'id' => 48,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Statisties',
                'coursecode' => 'BGEC103',
                'credithours' => '3',
            ],
            43 => [
                'id' => 49,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Communication Skills',
                'coursecode' => 'BGEC104',
                'credithours' => '3',
            ],
            44 => [
                'id' => 50,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Communication 1',
                'coursecode' => 'BGEC106',
                'credithours' => '3',
            ],
            45 => [
                'id' => 51,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Intro to Organisation Behaviour',
                'coursecode' => 'BGEC107',
                'credithours' => '3',
            ],
            46 => [
                'id' => 52,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Elements of Economics',
                'coursecode' => 'BGEC108',
                'credithours' => '3',
            ],
            47 => [
                'id' => 53,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Principles of Marketing',
                'coursecode' => 'BGEC109',
                'credithours' => '3',
            ],
            48 => [
                'id' => 54,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Communication  11',
                'coursecode' => 'BGEC110',
                'credithours' => '3',
            ],
            49 => [
                'id' => 55,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Policy and Strategy 1',
                'coursecode' => 'BCPC200',
                'credithours' => '3',
            ],
            50 => [
                'id' => 56,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Finance',
                'coursecode' => 'BCPC201',
                'credithours' => '3',
            ],
            51 => [
                'id' => 57,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Entrepreneurship',
                'coursecode' => 'BCPC202',
                'credithours' => '3',
            ],
            52 => [
                'id' => 58,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Economy of Ghana',
                'coursecode' => 'BCPC203',
                'credithours' => '3',
            ],
            53 => [
                'id' => 59,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Company Law',
                'coursecode' => 'BCPC204',
                'credithours' => '3',
            ],
            54 => [
                'id' => 60,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Policy and Strategy 11',
                'coursecode' => 'BCPC205',
                'credithours' => '3',
            ],
            55 => [
                'id' => 61,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Marketing Planning',
                'coursecode' => 'BCPC206',
                'credithours' => '3',
            ],
            56 => [
                'id' => 62,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Sales Management',
                'coursecode' => 'BCPC207',
                'credithours' => '3',
            ],
            57 => [
                'id' => 63,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Marketing Research',
                'coursecode' => 'BCPC208',
                'credithours' => '3',
            ],
            58 => [
                'id' => 64,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Human Resource Management',
                'coursecode' => 'BCPC209',
                'credithours' => '3',
            ],
            59 => [
                'id' => 65,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Company and Partnership Law',
                'coursecode' => 'BACT305',
                'credithours' => '3',
            ],
            60 => [
                'id' => 66,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Management Accounting',
                'coursecode' => 'BACT306',
                'credithours' => '3',
            ],
            61 => [
                'id' => 67,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Taxation',
                'coursecode' => 'BACT307',
                'credithours' => '3',
            ],
            62 => [
                'id' => 68,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Audit & Internal Review',
                'coursecode' => 'BACT308',
                'credithours' => '3',
            ],
            63 => [
                'id' => 69,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Research Methods',
                'coursecode' => 'BACT300',
                'credithours' => '3',
            ],
            64 => [
                'id' => 70,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Enterpreneurship Development',
                'coursecode' => 'BACT301',
                'credithours' => '3',
            ],
            65 => [
                'id' => 71,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Cost Accounting',
                'coursecode' => 'BACT302',
                'credithours' => '3',
            ],
            66 => [
                'id' => 72,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Financial Reporting 1',
                'coursecode' => 'BACT303',
                'credithours' => '3',
            ],
            67 => [
                'id' => 73,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 300',
                'coursetitle' => 'Financial Reporting 2',
                'coursecode' => 'BACT304',
                'credithours' => '3',
            ],
            68 => [
                'id' => 74,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Information Management',
                'coursecode' => 'BBBA405',
                'credithours' => '3',
            ],
            69 => [
                'id' => 75,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Software Quality Management',
                'coursecode' => 'BBBA406',
                'credithours' => '3',
            ],
            70 => [
                'id' => 76,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Electronic Business',
                'coursecode' => 'BBBA407',
                'credithours' => '3',
            ],
            71 => [
                'id' => 77,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Mobile Web Development',
                'coursecode' => 'BBBA408',
                'credithours' => '3',
            ],
            72 => [
                'id' => 78,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'Second Semester',
                'level' => 'Level 400',
                'coursetitle' => 'computer & Network Security',
                'coursecode' => 'BBBA409',
                'credithours' => '3',
            ],
            73 => [
                'id' => 79,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Business Policy and Strategy ',
                'coursecode' => 'BBBA400',
                'credithours' => '3',
            ],
            74 => [
                'id' => 80,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Coroperate Reporting 1',
                'coursecode' => 'BBBA401',
                'credithours' => '3',
            ],
            75 => [
                'id' => 81,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Taxation & Fiscal Policy',
                'coursecode' => 'BBBA402',
                'credithours' => '3',
            ],
            76 => [
                'id' => 82,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Project Work',
                'coursecode' => 'BBBA403',
                'credithours' => '6',
            ],
            77 => [
                'id' => 83,
                'programme' => 'Bachelor of Arts in Public Relations Management',
                'progcode' => 'BAPR',
                'semester' => 'First Semester',
                'level' => 'Level 400',
                'coursetitle' => 'Internship',
                'coursecode' => 'BBBA404',
                'credithours' => '3',
            ],
            78 => [
                'id' => 84,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Communication 1',
                'coursecode' => 'BGEC106',
                'credithours' => '3',
            ],
            79 => [
                'id' => 85,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Intro to Organisation Behaviour',
                'coursecode' => 'BGEC107',
                'credithours' => '3',
            ],
            80 => [
                'id' => 86,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Elements of Economics',
                'coursecode' => 'BGEC108',
                'credithours' => '3',
            ],
            81 => [
                'id' => 87,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Principles of Marketing',
                'coursecode' => 'BGEC109',
                'credithours' => '3',
            ],
            82 => [
                'id' => 88,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Communication  11',
                'coursecode' => 'BGEC110',
                'credithours' => '3',
            ],
            83 => [
                'id' => 89,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Management 1',
                'coursecode' => 'BGEC100',
                'credithours' => '3',
            ],
            84 => [
                'id' => 90,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Law ',
                'coursecode' => 'BGEC101',
                'credithours' => '3',
            ],
            85 => [
                'id' => 91,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Intro to Computer Skills',
                'coursecode' => 'BGEC102',
                'credithours' => '3',
            ],
            86 => [
                'id' => 92,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Business Statisties',
                'coursecode' => 'BGEC103',
                'credithours' => '3',
            ],
            87 => [
                'id' => 93,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 100',
                'coursetitle' => 'Communication Skills',
                'coursecode' => 'BGEC104',
                'credithours' => '3',
            ],
            88 => [
                'id' => 94,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Policy and Strategy 1',
                'coursecode' => 'BCPC200',
                'credithours' => '3',
            ],
            89 => [
                'id' => 95,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Finance',
                'coursecode' => 'BCPC201',
                'credithours' => '3',
            ],
            90 => [
                'id' => 96,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Entrepreneurship',
                'coursecode' => 'BCPC202',
                'credithours' => '3',
            ],
            91 => [
                'id' => 97,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Economy of Ghana',
                'coursecode' => 'BCPC203',
                'credithours' => '3',
            ],
            92 => [
                'id' => 98,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'First Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Company Law',
                'coursecode' => 'BCPC204',
                'credithours' => '3',
            ],
            93 => [
                'id' => 99,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Business Policy and Strategy 11',
                'coursecode' => 'BCPC205',
                'credithours' => '3',
            ],
            94 => [
                'id' => 100,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Marketing Planning',
                'coursecode' => 'BCPC206',
                'credithours' => '3',
            ],
            95 => [
                'id' => 101,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Sales Management',
                'coursecode' => 'BCPC207',
                'credithours' => '3',
            ],
            96 => [
                'id' => 102,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Marketing Research',
                'coursecode' => 'BCPC208',
                'credithours' => '3',
            ],
            97 => [
                'id' => 103,
                'programme' => 'Diploma in Accounting',
                'progcode' => 'DIAA',
                'semester' => 'Second Semester',
                'level' => 'Level 200',
                'coursetitle' => 'Human Resource Management',
                'coursecode' => 'BCPC209',
                'credithours' => '3',
            ],
        ]);
    }
}
