<?php

return [
    'af' => [
        'code' => 'af',
        'locale' => 'af',
        'name' => 'Afrikaans',
        'flag' => env('APP_URL') . '/flags/za.png',
    ],
    'ar' => [
        'code' => 'ar',
        'locale' => 'ar',
        'name' => 'العربية',
        'flag' => env('APP_URL') . '/flags/arab.png',
    ],
    'ary' => [
        'code' => 'ar',
        'locale' => 'ary',
        'name' => 'العربية المغربية',
        'flag' => env('APP_URL') . '/flags/ma.png',
    ],
    'as' => [
        'code' => 'as',
        'locale' => 'as',
        'name' => 'অসমীয়া',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'az' => [
        'code' => 'az',
        'locale' => 'az',
        'name' => 'Azərbaycan',
        'flag' => env('APP_URL') . '/flags/az.png',
    ],
    'azb' => [
        'code' => 'az',
        'locale' => 'azb',
        'name' => 'گؤنئی آذربایجان',
        'flag' => env('APP_URL') . '/flags/az.png',
    ],
    'bel' => [
        'code' => 'be',
        'locale' => 'bel',
        'name' => 'Беларуская мова',
        'flag' => env('APP_URL') . '/flags/by.png',
        'w3c' => 'be',
    ],
    'bg_BG' => [
        'code' => 'bg',
        'locale' => 'bg_BG',
        'name' => 'български',
        'flag' => env('APP_URL') . '/flags/bg.png',
    ],
    'bn_BD' => [
        'code' => 'bn',
        'locale' => 'bn_BD',
        'name' => 'বাংলা',
        'flag' => env('APP_URL') . '/flags/bd.png',
    ],
    'bo' => [
        'code' => 'bo',
        'locale' => 'bo',
        'name' => 'བོད་ཡིག',
        'flag' => env('APP_URL') . '/flags/tibet.png',
    ],
    'bs_BA' => [
        'code' => 'bs',
        'locale' => 'bs_BA',
        'name' => 'Bosanski',
        'flag' => env('APP_URL') . '/flags/ba.png',
    ],
    'ca' => [
        'code' => 'ca',
        'locale' => 'ca',
        'name' => 'Català',
        'flag' => env('APP_URL') . '/flags/catalonia.png',
    ],
    'ceb' => [
        'code' => 'ceb',
        'locale' => 'ceb',
        'name' => 'Cebuano',
        'flag' => env('APP_URL') . '/flags/ph.png',
    ],
    'ckb' => [
        'code' => 'ku',
        'locale' => 'ckb',
        'name' => 'کوردی',
        'flag' => env('APP_URL') . '/flags/kurdistan.png',
    ],
    'cs_CZ' => [
        'code' => 'cs',
        'locale' => 'cs_CZ',
        'name' => 'Čeština',
        'flag' => env('APP_URL') . '/flags/cz.png',
    ],
    'cy' => [
        'code' => 'cy',
        'locale' => 'cy',
        'name' => 'Cymraeg',
        'flag' => env('APP_URL') . '/flags/wales.png',
    ],
    'da_DK' => [
        'code' => 'da',
        'locale' => 'da_DK',
        'name' => 'Dansk',
        'flag' => env('APP_URL') . '/flags/dk.png',
    ],
    'de_DE' => [
        'code' => 'de',
        'locale' => 'de_DE',
        'name' => 'Deutsch',
        'flag' => env('APP_URL') . '/flags/de.png',
    ],
    'dzo' => [
        'code' => 'dz',
        'locale' => 'dzo',
        'name' => 'རྫོང་ཁ',
        'flag' => env('APP_URL') . '/flags/bt.png',
        'w3c' => 'dz',
    ],
    'el' => [
        'code' => 'el',
        'locale' => 'el',
        'name' => 'Ελληνικά',
        'flag' => env('APP_URL') . '/flags/gr.png',
    ],
    'en_US' => [
        'code' => 'en',
        'locale' => 'en_US',
        'name' => 'English',
        'flag' => env('APP_URL') . '/flags/us.png',
    ],
    'eo' => [
        'code' => 'eo',
        'locale' => 'eo',
        'name' => 'Esperanto',
        'flag' => env('APP_URL') . '/flags/esperanto.png',
    ],
    'es_ES' => [
        'code' => 'es',
        'locale' => 'es_ES',
        'name' => 'Español',
        'flag' => env('APP_URL') . '/flags/es.png',
    ],
    'et' => [
        'code' => 'et',
        'locale' => 'et',
        'name' => 'Eesti',
        'flag' => env('APP_URL') . '/flags/ee.png',
    ],
    'eu' => [
        'code' => 'eu',
        'locale' => 'eu',
        'name' => 'Euskara',
        'flag' => env('APP_URL') . '/flags/basque.png',
    ],
    'fa_AF' => [
        'code' => 'fa',
        'locale' => 'fa_AF',
        'name' => 'فارسی',
        'flag' => env('APP_URL') . '/flags/af.png',
    ],
    'fa_IR' => [
        'code' => 'fa',
        'locale' => 'fa_IR',
        'name' => 'فارسی',
        'flag' => env('APP_URL') . '/flags/ir.png',
    ],
    'fi' => [
        'code' => 'fi',
        'locale' => 'fi',
        'name' => 'Suomi',
        'flag' => env('APP_URL') . '/flags/fi.png',
    ],
    'fo' => [
        'code' => 'fo',
        'locale' => 'fo',
        'name' => 'Føroyskt',
        'flag' => env('APP_URL') . '/flags/fo.png',
    ],
    'fr_FR' => [
        'code' => 'fr',
        'locale' => 'fr_FR',
        'name' => 'Français',
        'flag' => env('APP_URL') . '/flags/fr.png',
    ],
    'fur' => [
        'code' => 'fur',
        'locale' => 'fur',
        'name' => 'Furlan',
        'flag' => env('APP_URL') . '/flags/it.png',
    ],
    'fy' => [
        'code' => 'fy',
        'locale' => 'fy',
        'name' => 'Frysk',
        'flag' => env('APP_URL') . '/flags/nl.png',
    ],
    'gd' => [
        'code' => 'gd',
        'locale' => 'gd',
        'name' => 'Gàidhlig',
        'flag' => env('APP_URL') . '/flags/scotland.png',
    ],
    'gl_ES' => [
        'code' => 'gl',
        'locale' => 'gl_ES',
        'name' => 'Galego',
        'flag' => env('APP_URL') . '/flags/galicia.png',
    ],
    'gu' => [
        'code' => 'gu',
        'locale' => 'gu',
        'name' => 'ગુજરાતી',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'haz' => [
        'code' => 'haz',
        'locale' => 'haz',
        'name' => 'هزاره گی',
        'flag' => env('APP_URL') . '/flags/af.png',
    ],
    'he_IL' => [
        'code' => 'he',
        'locale' => 'he_IL',
        'name' => 'עברית',
        'flag' => env('APP_URL') . '/flags/il.png',
    ],
    'hi_IN' => [
        'code' => 'hi',
        'locale' => 'hi_IN',
        'name' => 'हिन्दी',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'hr' => [
        'code' => 'hr',
        'locale' => 'hr',
        'name' => 'Hrvatski',
        'flag' => env('APP_URL') . '/flags/hr.png',
    ],
    'hu_HU' => [
        'code' => 'hu',
        'locale' => 'hu_HU',
        'name' => 'Magyar',
        'flag' => env('APP_URL') . '/flags/hu.png',
    ],
    'hsb' => [
        'code' => 'hsb',
        'locale' => 'hsb',
        'name' => 'Hornjoserbšćina',
        'flag' => env('APP_URL') . '/flags/de.png',
    ],
    'hy' => [
        'code' => 'hy',
        'locale' => 'hy',
        'name' => 'Հայերեն',
        'flag' => env('APP_URL') . '/flags/am.png',
    ],
    'id_ID' => [
        'code' => 'id',
        'locale' => 'id_ID',
        'name' => 'Bahasa Indonesia',
        'flag' => env('APP_URL') . '/flags/id.png',
    ],
    'is_IS' => [
        'code' => 'is',
        'locale' => 'is_IS',
        'name' => 'Íslenska',
        'flag' => env('APP_URL') . '/flags/is.png',
    ],
    'it_IT' => [
        'code' => 'it',
        'locale' => 'it_IT',
        'name' => 'Italiano',
        'flag' => env('APP_URL') . '/flags/it.png',
    ],
    'ja' => [
        'code' => 'ja',
        'locale' => 'ja',
        'name' => '日本語',
        'flag' => env('APP_URL') . '/flags/jp.png',
    ],
    'jv_ID' => [
        'code' => 'jv',
        'locale' => 'jv_ID',
        'name' => 'Basa Jawa',
        'flag' => env('APP_URL') . '/flags/id.png',
    ],
    'ka_GE' => [
        'code' => 'ka',
        'locale' => 'ka_GE',
        'name' => 'ქართული',
        'flag' => env('APP_URL') . '/flags/ge.png',
    ],
    'kab' => [
        'code' => 'kab',
        'locale' => 'kab',
        'name' => 'Taqbaylit',
        'flag' => env('APP_URL') . '/flags/dz.png',
    ],
    'kk' => [
        'code' => 'kk',
        'locale' => 'kk',
        'name' => 'Қазақ тілі',
        'flag' => env('APP_URL') . '/flags/kz.png',
    ],
    'km' => [
        'code' => 'km',
        'locale' => 'km',
        'name' => 'ភាសាខ្មែរ',
        'flag' => env('APP_URL') . '/flags/kh.png',
    ],
    'kn' => [
        'code' => 'kn',
        'locale' => 'kn',
        'name' => 'ಕನ್ನಡ',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'ko_KR' => [
        'code' => 'ko',
        'locale' => 'ko_KR',
        'name' => '한국어',
        'flag' => env('APP_URL') . '/flags/kr.png',
    ],
    'lo' => [
        'code' => 'lo',
        'locale' => 'lo',
        'name' => 'ພາສາລາວ',
        'flag' => env('APP_URL') . '/flags/la.png',
    ],
    'lt_LT' => [
        'code' => 'lt',
        'locale' => 'lt_LT',
        'name' => 'Lietuviškai',
        'flag' => env('APP_URL') . '/flags/lt.png',
    ],
    'lv' => [
        'code' => 'lv',
        'locale' => 'lv',
        'name' => 'Latviešu valoda',
        'flag' => env('APP_URL') . '/flags/lv.png',
    ],
    'mk_MK' => [
        'code' => 'mk',
        'locale' => 'mk_MK',
        'name' => 'македонски јазик',
        'flag' => env('APP_URL') . '/flags/mk.png',
    ],
    'ml_IN' => [
        'code' => 'ml',
        'locale' => 'ml_IN',
        'name' => 'മലയാളം',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'mn' => [
        'code' => 'mn',
        'locale' => 'mn',
        'name' => 'Монгол хэл',
        'flag' => env('APP_URL') . '/flags/mn.png',
    ],
    'mr' => [
        'code' => 'mr',
        'locale' => 'mr',
        'name' => 'मराठी',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'ms_MY' => [
        'code' => 'ms',
        'locale' => 'ms_MY',
        'name' => 'Bahasa Melayu',
        'flag' => env('APP_URL') . '/flags/my.png',
    ],
    'my_MM' => [
        'code' => 'my',
        'locale' => 'my_MM',
        'name' => 'ဗမာစာ',
        'flag' => env('APP_URL') . '/flags/mm.png',
    ],
    'nb_NO' => [
        'code' => 'nb',
        'locale' => 'nb_NO',
        'name' => 'Norsk Bokmål',
        'flag' => env('APP_URL') . '/flags/no.png',
    ],
    'ne_NP' => [
        'code' => 'ne',
        'locale' => 'ne_NP',
        'name' => 'नेपाली',
        'flag' => env('APP_URL') . '/flags/np.png',
    ],
    'nl_NL' => [
        'code' => 'nl',
        'locale' => 'nl_NL',
        'name' => 'Nederlands',
        'flag' => env('APP_URL') . '/flags/nl.png',
    ],
    'nn_NO' => [
        'code' => 'nn',
        'locale' => 'nn_NO',
        'name' => 'Norsk Nynorsk',
        'flag' => env('APP_URL') . '/flags/no.png',
    ],
    'oci' => [
        'code' => 'oc',
        'locale' => 'oci',
        'name' => 'Occitan',
        'flag' => env('APP_URL') . '/flags/occitania.png',
        'w3c' => 'oc',
    ],
    'pa_IN' => [
        'code' => 'pa',
        'locale' => 'pa_IN',
        'name' => 'ਪੰਜਾਬੀ',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'pl_PL' => [
        'code' => 'pl',
        'locale' => 'pl_PL',
        'name' => 'Polski',
        'flag' => env('APP_URL') . '/flags/pl.png',
    ],
    'ps' => [
        'code' => 'ps',
        'locale' => 'ps',
        'name' => 'پښتو',
        'flag' => env('APP_URL') . '/flags/af.png',
    ],
    'pt_PT' => [
        'code' => 'pt',
        'locale' => 'pt_PT',
        'name' => 'Português',
        'flag' => env('APP_URL') . '/flags/pt.png',
    ],
    'rhg' => [
        'code' => 'rhg',
        'locale' => 'rhg',
        'name' => 'Ruáinga',
        'flag' => env('APP_URL') . '/flags/mm.png',
    ],
    'ro_RO' => [
        'code' => 'ro',
        'locale' => 'ro_RO',
        'name' => 'Română',
        'flag' => env('APP_URL') . '/flags/ro.png',
    ],
    'ru_RU' => [
        'code' => 'ru',
        'locale' => 'ru_RU',
        'name' => 'Русский',
        'flag' => env('APP_URL') . '/flags/ru.png',
    ],
    'sah' => [
        'code' => 'sah',
        'locale' => 'sah',
        'name' => 'Сахалыы',
        'flag' => env('APP_URL') . '/flags/ru.png',
    ],
    'si_LK' => [
        'code' => 'si',
        'locale' => 'si_LK',
        'name' => 'සිංහල',
        'flag' => env('APP_URL') . '/flags/lk.png',
    ],
    'sk_SK' => [
        'code' => 'sk',
        'locale' => 'sk_SK',
        'name' => 'Slovenčina',
        'flag' => env('APP_URL') . '/flags/sk.png',
    ],
    'skr' => [
        'code' => 'skr',
        'locale' => 'skr',
        'name' => 'سرائیکی',
        'flag' => env('APP_URL') . '/flags/pk.png',
    ],
    'sl_SI' => [
        'code' => 'sl',
        'locale' => 'sl_SI',
        'name' => 'Slovenščina',
        'flag' => env('APP_URL') . '/flags/si.png',
    ],
    'snd' => [
        'code' => 'sd',
        'locale' => 'snd',
        'name' => 'سنڌي',
        'flag' => env('APP_URL') . '/flags/pk.png',
    ],
    'so_SO' => [
        'code' => 'so',
        'locale' => 'so_SO',
        'name' => 'Af-Soomaali',
        'flag' => env('APP_URL') . '/flags/so.png',
    ],
    'sq' => [
        'code' => 'sq',
        'locale' => 'sq',
        'name' => 'Shqip',
        'flag' => env('APP_URL') . '/flags/al.png',
    ],
    'sr_RS' => [
        'code' => 'sr',
        'locale' => 'sr_RS',
        'name' => 'Српски језик',
        'flag' => env('APP_URL') . '/flags/rs.png',
    ],
    'su_ID' => [
        'code' => 'su',
        'locale' => 'su_ID',
        'name' => 'Basa Sunda',
        'flag' => env('APP_URL') . '/flags/id.png',
    ],
    'sv_SE' => [
        'code' => 'sv',
        'locale' => 'sv_SE',
        'name' => 'Svenska',
        'flag' => env('APP_URL') . '/flags/se.png',
    ],
    'sw' => [
        'code' => 'sw',
        'locale' => 'sw',
        'name' => 'Kiswahili',
        'flag' => env('APP_URL') . '/flags/ke.png',
    ],
    'szl' => [
        'code' => 'szl',
        'locale' => 'szl',
        'name' => 'Ślōnskŏ gŏdka',
        'flag' => env('APP_URL') . '/flags/pl.png',
    ],
    'ta_IN' => [
        'code' => 'ta',
        'locale' => 'ta_IN',
        'name' => 'தமிழ்',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'ta_LK' => [
        'code' => 'ta',
        'locale' => 'ta_LK',
        'name' => 'தமிழ்',
        'flag' => env('APP_URL') . '/flags/lk.png',
    ],
    'tah' => [
        'code' => 'ty',
        'locale' => 'tah',
        'name' => 'Reo Tahiti',
        'flag' => env('APP_URL') . '/flags/pf.png',
    ],
    'te' => [
        'code' => 'te',
        'locale' => 'te',
        'name' => 'తెలుగు',
        'flag' => env('APP_URL') . '/flags/in.png',
    ],
    'th' => [
        'code' => 'th',
        'locale' => 'th',
        'name' => 'ไทย',
        'flag' => env('APP_URL') . '/flags/th.png',
    ],
    'tl' => [
        'code' => 'tl',
        'locale' => 'tl',
        'name' => 'Tagalog',
        'flag' => env('APP_URL') . '/flags/ph.png',
    ],
    'tr_TR' => [
        'code' => 'tr',
        'locale' => 'tr_TR',
        'name' => 'Türkçe',
        'flag' => env('APP_URL') . '/flags/tr.png',
    ],
    'tt_RU' => [
        'code' => 'tt',
        'locale' => 'tt_RU',
        'name' => 'Татар теле',
        'flag' => env('APP_URL') . '/flags/ru.png',
    ],
    'ug_CN' => [
        'code' => 'ug',
        'locale' => 'ug_CN',
        'name' => 'Uyƣurqə',
        'flag' => env('APP_URL') . '/flags/cn.png',
    ],
    'uk' => [
        'code' => 'uk',
        'locale' => 'uk',
        'name' => 'Українська',
        'flag' => env('APP_URL') . '/flags/ua.png',
    ],
    'ur' => [
        'code' => 'ur',
        'locale' => 'ur',
        'name' => 'اردو',
        'flag' => env('APP_URL') . '/flags/pk.png',
    ],
    'uz_UZ' => [
        'code' => 'uz',
        'locale' => 'uz_UZ',
        'name' => 'Oʻzbek',
        'flag' => env('APP_URL') . '/flags/uz.png',
    ],
    'vec' => [
        'code' => 'vec',
        'locale' => 'vec',
        'name' => 'Vèneto',
        'flag' => env('APP_URL') . '/flags/veneto.png',
    ],
    'vi' => [
        'code' => 'vi',
        'locale' => 'vi',
        'name' => 'Tiếng Việt',
        'flag' => env('APP_URL') . '/flags/vn.png',
    ],
    'zh_CN' => [
        'code' => 'zh',
        'locale' => 'zh_CN',
        'name' => '中文 (中国)',
        'flag' => env('APP_URL') . '/flags/cn.png',
    ],
    'zh_HK' => [
        'code' => 'zh',
        'locale' => 'zh_HK',
        'name' => '中文 (香港)',
        'flag' => env('APP_URL') . '/flags/hk.png',
    ],
    'zh_TW' => [
        'code' => 'zh',
        'locale' => 'zh_TW',
        'name' => '中文 (台灣)',
        'flag' => env('APP_URL') . '/flags/tw.png',
    ],
];
